### ISSUE TITLE
Excel to csv files

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/DataQualityDashboard#10]
The goal is for the dashboard to read off of four csv files specifying the checks (table, field, and concept) and the description of the checks. It is difficult to keep up with four files so it would be nice to have a mechanism that reads in the excel file and create the csvs from that.

**Comment by pavgra** [comment]
@clairblacketer , would also be nice to remove empty lines from the CSVs:
![image](https://user-images.githubusercontent.com/10010071/62827809-bb6d2100-bba5-11e9-84b9-fc03c5480c16.png)

**Comment by clairblacketer** [comment]
Closing this - ultimately it is less error prone to keep the four CSVs for now.
