### ISSUE TITLE
Add function to obtain checks for a CDM version

### ISSUE THREAD

**Issue by alondhe** [OHDSI/DataQualityDashboard#103]
Much like in Achilles, where we have getAnalysisDetails() which provides a data frame of all the analyses, let's add a function to be able to obtain the checks for a CDM version and for a given level.

getCheckDetails(cdmVersion, checkLevels = c("TABLE", "FIELD", "CONCEPT"))

**Comment by clairblacketer** [comment]
this was added as listDqChecks()
