### ISSUE TITLE
Need count of records checked(denominator), count of records failed (numerator)

### ISSUE THREAD

**Issue by schillil** [OHDSI/DataQualityDashboard#105]
I suspect this has been requested already, but I could only find request that mentioned numerator in JSON output.
Don't need to tell this group but this is key information for prioritizing DQ investigation/correction.
(now see "Similar to 4 existing issues" at the bottom of the comment box, I'll check that next)

**Comment by alondhe** [comment]
Hi @schillil -- we do have the numerators and denominators for every check result in the JSON and in the UI. Both are available in the drilldown of every check.

Have you installed the latest DQD?

**Comment by schillil** [comment]
Hi @alondhe Thank your for the quick response. It appears likely we have not, we're using the DQD for the FDA BEST project with IQVIA. I'll check to see if we need to be in synch with them or can upgrade liberally.
