### ISSUE TITLE
Add ability to identify presence of implausible codes

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/DataQualityDashboard#108]
Certain codes are never expected to be present at the same time together i.e. they cannot biologically occur together e.g. we ant have a congenital form and an acquired form of the same condition at the same time. It would be nice to know how frequently this exists in the data - at record level, on the same date or within a certain period.

A good starting point may be the codes considered Type1/Excludes1 in ICD10CM

**Comment by alondhe** [comment]
@gowthamrao -- would there be a temporal aspect as well? Meaning, condition1 and condition2 can only co-occur if they're > n days apart? Or would it just be a patient can't ever have both conditions at any point in their history?

**Comment by gowthamrao** [comment]
@alondhe yes, the codes should not exist at the same time (or time window). In theory we could make rules where the time-window may be very short to very long.

In general, i have seen this being used at the encounter level (equivalent to claim line level in US claims).

**Comment by alondhe** [comment]
Ah okay. So then in the CONCEPT csv, perhaps we can add 2 columns:

coOccurringConceptId
coOccurrenceMaxDays

The first would identify the concept that should not co-occur. The second would be the maximum allowable days between the concepts occurring. Perhaps we can use a value of -1 to indicate that both concepts should never occur in history.

**Comment by clairblacketer** [comment]
@gowthamrao Are there a list of these codes that cannot co-occur? Without a list we cannot implement this check.
