### ISSUE TITLE
Reporting dashbaord

### ISSUE THREAD

**Issue by vagarwal77** [OHDSI/DataQualityDashboard#114]
Hey, 

I am trying to build the dashboards on top of OMOP schemas and loved to see what is available @ 
http://www.ohdsi.org/web/achilles/#/OHDSI_Sample_Database/observationperiods

Can you please suggest in which OHDSI git repo i can get the reference code for these reporting dashboards which can get leveraged for my project? 

Thanks in advance!!

**Comment by alondhe** [comment]
Hi @vagarwal77 -- that is Achilles, which is in this repo: https://github.com/OHDSI/Achilles. Achilles generates summary level statistics on a CDM data source.

There's also a dashboard viewer of Achilles, called [AchillesWeb](https://github.com/OHDSI/AchillesWeb), but this is now deprecated in favor of viewing the dashboard results in Atlas.
