### ISSUE TITLE
Option to run DQD against a cohort

### ISSUE THREAD

**Issue by jimfrankfort** [OHDSI/DataQualityDashboard#115]
Our group would like to be able to run study specific DQ checks, so having the DQD run for personIDs belonging to a specific cohort would be very helpful.  

When considering how to implement please take the following into consideration: some cohorts cannot be defined by the cohort builder in Atlas, so we need a mechanism to pass the cohort other than with a cohortID.  e.g. before running DQD, we populate a table with PersonIDs....possibly using the table structure of the cohort table in Atlas.  When calling DQD we pass in the name of the table.

thanks!

**Comment by alondhe** [comment]
I think we'd allow for cohort selection from:

1. Cohorts authored by Atlas
2. Cohort-like tables located anywhere

**Comment by clairblacketer** [comment]
Hi @CartWill thanks for checking in. I am working now on making some fixes to the cohort code

**Comment by fdefalco** [comment]
This functionality has been added by @clairblacketer
