### ISSUE TITLE
when will the check id's stay consistently the same for each DQ reruns? what date are you expecting this feature to be added?

### ISSUE THREAD

**Issue by dir0417** [OHDSI/DataQualityDashboard#120]

**Comment by alondhe** [comment]
@dir0417 We have a proposal that will be presented during the next DQD working group call (Friday April 24). If it looks good, then we'll get to developing and testing the logic, which will take a few weeks at least. Earliest is probably end of May, but it's all dependent upon everyone's bandwidth.
