### ISSUE TITLE
Issue with DQD executeDqChecks function

### ISSUE THREAD

**Issue by marek05** [OHDSI/DataQualityDashboard#122]
I had an issue with DataQualityDashboard (DQD) executeDqChecks function. Specifically with .summarizeResults function. 

I used the master branch of DQD.

Issue description:

Checks ran but I was not able to write to table or json file.

I got the following output (I run only TABLE checks):
```
Connecting using PostgreSQL driver
Processing check description: measurePersonCompleteness
Connecting using PostgreSQL driver
Error in `$<-.data.frame`(`*tmp*`, "DQD_VERSION", value = "1.0.0") : 
  replacement has 1 row, data has 0
```

Solution:

I did some investigation in the source code and found that cdm_source table has to have at least one entry.

I think the problem is with [Line 446 in execution.R](https://github.com/OHDSI/DataQualityDashboard/blob/d30216b0c5f8df3a286935baad76dff1efd56119/R/execution.R#L446) or around that. 

We didn't have any entries in cdm_source table. After adding a row to cdm_source table, everything worked nicely and we could run DQD scripts and got table in database and could produce also a json file.

Maybe it is good idea to add to DQD github page info that cdm_source table has to have at least one entry or give a better error message.

**Comment by clairblacketer** [comment]
I agree it isn't clear - I am currently working on updating documentation to reflect this. The reason we require the CDM_SOURCE table to have a value is so that there is always some metadata attached to the results, at least with the database name
