### ISSUE TITLE
CDM_FIELD check: Oracle issue with CLOB columns

### ISSUE THREAD

**Issue by Andreyyiv** [OHDSI/DataQualityDashboard#123]
The `CDM_FIELD` check fails for `DRUG_EXPOSURE.SIG` and `NOTE.NOTE_TEXT` columns in Oracle with the following error:
`java.sql.SQLSyntaxErrorException: ORA-00932: inconsistent datatypes: expected - got CLOB`

This is the SQL for one of the checks:
```
SELECT
    num_violated_rows,
    CASE
        WHEN denominator.num_rows = 0 THEN 0
        ELSE 1.0 * num_violated_rows / denominator.num_rows
    END AS pct_violated_rows,
    denominator.num_rows   AS num_denominator_rows
FROM
    (
        SELECT
            num_violated_rows
        FROM
            (
                SELECT
                    CASE
                        WHEN COUNT("NOTE_TEXT") = 0 THEN 0
                        ELSE 0
                    END AS num_violated_rows
                FROM
                    note cdmtable
                GROUP BY
                    1
            ) violated_rows
    ) violated_row_count,
    (
        SELECT
            1 AS num_rows
        FROM
            dual
    ) denominator
;
```

The reason seems to be that these columns are of the CLOB type that has [certain restrictions in Oracle](https://docs.oracle.com/database/121/ADLOB/adlob_working.htm#ADLOB45148).

**Comment by clairblacketer** [comment]
@Andreyyiv in this case I would remove those fields from being evaluated or change the column type to one other than CLOB.

**Comment by katy-sadowski** [comment]
@tlecarrour-ee the suggestion is either to turn off these checks on these fields in your thresholds file, or change the datatype of these columns in your DB. let us know if you need further assistance :)

**Comment by tlecarrour-ee** [comment]
Crystal clear @katy-sadowski, thanks!
Turning off tests in DQD is right up my alley! 😎
