### ISSUE TITLE
plausibleValueLow check: Oracle error with cast(... as date) 

### ISSUE THREAD

**Issue by Andreyyiv** [OHDSI/DataQualityDashboard#125]
@alondhe @clairblacketer There are several statements in the _plausibleValueLow_ check with the following pattern: `cast('1950-01-01' as date)` (and similar with other values). In Oracle it results in `ORA-01861: literal does not match format string` error unless the `NLS_DATE_FORMAT` is set to `YYYY-MM-DD`. The date should be converted from the string literal with the explicit format like `to_date('1950-01-01', 'YYYY-MM-DD')`.

**Comment by alondhe** [comment]
@Andreyyiv I think this may be an issue for the SqlRender repo. I'm looking through the [replacement patterns CSV that SqlRender uses](https://github.com/OHDSI/SqlRender/blob/master/inst/csv/replacementPatterns.csv), and I'm not seeing a rule for handling cast('some date' as date).

**Comment by scossin** [comment]
I have the same error. 
Maybe another solution is to change the date string: 

This SQL produces an *ORA-01861: literal does not match format string* error: 
```
SELECT cast('1950-01-01' as date) FROM DUAL 
```
Whereas this SQL works fine for me: 
```
SELECT cast('01-01-1950' as date) FROM DUAL 
```

**Comment by clairblacketer** [comment]
I think there are some temporal checks that are not being evaluated because of issues like this. We should look at these dates and the getdate() functions

**Comment by clairblacketer** [comment]
@AnthonyMolinaro please check that the plausibleValueHigh and plausibleValueLow checks for dates are working as expected. Set sqlOnly  = TRUE, have it write the fully qualified sql statements for these checks and then run them in our environment to see that they are working.

**Comment by clairblacketer** [comment]
After evaluating this issue it seems to be an Oracle specific problem that we cannot address using SqlRender. In this case we recommend changing your date format to comply with the expected date format that DQD is using.
