### ISSUE TITLE
CDM Field check

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/DataQualityDashboard#127]
https://github.com/OHDSI/DataQualityDashboard/blob/1b13df7af4a82ee5516922afe5eb78691a5e013f/inst/sql/sql_server/field_cdm_field.sql#L21

@alondhe can you explain to me how this query works? Is this not always returning 0 or is there some smart trick used i am not aware off?

**Comment by clairblacketer** [comment]
@PRijnbeek I noticed that too- #121 is a similar issue

**Comment by PRijnbeek** [comment]
Ok. This step is taking a long time to run and i think we are waiting for 0 to be returned.
