### ISSUE TITLE
Postgres and CDM_DATATYPE check

### ISSUE THREAD

**Issue by alondhe** [OHDSI/DataQualityDashboard#13]
Hi @AnthonyMolinaro ,

Can you take a look at the CDM_DATATYPE sql template? Looks like in Postgres, the "~" operator isn't supported:

`ERROR: operator does not exist: integer ~ unknown   Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts. `

Thanks,
Ajit

**Comment by AnthonyMolinaro** [comment]
@alondhe:
Hi Ajit, I tested this on redshift and it seems to be working (sql render transforms isnumeric into a regex that seems to work fine).  What version of PG did you test against?

@fdefalco :   Frank, was this the error we saw the day of the hackathon?

**Comment by alondhe** [comment]
It's PG 11

**Comment by fdefalco** [comment]
Yes, it doesn't work on PG11, that was the error we saw at the hackathon.

**Comment by AnthonyMolinaro** [comment]
@alondhe 
Ok, so this is specifically an issue with how SqlRender converts ISNUMERIC() on PG11.  Perhaps this is an issue for SqlRender?

**Comment by alondhe** [comment]
Opened this issue: https://github.com/OHDSI/SqlRender/issues/188

**Comment by alondhe** [comment]
PR is in: https://github.com/OHDSI/SqlRender/pull/193

**Comment by conor-d-mcgrath** [comment]
Just checking on this. I have PG 10 with the same issue. This issue was merged to master in SqlRender as version 1.6.3. In my ~/R/x86_64-pc-linux-gnu-library/3.4/SqlRender/DESCRIPTION I see version 1.6.2 from installating cleanly yesterday.  I can look into getting this directly and try to apply it.

**Comment by clairblacketer** [comment]
Hi @conor-d-mcgrath is this still an issue?

**Comment by conor-d-mcgrath** [comment]
@clairblacketer I worked around the issue by dropping SqlRender 1.6.3 manually into my deployment at the time. I'm no longer working with OHDSI tools so Idon't know current state of play with this issue.

**Comment by fdefalco** [comment]
resolved in OHDSI/SqlRender#193
