### ISSUE TITLE
fail to execute command 

### ISSUE THREAD

**Issue by dongxuan5831** [OHDSI/DataQualityDashboard#131]
fail to execute command DataQuality:

detail information as below:

please help me to solve the problem.
Thanks a lot.

![cd6a7d64ed385e0ac6388ff7f816f41](https://user-images.githubusercontent.com/13995977/81916474-72e80580-9606-11ea-963c-035123a4ed1e.png)

**Comment by WoutV** [comment]
same problem as #122

**Comment by clairblacketer** [comment]
Hi @dongxuan5831 try inserting a record in the CDM_SOURCE table and then run again.

**Comment by dongxuan5831** [comment]
> Hi @dongxuan5831 try inserting a record in the CDM_SOURCE table and then run again.

It works.
Thanks a lot.
