### ISSUE TITLE
CDM Field check issue

### ISSUE THREAD

**Issue by dmitryilyn** [OHDSI/DataQualityDashboard#133]
Latest changes in https://github.com/OHDSI/DataQualityDashboard/blob/master/inst/sql/sql_server/field_cdm_field.sql
cause the checks to fail every time.

Even if the field being checked exists, the following script returns num_violated_rows = 1.
`select
case when count_big("@cdmFieldName") > 1 then 1
else 0
end as num_violated_rows
from @cdmDatabaseSchema.@cdmTableName cdmTable`

**Comment by clairblacketer** [comment]
Ah you’re right! I switched the 1 and 0. I’ll fix and create a new pull request

**Comment by dmitryilyn** [comment]
Thank you, Clair!
