### ISSUE TITLE
DQD should run checks as relevant to the CDM version it is checking

### ISSUE THREAD

**Issue by gklebanov** [OHDSI/DataQualityDashboard#138]
The data is CDM version 5.2.2
![image](https://user-images.githubusercontent.com/26966141/84167426-36140080-aa44-11ea-919a-3ae21b1eb600.png)

However, DQD is checking for tables that were introduced in version 5.3 and is showing it as an error 
![image](https://user-images.githubusercontent.com/26966141/84167520-580d8300-aa44-11ea-860b-14aa28942809.png)

DQ should take into consideration the OMOP CDM version and only check for relevant tables and business rules. Also, a lot of tables are not required to be populated or cannot be populated for certain data type (like cost and EHR data) or NOTES, we should not be displaying these as errors but rather warnings that tables are empty

**Comment by fdefalco** [comment]
Corrected by passing the cdmVersion parameter to the execution function.
