### ISSUE TITLE
Expose parameter values in HarnessV2.R?

### ISSUE THREAD

**Issue by AnthonyMolinaro** [OHDSI/DataQualityDashboard#14]
@fdefalco, @clairblacketer:

Would it be possible to return parameter values?  For example, a recent flatiron run shows that 100% of the drug_era rows violate check 513.  The sql follows:
```
SELECT num_violated_rows, 1.0*num_violated_rows/denominator.num_rows AS pct_violated_rows
FROM (
SELECT COUNT(violated_rows.violating_field) AS num_violated_rows
FROM(
SELECT 'PERSON.gender_concept_id' AS violating_field, PERSON.* 
FROM cdm.PERSON LEFT JOIN cdm.CONCEPT ON PERSON.gender_concept_id = CONCEPT.CONCEPT_ID
WHERE CONCEPT.DOMAIN_ID != '@fkDomain' OR CONCEPT.CONCEPT_CLASS_ID != '@fkClass' 
) violated_rows
) violated_row_count,
( SELECT COUNT(*) AS num_rows\r\n\tFROM cdm.PERSON ) denominator;
```
The checkResults data frame has the QUERY_TEXT column, making it easy to get the query:

```
checkResults[which(checkResults$CHECK_ID==513),"QUERY_TEXT"]
```
..however, it's hard to debug without the actual parameter values for @fkDomain and @fkClass.

Thanks!

**Comment by alondhe** [comment]
Try pulling the branch and using the execute() function over the harness script, I think that will help

**Comment by clairblacketer** [comment]
Additionally, I added parameters to the check descriptions for this reason

**Comment by AnthonyMolinaro** [comment]
Thanks.  Nice work!
