### ISSUE TITLE
Show list of checks run and the thresholds in the tool

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/DataQualityDashboard#144]

**Comment by clairblacketer** [comment]
Let's run the DQD on a synthetic data set and output the results to a csv that can be filtered and added to the website.

**Comment by DaveBarman** [comment]
Hello, I am going to help out with this issue and begin working on it today. Cheers.

**Comment by DaveBarman** [comment]
@clairblacketer Do you want the ultimate output to the cdm_results schema here? I can export the results from dqdashboard_results into a CSV. Let me know if this is suitable or if something else is what you are looking for.

**Comment by DaveBarman** [comment]
@clairblacketer I have created the output of Synthea OMOP CDM DQD results. Please review
[synthea_dqd_results.zip](https://github.com/OHDSI/DataQualityDashboard/files/5655094/synthea_dqd_results.zip)
