### ISSUE TITLE
Add option to filter dqd by care site, etc

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/DataQualityDashboard#147]
This should be added to the executeDqChecks function so that one JSON is created for each care_site, etc.

**Comment by sirli-tamm** [comment]
Hi @clairblacketer, I would like to complement that issue with an option to filter DQD by TYPE_CONCEPT_ID. We are hosting multiple data sources in one CDM database, so it would be helpful for us to see the results of DQD by the provenance of records.

**Comment by clairblacketer** [comment]
I need to think more about how we could implement this and if the filtering would at the database side how to do that with out increasing the processing time too much.

**Comment by fdefalco** [comment]
After discussion it was determined that data should be separated into individual CDMs.  Stratification across different variables for the DQD would not be practical in terms of query alterations and processing time.
