### ISSUE TITLE
Error on BigQuery

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/DataQualityDashboard#154]
I'm not sure if this is the write place to post this, but when I run DQD on BigQuery, I'm able to get to 100% in the progress bar; however, right afterwards I get the following error:

```
Error in `$<-.data.frame`(`*tmp*`, "DQD_VERSION", value = "1.0.0") : 
  replacement has 1 row, data has 0
```

This error occur before the JSON file is created. Even though I set the writeToTable variable to TRUE I did not see any table created in the specified dataset. I'm not sure if this is a DQD issue or a BQ issue or both. I'm thinking both.
@clairblacketer  @pavgra

**Comment by WoutV** [comment]
That error is caused because the **cdm_source** table is empty. If you add an entry in that table for the dataset you are checking, the error should disappear.

**Comment by clairblacketer** [comment]
Hi @cukarthik were you able to resolve this issue?

**Comment by cukarthik** [comment]
@clairblacketer I didn't see the above suggestion. I'll give it a try.

**Comment by cukarthik** [comment]
it worked. thanks, @WoutV !
