### ISSUE TITLE
The plausibleTemporalAfter check is never executed

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/DataQualityDashboard#164]
In the following lines the "plausibleTemporalAfter" is not included in the `checksToInclude` vector

https://github.com/OHDSI/DataQualityDashboard/blob/7b3a41287bb8c421281ae62736948369780a7c15/R/execution.R#L241-L246

**Comment by clairblacketer** [comment]
Ah I never noticed that! Thank you!

**Comment by MaximMoinat** [comment]
I made a quick fix by renaming the check to `plausibleTemporalAfterFieldName` in [_Check_Description.csv](https://github.com/OHDSI/DataQualityDashboard/blob/master/inst/csv/OMOP_CDMv5.3.1_Check_Descriptions.csv). 

The underlying cause is that the check name is `plausibleTemporalAfter` while the respective column in the [_Field_Level.csv](https://github.com/OHDSI/DataQualityDashboard/blob/master/inst/csv/OMOP_CDMv5.3.1_Field_Level.csv) is called `plausibleTemporalAfterFieldName`. A better solution would be to consistently use the "evaluationFilter".

**Comment by clairblacketer** [comment]
yep, agreed. I have a branch/PR ready for some bugfixes to v1.1 so I will add this to it.
