### ISSUE TITLE
checkIdentifiers.csv

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/DataQualityDashboard#165]
I came across the file [inst/csv/checkIdentifiers.csv](https://github.com/OHDSI/DataQualityDashboard/blob/master/inst/csv/checkIdentifiers.csv) while trying to modify the check definitions. I see no use of it in the scripts. 

Is this the remnant of testing or does it have some mysterious role? ;)

**Comment by clairblacketer** [comment]
@MaximMoinat this is a file I was playing with to try to assign DQD check ids to individual checks. Right now it serves no purpose in the scripts

**Comment by MaximMoinat** [comment]
Ok, thanks for clarifying. Would be a nice addition indeed, a unique identifier for each check. How about managing this through the OMOP vocabulary and create a concept_id for each?

I will close this issue.

**Comment by clairblacketer** [comment]
Thanks! So we have talked through a couple ideas, and a concept_id for each check was one of them. The other idea was to use the concepts for tables and fields that currently exist and concatenate them to represent the check itself, so like a Person_person_id_primarykey check would be something like an IP address with *person_concept_id.person_id_concept_Id.1* with 1 representing that the primary key check is the first one run, or something like that.
