### ISSUE TITLE
No output for the cdmField check

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/DataQualityDashboard#166]
## Expected
According to the [documentation](https://ohdsi.github.io/DataQualityDashboard/articles/CheckTypeDescriptions.html#cdmfield):
> For each table indicated this check will go through and determine if all fields are present as specified based on the CDM version. If the field is present, the resulting value will be 0; if the field is absent the resulting value will be 100.

## Observed
If a field is not present in my CDM, the check will fail and gives a `null` for the `num_violated_rows` column.
Also, none of the cdmField checks (failed or succeeded) appear in the DQ Dashboard.

**Footnote**
When looking at the code, I noticed that this `case` in the field_cdm_field.sql will always result in a 0.
https://github.com/OHDSI/DataQualityDashboard/blob/7b3a41287bb8c421281ae62736948369780a7c15/inst/sql/sql_server/field_cdm_field.sql#L20-L23

**Comment by clairblacketer** [comment]
Hi @MaximMoinat I am not sure why the cdmField check does not show up for you in the dashboard but I see it when I run it. They look like this:

![image](https://user-images.githubusercontent.com/12911960/89926954-9ace1180-dbd3-11ea-8522-f56908bba8e9.png)

and the reason that the case always results in a 0 is that it is a dummy query. If the cdm field does not exist then the query will error, causing a failure. This was the best way we could write this type of check without utilizing the system tables, which are very different from dbms to dbms.

**Comment by MaximMoinat** [comment]
Thanks @clairblacketer. It indeed works, I just couldn't find the failing check.

The description does not mention the field name that is not there. So when I searched for the field name the check did not come up. That is now clearer through the fix for #167 , where the field name can be added to the check results table.

**Comment by MaximMoinat** [comment]
Actually, can I propose to change the `cdmField` check description?

checkLevel | checkName | checkDescription | kahnContext | kahnCategory | kahnSubcategory | sqlFile | evaluationFilter
-- | -- | -- | -- | -- | -- | -- | --
FIELD | cdmField | A yes or no value indicating **@cdmFieldName is present** in the @cdmTableName table as expected based on the specification. | Verification | Conformance | Relational | field_cdm_field.sql | cdmFieldName!=''
