### ISSUE TITLE
Include more metadata in dashboard table (check name, OMOP table)

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/DataQualityDashboard#167]
I have found the check names are very useful to classify the raw results (e.g. isForeignKey or plausibleGender). Same for the OMOP table and field names. These are often more relevant than the Kahn category and contexts.

Would be possible to add a column with the checkName, OMOP table and field to this table?
![image](https://user-images.githubusercontent.com/17825660/89921185-a6cec900-dbfd-11ea-889e-0b4590f2c6ee.png)

**Comment by clairblacketer** [comment]
@MaximMoinat I agree they would be helpful, I will see about adding them

**Comment by clairblacketer** [comment]
@MaximMoinat check out PR #168 - I added the table name to the default UI and removed the kahn context. I also added in the cdm field name and check names as options in the column visibility button. They don't show up by default because they take up the screen but it is an option to turn them on.

**Comment by MaximMoinat** [comment]
Just tested the PR and works for me. Awesome and quickly solved!
