### ISSUE TITLE
How to display multiple DQD results?

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/DataQualityDashboard#170]
Let's say we have multiple DQD json outputs from multiple data sets (or multiple ETL runs on the same dataset). How can we show them all in the DQD RShiny application? I think I saw something like that in previous iterations of the DQD.

**Comment by clairblacketer** [comment]
@fdefalco can you describe how you do this for JnJ?

**Comment by clairblacketer** [comment]
Hi @MaximMoinat let's talk about this a little more. I don't know that DQD is the correct place for this feature but it might be. There was a recent indexing function added by Frank that could take a step in this direction by indexes all json files in a folder. We would need to then update the shiny application to read that index.

**Comment by fdefalco** [comment]
The included DQD shiny application will only support a single result.  There is work on a new interface called ARES that will provide an integrated Achilles/DQD experience and have multi-source as well as DQD over time reporting capabilities.
