### ISSUE TITLE
Remove dependency on cdm_source

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/DataQualityDashboard#171]
If the `cdm_source` table is empty, the DQD gives the following error:
```
Error in `$<-.data.frame`(`*tmp*`, "DQD_VERSION", value = "1.0.0") : 
  replacement has 1 row, data has 0
```
Can we make it optional to read from the `cdm_source` table? If there is no record, we just leave the metadata for the DQD empty (or use the name provided in `cdmSourceName`).

**Comment by clairblacketer** [comment]
Hi @MaximMoinat I agree this is an issue but I am uncomfortable totally removing the dependency on the cdm_source altogether. I like your commit though and one idea we have in the DQD development group is to move this to the beginning of the DQD execution so you don't have to wait hours only to find out you don't have metadata and to lose all your work. I will add this to our v1.4 milestone.

**Comment by MaximMoinat** [comment]
I like you suggestion. It would already greatly help if this dependency check is at the beginning AND outputs a clear error about cdm_source not being populated.

About removing the dependency on the table; would you be ok with the option of supplying the cdm_source information through parameters of the DQD execute function? (like already implemented for `cdmSourceName`)

**Comment by katy-sadowski** [comment]
Looks like this is planned for resolution in the next release, which is awesome :) just wanted to add my upvote for this one, particularly the option to bypass the dependency by supplying cdm_source information as parameters rather than by reading from the table.  Thanks!

**Comment by mgkahn** [comment]
Kahn also adds an upvote for both discussed enhancements: Early validation check for the cdm_source table and, if not present, look for values in config parts. Or perhaps sequenced the other way around (look in config then cdm_source).
