### ISSUE TITLE
Execution Time in Results

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/DataQualityDashboard#174]
It would be nice to have the time the DQD was run to be stored in the table output. The time is rendered in shiny app so it must be in the JSON, so maybe it's embedded in the table somewhere, but it would be nice for it to be a separate column for trending purposes in the future.

**Comment by clairblacketer** [comment]
Thanks @cukarthik I agree. I added this to an expected milestone of v1.4

**Comment by fdefalco** [comment]
The execution time of the individual checks are currently written out for each row in the result table.  Are you looking for the overall  DataQualityDashboard execution time?  This is stored in the json file that is output from the process.
