### ISSUE TITLE
Support for R 4.0

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/DataQualityDashboard#177]
I recently had to upgrade my R instance and when I try to install DQD, I get the following error:

`> install.packages("DataQualityDashboard")
Installing package into ‘C:/Users/kan7003/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘DataQualityDashboard’ is not available (for R version 4.0.2)
Warning in install.packages :
  unable to access index for repository https://OHDSI.github.io/drat/bin/windows/contrib/4.0:
  cannot open URL 'https://OHDSI.github.io/drat/bin/windows/contrib/4.0/PACKAGES'`

**Comment by clairblacketer** [comment]
Thanks for bringing this up @cukarthik. We will work to get this resolved

**Comment by cukarthik** [comment]
I got it to work when I installed using this command:

```install_github("OHDSI/DataQualityDashboard)```
