### ISSUE TITLE
Error when writing JSON to table

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/DataQualityDashboard#181]
When I call the write json to table function, I get the below error regarding cdm_field_name. The table definition does not seem to have the column name.

> DataQualityDashboard::writeJsonResultsToTable(connectionDetails = connectionDetails, 
                                               resultsDatabaseSchema = resultsDatabaseSchema, 
                                               jsonFilePath = jsonFilePath)
Connecting using SQL Server driver using Windows integrated security
  |==========================================================================================| 100%
Executing SQL took 0.016 secs
java.sql.BatchUpdateException: Invalid column name 'CDM_FIELD_NAME'.
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:1178)
	at org.ohdsi.databaseConnector.BatchedInsert.executeBatch(BatchedInsert.java:110)

**Comment by clairblacketer** [comment]
Hi @cukarthik I added an additional fix for that function to the recent release [v1.3](https://github.com/OHDSI/DataQualityDashboard/releases/tag/1.3). Try that and let me know if it works.

**Comment by fdefalco** [comment]
Fixed in https://github.com/OHDSI/DataQualityDashboard/releases/tag/1.3
