### ISSUE TITLE
Results table not showing up (due to offline use ??)

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [OHDSI/DataQualityDashboard#184]
Running `viewDqDasboard` on the results.json in inst/shinyApps/www/results.json (same issue in own results json)

The table for results does not appear.  

![image](https://user-images.githubusercontent.com/54809193/97407741-c8d60e80-1903-11eb-85be-2327ad0b55e0.png)

I'm on an offline virtual machine. Is the error due to not finding online resources ??

Any way to fix this ??

thanks

**Comment by clairblacketer** [comment]
Hi @javier-gracia-tabuenca-tuni I think this is a javascript error and you may want to reload your cache.
