### ISSUE TITLE
Proposal to Sub-categorize Failures

### ISSUE THREAD

**Issue by RogerJCarlson** [OHDSI/DataQualityDashboard#186]
In our own data quality checks, we sub-categorize failures four ways:

- **Fatal**: records that won’t even load into an OMOP database

> - Null in a concept_id field
> - Non-standard concept in a concept_id field

- **Warning**: May or may not be wrong. 

> - usually source_to_concept_map mapping issues
> - if these jump rapidly, there may be new concepts to map

- **Expected**: errors I know will always happen

> - Usually zero in  *_source_concept_id fields that I know our system does not have.

- **Invalid Data**: data that will go into the database, but will throw a Data Quality Dashboard error

> - End Date before Start Date

> - Visit Date Disparity

This way we can easily see those errors which are most important to us.

This sub-categorization should be editable like thresholds, so individuals can decide which errors are most important to them.

**Comment by clairblacketer** [comment]
Thank you @RogerJCarlson! We will need to spend some time thinking through how to implement this but I think it is a great idea.
