### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by yilingchenn** [OHDSI/DataQualityDashboard#187]
Hi, I am new to OHDSI OMOP CDM and want to learn more about the data quality dashboard! However, when I run the command in R Studio:
`install.packages("DataQualityDashboard")` 
it returns this:
`package ‘DataQualityDashboard’ is not available (for R version 3.6.3)`

Is there any way to fix this? Thanks!

**Comment by fdefalco** [comment]
The DataQualityDashboard is not currently a package available through CRAN.  Installation can be completed as follows:

library(devtools)
devtools::install_github("OHDSI/DataQualityDashboard")
