### ISSUE TITLE
Does not allow viewing results after an error

### ISSUE THREAD

**Issue by don-torok** [OHDSI/DataQualityDashboard#188]
DQ has a nasty trait of continuing to run after an error, but then failing at the end and not showing result.  Just ran for two days and then DQ said it failed with an error, even though the error happen in the first hour of running.  Options: 1) report the error, but at the end display the results it has. 2) Stop running and tell the user results will not display, but give option to continue running to discover if there are other errors.

**Comment by clairblacketer** [comment]
@don-torok that's weird. Usually if I get an error the results will still be written, just the result of that one check is an error rather than the percent failed. Did it not produce the json at all?

**Comment by don-torok** [comment]
Now I have to admit I did not check to see if json file created.  Put this on hold until I can confirm :)

**Comment by fdefalco** [comment]
Will reopen upon confirmation of issue.
