### ISSUE TITLE
OMOP_CDMv5.3.1_Field_Level.csv PAYER_PLAN_PERIOD.payer_plan_period_id  is Foreign Key to person.person_id

### ISSUE THREAD

**Issue by don-torok** [OHDSI/DataQualityDashboard#190]
OMOP_CDMv5.3.1_Field_Level.csv PAYER_PLAN_PERIOD.payer_plan_period_id  is Foreign Key to person.person_id

**Comment by clairblacketer** [comment]
addressed by PR #273 for CDM v5.4 and PR #286 for v5.2.2 and v5.3
