### ISSUE TITLE
Interesting features to get inspired from DQueen

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/DataQualityDashboard#197]
### Expected behavior

num column and text column (in addition to count value)

https://github.com/ABMI/DQUEEN_OMOP_CDM_Version/blob/887f9418d02eae685aaaf2084162fc009426740e/inst/sql/sql_server/DQA_Level_2/cdm/117_261_262_check_the_missing_value_of_specimen.sql#L11

![image](https://user-images.githubusercontent.com/7526119/92930739-794d8900-f410-11ea-9749-8b5de5df4312.png)

**Comment by stephanieshong** [comment]
https://github.com/ABMI/DQUEEN_OMOP_CDM_Version/blob/887f9418d02eae685aaaf2084162fc009426740e/inst/sql/sql_server/DQA_Level_2/cdm/117_261_262_check_the_missing_value_of_specimen.sql#L11 - this link is not found?

**Comment by don-torok** [comment]
This link works
best list of rules is https://github.com/ABMI/DQUEEN_OMOP_CDM_Version/blob/master/inst/csv/rules/DQA_check_of_dqueen.csv

**Comment by clairblacketer** [comment]
closing this as it is a dup and looks like some was moved to achilles

**Comment by stephanieshong** [comment]
@clairblacketer -Is there a way for me to link the checks listed in the csv file to the actual sql statement in the data quality check dashboard without running the shiny app?

**Comment by clairblacketer** [comment]
Hi @stephanieshong you could run the DQD setting `sqlOnly = TRUE` which would output for you a file per sql statement rather than running the entire thing.
