### ISSUE TITLE
Minor: sometimes inconsistent indentation in query formatting

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/DataQualityDashboard#200]
Minor feature request to improve readability of the queries. I know this might be hard as the queries are generated dynamically, but it would be doable (I think, haven't tried yet) to have consistent indentation and capitalisation. 

e.g. this inner query (violated rows)
```sql
	SELECT COUNT(violated_rows.violating_field) AS num_violated_rows
	FROM
	(
		SELECT 'VISIT_DETAIL.visit_detail_end_date' AS violating_field, cdmTable.*
    from omopcdm.VISIT_DETAIL cdmTable
    
		join omopcdm.VISIT_OCCURRENCE plausibleTable
			on cdmTable.person_id = plausibleTable.person_id
		
		
    where cast(VISIT_DETAIL_START_DATE as date) > cast(cdmTable.visit_detail_end_date as date)
	) violated_rows
```

would become
```sql
SELECT COUNT(violated_rows.violating_field) AS num_violated_rows
FROM
(
    SELECT 'VISIT_DETAIL.visit_detail_end_date' AS violating_field, cdmTable.*
    FROM omopcdm.VISIT_DETAIL cdmTable
    JOIN omopcdm.VISIT_OCCURRENCE plausibleTable
       ON cdmTable.person_id = plausibleTable.person_id
    WHERE cast(VISIT_DETAIL_START_DATE as date) > cast(cdmTable.visit_detail_end_date as date
) violated_rows
```

**Comment by MaximMoinat** [comment]
Note: I noticed that for many other queries the formatting is actually very consistent. So the example given above might actually be one of the few exceptions.

Good job!

**Comment by clairblacketer** [comment]
Hi @MaximMoinat I have struggled with the formatting because these gaps happen due to the inclusion of SqlRender IF statements. I will play with it to see if I can make it look nicer

**Comment by fdefalco** [comment]
I have a PR coming up that will improve this.  It is worth noting that ongoing work with a new interface includes improved SQL formatting that will also aid in readability.

**Comment by MaximMoinat** [comment]
Awesome, thanks @clairblacketer and @fdefalco! ✨
