### ISSUE TITLE
Question - No of checks 1493 or  3,351

### ISSUE THREAD

**Issue by Ak784** [OHDSI/DataQualityDashboard#204]
Hello Everyone,

I was reading the documentation of DQD and going through the `inst/csv` file for understanding the checks.

I counted the no of checks (rows) in csv files and they add upto 1493 checks

But then I see that in document it is mentioned as 3351. 

May I know how is this number of 3351 arrived?

**Comment by clairblacketer** [comment]
Hi @Ak784 Many of the 3,351 checks are measurement and gender plausibility checks found in the Concept Level checks file.
