### ISSUE TITLE
Include timestamps in log output

### ISSUE THREAD

**Issue by filipmaljkovic** [OHDSI/DataQualityDashboard#208]
<div id="expected-behavior" class="section level3">
<h3 class="hasAnchor">
<a href="#expected-behavior" class="anchor"></a>Expected behavior</h3>
</div>
Timestamps should appear in log for every query that's being run.
<div id="actual-behavior" class="section level3">
<h3 class="hasAnchor">
<a href="#actual-behavior" class="anchor"></a>Actual behavior</h3>
</div>
No timestamps in the log output, making it hard to discern when certain things happened.
<div id="steps-to-reproduce-behavior" class="section level3">
<h3 class="hasAnchor">
<a href="#steps-to-reproduce-behavior" class="anchor"></a>Steps to reproduce behavior</h3>
</div>
Just run DataQualityDashboard::executeDqChecks(...)

**Comment by fdefalco** [comment]
The log and output files have a start timestamp, end timestamp, and the check results contains execution duration for every query that is run.  Is there something else you're looking for?

**Comment by filipmaljkovic** [comment]
That's weird, R Studio output for me doesn't include any timestamp. Do I have to configure something?
```
Connecting using PostgreSQL driver
Processing check description: measurePersonCompleteness
Processing check description: cdmField
Processing check description: isRequired
Processing check description: cdmDatatype
Processing check description: isPrimaryKey
Processing check description: isForeignKey
Processing check description: fkDomain
Processing check description: fkClass
Processing check description: isStandardValidConcept
Processing check description: measureValueCompleteness
Processing check description: standardConceptRecordCompleteness
Processing check description: sourceConceptRecordCompleteness
Processing check description: sourceValueCompleteness
Processing check description: plausibleValueLow
Processing check description: plausibleValueHigh
Processing check description: plausibleTemporalAfter
Processing check description: plausibleDuringLife
Processing check description: plausibleValueLow
Processing check description: plausibleValueHigh
Processing check description: plausibleGender
Connecting using PostgreSQL driver
Execution Complete
Connecting using PostgreSQL driver
Writing results to table results.dqdashboard_results
```

**Comment by fdefalco** [comment]
Ah, I understand.  The timestamps appear in the log file (usually output/<data source name>/log_DqDashboard_<data source name>.txt.  We could add them so they appear in the R console output as well.

Here is what appears in the log:

2021-03-08 09:15:23	[Main thread]	INFO	DataQualityDashboard	FUN	Processing check description: isRequired
2021-03-08 09:15:27	[Main thread]	INFO	DataQualityDashboard	FUN	Processing check description: cdmDatatype
2021-03-08 09:15:36	[Main thread]	INFO	DataQualityDashboard	FUN	Processing check description: isPrimaryKey
2021-03-08 09:15:38	[Main thread]	INFO	DataQualityDashboard	FUN	Processing check description: isForeignKey
2021-03-08 09:16:38	[Main thread]	INFO	DataQualityDashboard	FUN	Processing check description: fkDomain
2021-03-08 09:17:15	[Main thread]	INFO	DataQualityDashboard	FUN	Processing check description: fkClass
2021-03-08 09:17:17	[Main thread]	INFO	DataQualityDashboard	FUN	Processing check description: isStandardValidConcept
2021-03-08 09:17:59	[Main thread]	INFO	DataQualityDashboard	FUN	Processing check description: measureValueCompleteness

**Comment by filipmaljkovic** [comment]
Yes, please add it in the console output, since that's the main place where we execute code and going through several logs (for several tools) could be tedious work.
