### ISSUE TITLE
Add support for Spark SQL

### ISSUE THREAD

**Issue by sdebruyn** [OHDSI/DataQualityDashboard#213]
Most big data organisations are using data lakes and process their data with Apache Spark. Adding support for Apache Spark would be very useful.

**Comment by fdefalco** [comment]
Support for different database platforms is managed by the OHDSI/SqlRender package.  Queries in all other packages are written once and then translated using OHDSI/SqlRender.  Individual packages such as DQD do not add platform specific support.
