### ISSUE TITLE
Syntax error due to a clash between OFFSET CDM attribute and Postgresql keyword

### ISSUE THREAD

**Issue by vpapez** [OHDSI/DataQualityDashboard#219]
[Field_cdm_field.sql](https://github.com/OHDSI/DataQualityDashboard/blob/master/inst/sql/sql_server/field_cdm_field.sql) script returns a syntax error ([log](https://github.com/OHDSI/DataQualityDashboard/files/6152106/FIELD_cdmField_NOTE_NLP_OFFSET.txt)). A name of the attribute 'offset' (OMOP CDM table 'note_nlp') is also a postgresql keyword. Issue probably occurs due to the latest [commit](https://github.com/OHDSI/DataQualityDashboard/commit/ca22085eaf1a033d93e74ce7474c8f46dc864b15#diff-37006f148ef5bad3ec3126b49053651089eb95bae7b4206f988ab7b86e8175f4).

Environment: Postgresql v 11:11, OMOP CDM v5.3.1, DQD v1.3.1

**Comment by ericaVoss** [comment]
I have seen this too . . . I think a double quote removes the issue?

Tagging @mgadetta

**Comment by vpapez** [comment]
> I have seen this too . . . I think a double quote removes the issue?
> 
> Tagging @mgadetta

Yup, probably. I put a table name variable in front of it which worked fine as well (ln 21: 'case when count_big(cdmTable.@cdmFieldName) = 0 then 0')

**Comment by clairblacketer** [comment]
duplicate issue around offset. PR #273 fixes this by removing offset from being evaluated altogether as it is a reserved word in many DBMS's and has been causing problems.
