### ISSUE TITLE
Error: replacement has 0 rows, data has 1 

### ISSUE THREAD

**Issue by cwallaceacr** [OHDSI/DataQualityDashboard#223]
When running the DQD we are getting this error:

Connecting using SQL Server driver
Warning: NAs introduced by coercion
Warning: NAs introduced by coercion
Error in `$<-.data.frame`(`*tmp*`, "THRESHOLD_VALUE", value = integer(0)) : 
  replacement has 0 rows, data has 1

I see a similar issue here but apparently that was fixed, and here I'm seeing replacement has 0 rows instead of 2. Any help would be appreciated, thanks!

**Comment by clairblacketer** [comment]
@cwallaceacr is this still an issue for you? We pushed some changes that should have fixed it, just want to follow-up

**Comment by clairblacketer** [comment]
Closing for now, @cwallaceacr please let me know if you are still having a problem and we can reopen
