### ISSUE TITLE
Operand type clash: datetime2 is incompatible with int

### ISSUE THREAD

**Issue by sdebruyn** [OHDSI/DataQualityDashboard#224]
I attached a list of files. These are all errors I get when running DQD v1.3.1 on my OMOP v5.3.1 CDM hosted on Azure SQL Database. It seems to be related to how the SQL scripts are generated and it tries to compare ints with dates (I think the dates should be encapsulated in quotes).

[FIELD_plausibleValueLow_DRUG_EXPOSURE_drug_exposure_end_datetime.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213174/FIELD_plausibleValueLow_DRUG_EXPOSURE_drug_exposure_end_datetime.txt)
[FIELD_plausibleValueLow_VISIT_OCCURRENCE_visit_end_datetime.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213175/FIELD_plausibleValueLow_VISIT_OCCURRENCE_visit_end_datetime.txt)
[FIELD_plausibleValueLow_DRUG_EXPOSURE_verbatim_end_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213176/FIELD_plausibleValueLow_DRUG_EXPOSURE_verbatim_end_date.txt)
[FIELD_plausibleValueLow_OBSERVATION_observation_datetime.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213177/FIELD_plausibleValueLow_OBSERVATION_observation_datetime.txt)
[FIELD_plausibleValueLow_OBSERVATION_PERIOD_observation_period_end_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213179/FIELD_plausibleValueLow_OBSERVATION_PERIOD_observation_period_end_date.txt)
[FIELD_plausibleValueLow_NOTE_NLP_nlp_datetime.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213180/FIELD_plausibleValueLow_NOTE_NLP_nlp_datetime.txt)
[FIELD_plausibleValueLow_DRUG_EXPOSURE_drug_exposure_start_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213181/FIELD_plausibleValueLow_DRUG_EXPOSURE_drug_exposure_start_date.txt)
[FIELD_plausibleValueLow_DEVICE_EXPOSURE_device_exposure_start_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213182/FIELD_plausibleValueLow_DEVICE_EXPOSURE_device_exposure_start_date.txt)
[FIELD_plausibleValueLow_CONDITION_ERA_condition_era_start_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213183/FIELD_plausibleValueLow_CONDITION_ERA_condition_era_start_date.txt)
[FIELD_plausibleValueLow_DRUG_ERA_drug_era_end_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213184/FIELD_plausibleValueLow_DRUG_ERA_drug_era_end_date.txt)
[FIELD_plausibleValueLow_CONDITION_OCCURRENCE_condition_end_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213185/FIELD_plausibleValueLow_CONDITION_OCCURRENCE_condition_end_date.txt)
[FIELD_plausibleValueLow_OBSERVATION_PERIOD_observation_period_start_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213186/FIELD_plausibleValueLow_OBSERVATION_PERIOD_observation_period_start_date.txt)
[FIELD_plausibleValueLow_NOTE_note_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213187/FIELD_plausibleValueLow_NOTE_note_date.txt)
[FIELD_plausibleValueLow_DEVICE_EXPOSURE_device_exposure_start_datetime.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213188/FIELD_plausibleValueLow_DEVICE_EXPOSURE_device_exposure_start_datetime.txt)
[FIELD_plausibleValueLow_CONDITION_OCCURRENCE_condition_end_datetime.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213189/FIELD_plausibleValueLow_CONDITION_OCCURRENCE_condition_end_datetime.txt)
[FIELD_plausibleValueLow_DRUG_ERA_drug_era_start_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213190/FIELD_plausibleValueLow_DRUG_ERA_drug_era_start_date.txt)
[FIELD_plausibleValueLow_CONDITION_OCCURRENCE_condition_start_datetime.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213191/FIELD_plausibleValueLow_CONDITION_OCCURRENCE_condition_start_datetime.txt)
[FIELD_plausibleValueLow_VISIT_DETAIL_visit_detail_end_datetime.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213192/FIELD_plausibleValueLow_VISIT_DETAIL_visit_detail_end_datetime.txt)
[FIELD_plausibleValueLow_CONDITION_ERA_condition_era_end_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213193/FIELD_plausibleValueLow_CONDITION_ERA_condition_era_end_date.txt)
[FIELD_plausibleValueLow_NOTE_note_datetime.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213194/FIELD_plausibleValueLow_NOTE_note_datetime.txt)
[FIELD_plausibleValueLow_VISIT_OCCURRENCE_visit_start_datetime.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213195/FIELD_plausibleValueLow_VISIT_OCCURRENCE_visit_start_datetime.txt)
[FIELD_plausibleValueLow_VISIT_DETAIL_visit_detail_end_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213196/FIELD_plausibleValueLow_VISIT_DETAIL_visit_detail_end_date.txt)
[FIELD_plausibleValueLow_VISIT_DETAIL_visit_detail_start_datetime.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213197/FIELD_plausibleValueLow_VISIT_DETAIL_visit_detail_start_datetime.txt)
[FIELD_plausibleValueLow_OBSERVATION_observation_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213198/FIELD_plausibleValueLow_OBSERVATION_observation_date.txt)
[FIELD_plausibleValueLow_DEVICE_EXPOSURE_device_exposure_end_datetime.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213199/FIELD_plausibleValueLow_DEVICE_EXPOSURE_device_exposure_end_datetime.txt)
[FIELD_plausibleValueLow_DEVICE_EXPOSURE_device_exposure_end_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213200/FIELD_plausibleValueLow_DEVICE_EXPOSURE_device_exposure_end_date.txt)
[FIELD_plausibleValueLow_VISIT_OCCURRENCE_visit_start_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213201/FIELD_plausibleValueLow_VISIT_OCCURRENCE_visit_start_date.txt)
[FIELD_plausibleValueLow_PROCEDURE_OCCURRENCE_procedure_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213202/FIELD_plausibleValueLow_PROCEDURE_OCCURRENCE_procedure_date.txt)
[FIELD_plausibleValueLow_DOSE_ERA_dose_era_start_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213203/FIELD_plausibleValueLow_DOSE_ERA_dose_era_start_date.txt)
[FIELD_plausibleValueLow_VISIT_OCCURRENCE_visit_end_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213204/FIELD_plausibleValueLow_VISIT_OCCURRENCE_visit_end_date.txt)
[FIELD_plausibleValueLow_MEASUREMENT_measurement_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213167/FIELD_plausibleValueLow_MEASUREMENT_measurement_date.txt)
[FIELD_plausibleValueLow_VISIT_DETAIL_visit_detail_start_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213168/FIELD_plausibleValueLow_VISIT_DETAIL_visit_detail_start_date.txt)
[FIELD_plausibleValueLow_CONDITION_OCCURRENCE_condition_start_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213169/FIELD_plausibleValueLow_CONDITION_OCCURRENCE_condition_start_date.txt)
[FIELD_plausibleValueLow_DOSE_ERA_dose_era_end_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213170/FIELD_plausibleValueLow_DOSE_ERA_dose_era_end_date.txt)
[FIELD_plausibleValueLow_DRUG_EXPOSURE_drug_exposure_start_datetime.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213171/FIELD_plausibleValueLow_DRUG_EXPOSURE_drug_exposure_start_datetime.txt)
[FIELD_plausibleValueLow_PROCEDURE_OCCURRENCE_procedure_datetime.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213172/FIELD_plausibleValueLow_PROCEDURE_OCCURRENCE_procedure_datetime.txt)
[FIELD_plausibleValueLow_DRUG_EXPOSURE_drug_exposure_end_date.txt](https://github.com/OHDSI/DataQualityDashboard/files/6213173/FIELD_plausibleValueLow_DRUG_EXPOSURE_drug_exposure_end_date.txt)

**Comment by clairblacketer** [comment]
Thanks @sdebruyn. Right now the DataQualityDashboard relies on SqlRender to translate the sql statements to the proper dbms format. Since SqlRender does not support Azure sql that is most likely the source of the error.

**Comment by sdebruyn** [comment]
Azure SQL is just ms sql in the cloud, the language differences are minimal and only related to stored procedures and security settings.

**Comment by sdebruyn** [comment]
Issue was on my side. I had to put quotes around the dates
