### ISSUE TITLE
SPECIMEN.VALUE_AS_NUMBER Check

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/DataQualityDashboard#236]
Is DQD trying to check SPECIMEN.VALUE_AS_NUMBER in CDM V5.3.1?  I don't think this column is in this version of the CDM.

![image](https://user-images.githubusercontent.com/6305439/125793349-6869e3e5-f42e-4987-b3c6-4f10e059b0cb.png)

**Comment by clairblacketer** [comment]
This is related to a fix I was trying to implement related to MEASUREMENT and OBSERVATION. It has since been addressed.
