### ISSUE TITLE
Error : The folder location pathToDriver = '  ' does not exist

### ISSUE THREAD

**Issue by scossin** [OHDSI/DataQualityDashboard#237]
```R
# fill out the connection details -----------------------------------------------------------------------
connectionDetails <- DatabaseConnector::createConnectionDetails(dbms = "", user = "", 
                                                                password = "", server = "", 
                                                                port = "", extraSettings = "")
```
I'm using DatabaseConnector package version 4.0.0, the createConnectionDetails requires a "pathToDriver" parameter. 

The error occurs here : https://github.com/OHDSI/DatabaseConnector/blob/8a34f01d92a11832cb2bdb07e44385f33e428802/R/Connect.R#L72

**Comment by clairblacketer** [comment]
Thanks @scossin. You're correct, we did not update this call when the DatabaseConnector package upddated.

**Comment by fdefalco** [comment]
The preferred approach here is to set an environment variable that points to your drivers.  The documentation on how to set up your environment can be found [here](http://ohdsi.github.io/DatabaseConnector/articles/Connecting.html).
