### ISSUE TITLE
plausibleValueLow of CONCEPT_ID 3015377 (CALCIUM [MOLES/VOLUME] IN SERUM OR PLASMA) and UNIT_CONCEPT_ID 8753 (MILLIMOLE PER LITER)

### ISSUE THREAD

**Issue by scossin** [OHDSI/DataQualityDashboard#238]
I would like to report a possible incorrect plausibleValueLow of **7** of CONCEPT_ID 3015377 (CALCIUM [MOLES/VOLUME] IN SERUM OR PLASMA) and UNIT_CONCEPT_ID 8753 (MILLIMOLE PER LITER). 

According to [wikipedia](https://en.wikipedia.org/wiki/Hypercalcaemia), the normal range is 2.1–2.6 mmol/L

The value is set at this line in the OMOP_CDMv5.3.1_Concept_Level.csv file: https://github.com/OHDSI/DataQualityDashboard/blob/master/inst/csv/OMOP_CDMv5.3.1_Concept_Level.csv#L649

The SQL returns 100% of violated rows :
```sql
SELECT num_violated_rows, CASE WHEN denominator.num_rows = 0 THEN 0 ELSE 1.0*num_violated_rows/denominator.num_rows END  AS pct_violated_rows, 
  denominator.num_rows as num_denominator_rows
FROM (SELECT COUNT(*) AS num_violated_rows
	FROM (SELECT m.* 
		FROM OMOP.MEASUREMENT m
		
		  WHERE m.MEASUREMENT_CONCEPT_ID =  3015377
		AND m.unit_concept_id =     8753
		AND m.value_as_number IS NOT NULL
		AND m.value_as_number <      7.000
	 ) violated_rows
 ) violated_row_count,
(SELECT COUNT(*) AS num_rows
	FROM OMOP.MEASUREMENT m
	
	  WHERE m.MEASUREMENT_CONCEPT_ID =  3015377
	AND unit_concept_id =     8753
	AND value_as_number IS NOT NULL
 ) denominator
 ;
```

This was the only plausibleValueLow error we had on our dataset.

**Comment by clairblacketer** [comment]
this is another one that would be good for a non-coder. We do not want to set the normal range as the biologically plausible range as the biologically plausible range should be wider. However, this should be addressed.

**Comment by clairblacketer** [comment]
I am closing this as we implemented new measurement checks looking for plausible units and we removed the plausible value checks.
