### ISSUE TITLE
Unable to install "DataQualityDashboard" package

### ISSUE THREAD

**Issue by qianjiawei123456** [OHDSI/DataQualityDashboard#239]
Hi, I am a OHDSI member from IQVIA and I am preparing OHDSI-in-a-box for training. However, DQD can not be launched from RStudio. The ERROR is: "there is no package called: DataQualityDashboard".  
Then I tried to install it using **command below**, but failed: 

library(devtools)
devtools::install_github("OHDSI/DataQualityDashboard")

Therefore, do you know why and how I can install "DataQualityDashboard" and launch it successfully? 
Thanks

![image](https://user-images.githubusercontent.com/84256452/128373362-c0faabbd-4565-4239-bdcd-c371e04c1ba2.png)

**Comment by don-torok** [comment]
Try building the source package.  Under Build tab.

**Comment by konstjar** [comment]
DatabaseConnector package requires Java SDK to be installed.
Please follow setup steps here:
https://github.com/OHDSI/DatabaseConnector#system-requirements

**Comment by clairblacketer** [comment]
closing this as it is related to DatabaseConnector
