### ISSUE TITLE
Note_NLP Redshift Issue

### ISSUE THREAD

**Issue by prunk1al** [OHDSI/DataQualityDashboard#245]
SELECT num_violated_rows, CASE WHEN denominator.num_rows = 0 THEN 0 ELSE 1.0*num_violated_rows/denominator.num_rows END AS pct_violated_rows, 
  denominator.num_rows as num_denominator_rows
FROM
(
  select num_violated_rows from
  (
    select
      case when COUNT(OFFSET) = 0 then 0
      else 0
    end as num_violated_rows
    from idival.NOTE_NLP cdmTable
  ) violated_rows
) violated_row_count,
( 
	SELECT 1 as num_rows
) denominator
;

ERROR: [Amazon](500310) Invalid operation: syntax error at or 
near "OFFSET"  Position: 267; Error Code: 500310 Statement Line: 
8 Editor Line (Approximate): 9 

Query = SELECT num_violated_rows, CASE WHEN denominator.num_rows 
= 0 THEN 0 ELSE 1.0*num_violated_rows/denominator.num_rows END AS 
pct_violated_rows,  denominator.num_rows as num_denominator_rows 
FROM ( select num_violated_rows from ( select case when 
COUNT(OFFSET) = 0 then 0 else 0 end as num_violated_rows from 
idival.NOTE_NLP cdmTable ) violated_rows ) violated_row_count, (  
	SELECT 1 as num_rows ) denominator ;

**Comment by ericaVoss** [comment]
@clairblacketer We hit this DQD issue on an empty NLP_NOTES table.  I thought the issue was being thrown because the table was empty but I'm wondering if there is an issue with this OFFSET.  This is for IDIVAL.

**Comment by clairblacketer** [comment]
PR #273 addresses this issue by just removing OFFSET from being checked. One of the issues has to do with the case of the column. Adding double quotes (which we do to get around the fact that it is a reserved word) evaluates the query using explicit case. SqlRender automatically makes everything upper case so this mismatch makes it think that the column offset doesn't exist
