### ISSUE TITLE
Specimen value_as_number

### ISSUE THREAD

**Issue by prunk1al** [OHDSI/DataQualityDashboard#246]
SELECT num_violated_rows, CASE WHEN denominator.num_rows = 0 THEN 0 ELSE 1.0*num_violated_rows/denominator.num_rows END  AS pct_violated_rows, 
  denominator.num_rows as num_denominator_rows
FROM
(
	SELECT COUNT(violated_rows.violating_field) AS num_violated_rows
	FROM
	(
		SELECT 'SPECIMEN.UNIT_CONCEPT_ID' AS violating_field, cdmTable.* 
		FROM idival.SPECIMEN cdmTable
		
		WHERE cdmTable.UNIT_CONCEPT_ID = 0 AND cdmTable.value_as_number IS NOT NULL
	) violated_rows
) violated_row_count,
( 
	SELECT COUNT(*) AS num_rows
	FROM idival.SPECIMEN cdmTable
	
	WHERE cdmTable.value_as_number IS NOT NULL
) denominator
;

https://github.com/OHDSI/CommonDataModel/blob/v5.3.1_fixes/Redshift/OMOP%20CDM%20redshift%20v5_3_1%20ddl.sql#L242-L258

**Comment by ericaVoss** [comment]
@clairblacketer  - which is correct here.  The RedShift DDL doesn't have a SPECIMEN.VALUE_AS_NUMBER but DQD is looking for it.

**Comment by clairblacketer** [comment]
This is related to a fix I was trying to implement for MEASUREMENT and OBSERVATION. It has since been addressed.
