### ISSUE TITLE
Connecting to the DB server only once

### ISSUE THREAD

**Issue by schuemie** [OHDSI/DataQualityDashboard#25]
Currently it seems a new connection is opened for every check. This seems inefficient, and for some DBMSs this is even impossible (Oracle will run out of its pool of random numbers). Instead of passing the connectionDetail object (internally), could a connection object be passed?

**Comment by schuemie** [comment]
Related: maybe nice to show a progress bar?

**Comment by alondhe** [comment]
@schuemie I changed this behavior, now if using 1 thread, only 1 connection object is used. 

In clusterApply when 1 thread is used, the progress bar that is usually shown in multi-threading mode is not shown. Is there a way to show it?

**Comment by schuemie** [comment]
Not right now. I've created an [issue](https://github.com/OHDSI/ParallelLogger/issues/4) for ParallelLogger, but it will be while before I can get around to it.
