### ISSUE TITLE
Functions should not have unintended side-effects

### ISSUE THREAD

**Issue by schuemie** [OHDSI/DataQualityDashboard#250]
A golden rule in R is that functions should not have unintended side-effects (which for example is strictly enforced in CRAN). DQD violates this rule in several ways:

1. [Setting a global option, and not restoring it to its original value](https://github.com/OHDSI/DataQualityDashboard/blob/master/R/execution.R#L203). I recommend using `on.exit` to ensure the value is always restored.
2. [Throwing away all previous loggers](https://github.com/OHDSI/DataQualityDashboard/blob/master/R/execution.R#L228), and also not ensuring the DQD loggers are cleaned up (e.g. in case of an error).  [Here](https://github.com/OHDSI/SkeletonComparativeEffectStudy/blob/master/R/Main.R#L100)'s an example of adding loggers and ensuring they're clean up.
3. [Calling `library` in a function](https://github.com/OHDSI/DataQualityDashboard/blob/master/R/execution.R#L286). Either use the `::` syntax when possible, or for packages like `magrittr` that introduce new syntax import it into your package like [this](https://github.com/OHDSI/CohortMethod/blob/master/R/CohortMethod.R#L35).

**Comment by schuemie** [comment]
Related to this:

4. [The output folder defaults to a folder in the current working directory](https://github.com/OHDSI/DataQualityDashboard/blob/master/R/execution.R#L170). So even when the user does not specify a folder, a folder is automatically created. Better to have no default, and throw an error when no value is specified by the user. (This is another rule that is used not only in HADES, but in CRAN also)

**Comment by clairblacketer** [comment]
Thanks @schuemie! I appreciate your review and I’ll work to get those items addressed.

**Comment by katy-sadowski** [comment]
I checked and it looks like items 2 & 4 still need to be addressed (the other 2 were resolved in the Symposium hackathon).  I'll assign this to myself to get these fixed up :)
