### ISSUE TITLE
Support for CDM v5.4

### ISSUE THREAD

**Issue by alabarga** [OHDSI/DataQualityDashboard#260]
Hi,

are you planning to support CDM v5.4? i understand that some of the changes will prevent DataQualityDashboard to run, as it happens with CDM v6.0

Alberto

**Comment by clairblacketer** [comment]
Hi @alabarga yes, we are actively in development to support CDM v5.4

**Comment by jahoon1998** [comment]
Hi @clairblacketer,

Is there an estimated release date for a new version that supports CDM v5.4? 

Thank you.
Jahoon

**Comment by clairblacketer** [comment]
Hi @jahoon1998 I am waiting on a review for my PR #273 then we will release, hopefully this week.

**Comment by clairblacketer** [comment]
the code on the main branch now supports v5.4
