### ISSUE TITLE
Add vocabulary tables to be evaluated

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/DataQualityDashboard#27]
Currently, the dq dashboard only looks at CDM tables. A future version should include the vocabulary tables as well. For example, a recent download of the vocabulary switched a columns blanks to NULLs; an issue the dq dashboard would have caught.

**Comment by clairblacketer** [comment]
I added these in v5.4, should we include a parameter that allows them to be skipped @fdefalco?

**Comment by katy-sadowski** [comment]
@clairblacketer was there further discussion on a vocab checks parameter / think this issue can be closed out now that the checks are added in v5.4?

**Comment by katy-sadowski** [comment]
Looks like this was addressed [here](https://github.com/OHDSI/DataQualityDashboard/commit/e5e7b89ae46270c13e935a3a0009d1756ae1be45) a while back so I'll close this one. We're utilizing `tablesToExclude` to skip these tables by default. I'm also going to update our docs to explicitly mention `tablesToExclude` to make sure users are aware of it!
