### ISSUE TITLE
Percent violated rows incorrectly reporting 0%

### ISSUE THREAD

**Issue by jimfrankfort** [OHDSI/DataQualityDashboard#276]
We recently noticed that 404 DQ checks having # violated rows > 0 reporting % violated rows as 0%.  
The DQD sql-query seems to be producing these 0% outputs.  In each of the incorrectly reported results, the % violated was <1.

For example, this is what was found in output.json:
"NUM_VIOLATED_ROWS":445,"PCT_VIOLATED_ROWS":0,"NUM_DENOMINATOR_ROWS":24879

And we got PCT_VIOLATED_ROWS=0 from SQL query results:
SELECT 
num_violated_rows, 
CASE WHEN denominator.num_rows = 0 THEN 0 ELSE 1.0*num_violated_rows/denominator.num_rows END  AS pct_violated_rows,
denominator.num_rows as num_denominator_rows

**Comment by don-torok** [comment]
I am not involved in making changes to DQD, but if you want, I can help you find the queries causing the problem so that you can make the correct locally until this issue is fixed.

**Comment by clairblacketer** [comment]
I believe this is an issue with how the results are report from the sql server instead of the DQD. If the sql query is returning 0 then there is something going on with the settings and how the server shows small numbers
