### ISSUE TITLE
Estimated release date for a version that supports CDM v5.4

### ISSUE THREAD

**Issue by jahoon1998** [OHDSI/DataQualityDashboard#283]
Hi,

Is there an estimated release date for a new version that supports CDM v5.4?

Thank you.
Jahoon

**Comment by clairblacketer** [comment]
Hi @jahoon1998 we are actively testing the v5.4 branch (PR #273 ) and hope to release a version with support for v5.4 this week.

**Comment by clairblacketer** [comment]
the code on the main branch now supports v5.4
