### ISSUE TITLE
Apply new thresholds without re-executing DQD

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/DataQualityDashboard#290]
Currently, you have to run the whole DQD execution again after updating the thresholds to apply them. Like this:

```mermaid
graph LR
    A[Execute DQD on CDM] --> B[Inspect Results<br>in Shiny Viewer]
    B --> C[Edit Thresholds File]
    C --> A
```

If the CDM data did not change, you can actually determine which checks fail with the new thresholds, without re-executing DQD. This will make iterations faster. (yes, I am trying out [a new feature I recently learned about](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/))

```mermaid
graph LR
    A[Execute DQD on CDM] --> B[Inspect Results<br>in Shiny Viewer]
    B --> C[Edit Thresholds File]
    C --> B
```

I see two potential ways to implement this, the first requiring less work than the second:

- **Minor change**: Create a separate method that takes an DQD output json and new thresholds file and calculates which checks pass/fail given those new thresholds.
- **Major change**:  Redesign DQD execute to output only the raw data for each check (mainly `NUM_VIOLATED_ROWS` and `NUM_DENOMINATOR_ROWS`). Then, the viewer takes this raw output AND the thresholds to determine which checks have failed. Added benefit is that we can reduce the size of the results json.

**Comment by clairblacketer** [comment]
@MaximMoinat this is a great idea, I think I might have some code to get this started. I can put it in extras for you to take a look and someone can pick it up and polish it.

**Comment by clairblacketer** [comment]
@MaximMoinat take a look at this [commit ](https://github.com/OHDSI/DataQualityDashboard/commit/701aacb54646e2ae126b131ed3aef7cf252a050e) I added two files, one that indexes multiple JSONs and shows the results across a network and one that allows for updating thresholds without rerunning the full DQD

**Comment by MaximMoinat** [comment]
That is awesome, thanks Clair. 

So the magic seems to be in the [`.evaluateThresholds` function](https://github.com/OHDSI/DataQualityDashboard/blob/edd8125ad8496fc9ba407cc7a44a473a57ac5767/R/execution.R#L456)... Will give it a try for my use case and see if we can turn this into an 'exported' function.

**Comment by clairblacketer** [comment]
closing - we added the reEvaluateThresholds function
