### ISSUE TITLE
Hard-coded call to jConnection fails on non-JDBC connections (like Eunomia)

### ISSUE THREAD

**Issue by schuemie** [OHDSI/DataQualityDashboard#30]
There is a call to the JConnection property to turn autoCommit on [here](https://github.com/OHDSI/DataQualityDashboard/blob/03d54e67cd4500302cb15bdafac0df522b5325ba/R/execution.R#L78). However, not all connection objects have this property (specifically, SQLite connections such as those used by Eunomia don't).

Is this call really necessary when just querying the data? DatabaseConnector in general knows when to turn autoCommit on and off.

If really necessary, please use 

```r
if (inherits(connection, "DatabaseConnectorJdbcConnection")) {...}
```

to only apply the code to the appropriate objects.

**Comment by alondhe** [comment]
We found it necessary for Postgres and Redshift. As we're expecting SQL errors to happen frequently, as soon as one happens, subsequent calls to querySql throw an error due to the use of the same transaction. 

Perhaps we could limit it to just those dialects?

**Comment by schuemie** [comment]
That would be good too

**Comment by clairblacketer** [comment]
To test Eunomia I removed the line and I was able to then return the results.

**Comment by alondhe** [comment]
Gotcha, adding some logic to ensure it's used for the right connection
