### ISSUE TITLE
Hemoglobin [Mass/Volume] gram / dL plausibleValueLow

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/DataQualityDashboard#307]
There is a minor inconsistency in the `plausibleValueLow` of the "Hemoglobin [Mass/volume] in Blood" (3000963). For some reason this is set to 0 for all units except "gram per deciliter", where it is 1. Without any knowledge on what the plausible hemoglobin values are, I do expect consistency across units.

Is there a specific reason why the `plausibleValueLow` for hemoglobin with unit gram per deciliter should be 1?

conceptName | unitConceptId | unitConceptName | plausibleValueLow | plausibleValueLowThreshold 
-- | -- | -- | -- | --
Hemoglobin [Mass/volume] in Blood | 8564 | picogram | 0 | 5 |   
Hemoglobin [Mass/volume] in Blood | 8576 | milligram | 0 | 5 |   
Hemoglobin [Mass/volume] in Blood | 8582 | centimeter | 0 | 5 |  
Hemoglobin [Mass/volume] in Blood | 8583 | femtoliter | 0 | 5 |   
Hemoglobin [Mass/volume] in Blood | 8587 | milliliter | 0 | 5 |   
Hemoglobin [Mass/volume] in Blood | 8636 | gram per liter | 0 | 5 |   
Hemoglobin [Mass/volume] in Blood | 8713 | gram per deciliter | 1 | 5 |   
Hemoglobin [Mass/volume] in Blood | 8739 | pound (US) | 0 | 5 |  
Hemoglobin [Mass/volume] in Blood | 8753 | millimole per liter | 0 | 5 |  
Hemoglobin [Mass/volume] in Blood | 8837 | microgram per deciliter | 0 | 5 |   
Hemoglobin [Mass/volume] in Blood | 9245 | per deciliter | 0 | 5 |   
Hemoglobin [Mass/volume] in Blood | 9373 | ounce (avoirdupois) | 0 | 5 |   

https://github.com/OHDSI/DataQualityDashboard/blob/edd8125ad8496fc9ba407cc7a44a473a57ac5767/inst/csv/OMOP_CDMv5.4_Concept_Level.csv#L346-L347

**Comment by clairblacketer** [comment]
@MaximMoinat I agree that values should agree across units. I added the "No Coding" label as I think this could be a good issue for someone from DevCon to tackle

**Comment by clairblacketer** [comment]
I am closing this as we implemented new measurement checks looking for plausible units and we removed the plausible value checks.
