### ISSUE TITLE
Errors during running checks for cohort table

### ISSUE THREAD

**Issue by ssuvorov-fls** [OHDSI/DataQualityDashboard#308]
I'm getting several errors while running quality checks because "cohort" table does not exist in cdm schema. As far as I know this table is in result schema.
Are these quality checks correct?

**Comment by clairblacketer** [comment]
Hi @ssuvorov-fls which cdm version are you running?

**Comment by ssuvorov-fls** [comment]
@clairblacketer 5.4

**Comment by clairblacketer** [comment]
@ssuvorov-fls in CDM v5.4 the ddl generated from the CommonDataModel package has the cohort table in the CDM schema. If you have chosen to put it in a different schema you can the tablesToExclude option in the executeDqChecks() function.
