### ISSUE TITLE
fkDomain denominator rows over non-zero concepts.

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/DataQualityDashboard#309]
I came across the following:
All mapped concepts in the visit occurrence table were from the wrong domain. However, the DQD reported only 40% of rows violated the check. It turned out the other 60% were rows with unmapped standared concept (mapped to 0). I would expect in this case that the fkDomain check would report 100% of concepts in the wrong domain.

Proposal:
Also filter denominator to non-zero conceps (`WHERE co.concept_id != 0`) here:
https://github.com/OHDSI/DataQualityDashboard/blob/edd8125ad8496fc9ba407cc7a44a473a57ac5767/inst/sql/sql_server/field_fk_domain.sql#L39-L47

There might be other checks where the same holds true.

**Comment by MaximMoinat** [comment]
Sorry, I did not explain correctly. 
What I meant was that the %violated should be calculated from the records with a non-zero concept.

**Comment by clairblacketer** [comment]
@MaximMoinat ok that makes more sense. I agree with that assessment
