### ISSUE TITLE
Add Death checks for 5.3.1 and 5.2.2

### ISSUE THREAD

**Issue by MelaniePhilofsky** [OHDSI/DataQualityDashboard#312]
Colorado is on DQD v1.3.1, so this might already be available in v1.4 of the DQD. 

Add a check for duplicate Death.death_id
Add a check for duplicate Death.person_id
Add a check for Person.person_id and Death.person_id PK-FK integrity check
Add a check for Death.death_date > Person.year_of_birth, Person.month_of_birth, Person.day_of_birth
Add a check for Death.death_datetime > Person.birth_datetime

**Comment by MelaniePhilofsky** [comment]
Thank you, Maxim, for your response.

**Comment by MaximMoinat** [comment]
I just realised that the death table is completely missing from the [v5.3.1](https://github.com/OHDSI/DataQualityDashboard/blob/main/inst/csv/OMOP_CDMv5.3.1_Field_Level.csv) and [v5.2.2](https://github.com/OHDSI/DataQualityDashboard/blob/main/inst/csv/OMOP_CDMv5.2.2_Field_Level.csv) Table AND Field level threshold files. On these CDM versions, no checks are executed against the death table.

So reopening the issue, we need to fix this.

**Comment by katy-sadowski** [comment]
Added these checks in the v2.2.0 release.
