### ISSUE TITLE
Payer Plan Period bug in SQL

### ISSUE THREAD

**Issue by MelaniePhilofsky** [OHDSI/DataQualityDashboard#315]
Colorado is on DQD v1.3.1, so this might have been fixed in v1.4 of the DQD.

This check should compare the cdmtable.person_id and fktable.person_id

SQL Query: | /********* IS_FOREIGN_KEY Foreign key check  
Parameters used in this template: 
cdmDatabaseSchema = omop_uchealth  
cdmTableName = PAYER_PLAN_PERIOD 
**cdmFieldName = PAYER_PLAN_PERIOD_ID** 
fkTableName = PERSON 
**fkFieldName = PERSON_ID** 

 **********/   
select num_violated_rows, case when denominator.num_rows = 0 then 0 else 1.0*num_violated_rows/denominator.num_rows end  as pct_violated_rows,    denominator.num_rows as num_denominator_rows 
from ( 	
select COUNT(violated_rows.violating_field) as num_violated_rows 	
from 	
( 		
select 'PAYER_PLAN_PERIOD.PAYER_PLAN_PERIOD_ID' as violating_field, cdmtable.*  		
from omop_uchealth.payer_plan_period cdmtable 		 		
left join omop_uchealth.person fktable 		
**on cdmtable.payer_plan_period_id = fktable.person_id** 		
where fktable.person_id is null 
and cdmtable.payer_plan_period_id is not null  	
) violated_rows ) violated_row_count, 
(  	
select COUNT(*) as num_rows 	
from omop_uchealth.payer_plan_period cdmtable 	 
) denominator ;
-- | --

**Comment by MaximMoinat** [comment]
This has indeed been fixed in the latest code:
https://github.com/OHDSI/DataQualityDashboard/commit/377cd17b0ae9c523cc7654ed02a0990a87f90364
```
Fix foreign key check
removed PAYER_PLAN_PERIOD_ID  foreign key check to PERSON_ID
```
