### ISSUE TITLE
Plausible values for lab tests in DQD

### ISSUE THREAD

**Issue by tajanenp** [OHDSI/DataQualityDashboard#317]
Dears, we found a few cases where the plausibleLow and plausibleHigh values seem to be incorrectly set in DqD and already had a discussion about those with Claire at the forums :)
I updated the values for us with a very simple method, by selecting the lowest and highest values (that seem reasonable and not erroneous/typos)  from our data. Now that I am preparing to report these changes back to you, I realize that my method was probably far too simplified!
So my question is, what exactly do you mean by "plausible values" ? I know that some experts have provided you with those, but can you tell me how they are/should be calculated so I would be able to re-calculate them for these 5-6 concepts that don't seem to make sense compared to the data and the tests' reference ranges. Many Thanks already!
Pia

**Comment by tajanenp** [comment]
Dears,

after discussing with different parties here in Turku, we came to an understanding that plausible values
could indeed be interpreted simply as values that are humanly/physiologically plausible :) At this point
we consider our data sufficiently reliable to be used as a basis for the calculations of these values.
It is to be noted that our data is from a university hospital providing the most specialized care, and the subjects
are often seriously affected by different illnesses. Therefore we have many extreme values, but still these values
are real, so plausible ;)
Here's our proposition for plausible low and high values for the few  measurement_concept_id/unit_concept_id -pairs, we
found suspicious in the DqD. To determine the cutoffs we chose to leave out 4% of the most extreme values from both ends. 

`select m.measurement_concept_id,
 c.concept_name,
 m.unit_concept_id,
 m.unit_source_value,
 percentile_disc(0.04) within group (order by value_as_number) as plausible_Low_Value,
 percentile_disc(0.96) within group (order by value_as_number) as Plausible_High_Value
from common_data_model.measurement m
join common_data_model.concept c on m.measurement_concept_id=c.concept_id
where m.measurement_concept_id in (3000620,3003458,3024561,3022756,3017766,3015377) and m.unit_concept_id !=0
group by m.measurement_concept_id, c.concept_name, m.unit_concept_id, m.unit_source_value
order by m.measurement_concept_id, m.unit_concept_id
;
/*
|measurement_concept_id|concept_name                                  |unit_concept_id|unit_source_value|plausible_low_value|plausible_high_value|
|----------------------|----------------------------------------------|---------------|-----------------|-------------------|--------------------|
|3,000,620             |Complement C3 [Mass/volume] in Serum or Plasma|8,636          |g/l              |0.59               |1.6                 |
|3,003,458             |Phosphate [Moles/volume] in Serum or Plasma   |8,753          |mmol/l           |0.65               |2.15                |
|3,015,377             |Calcium [Moles/volume] in Serum or Plasma     |8,753          |mmol/l           |1.97               |2.6                 |
|3,017,766             |Complement C4 [Mass/volume] in Serum or Plasma|8,636          |g/l              |0.06               |0.35                |
|3,022,756             |Ceruloplasmin [Mass/volume] in Serum or Plasma|8,636          |g/l              |0.17               |0.44                |
|3,024,561             |Albumin [Mass/volume] in Serum or Plasma      |8,636          |g/l              |17.4               |43.1                |
`

What do you think, would this be acceptable?
Many Thanks for your comments already!
Pia

**Comment by tajanenp** [comment]
Any update on this, anyone care to comment? :) Thanks already!

**Comment by tajanenp** [comment]
close by mistake, the issue is still open!

**Comment by MaximMoinat** [comment]
Thanks @tajanenp for opening this issue, sorry for our late response. 
The value ranges are also being investigated by @dimshitc. We hope to implement your and his findings in an upcoming DQD release.

**Comment by clairblacketer** [comment]
I am closing this as we implemented new measurement checks looking for plausible units and we removed the plausible value checks. Feel free to keep using them if your values are useful for you.

**Comment by tajanenp** [comment]
me again, I forgot to ask whether this change is already “in production” we’ll soon need to run the DQD again related to the EU Darwin
Thanks again!
Pia

**Comment by tajanenp** [comment]
had forgotten to click SEND on this ?!

Hi Claire and thanks for letting me know, this sounds like good news ☺
Kind Regards,
Pia
