### ISSUE TITLE
Document naming convention for user defined csv files.

### ISSUE THREAD

**Issue by don-torok** [OHDSI/DataQualityDashboard#321]
If a user wants to maintain there own set of CSV files explain that they need all 4 CSV files and how to name file and set cdmVersion variable so that their files are used.
"OMOP_CDMv%s_Check_Descriptions.csv", cdmVersion

**Comment by clairblacketer** [comment]
@don-torok the user only needs the three (field, concept, and table) check files. The check description file stays static and is pulled from the package files on the user's machine.

**Comment by clairblacketer** [comment]
A user doesn't need to follow a certain naming convention, they can use the location options (`fieldCheckThresholdLoc`, etc) to use their own files.
