### ISSUE TITLE
Foreign Key check return failed for table with no rows

### ISSUE THREAD

**Issue by don-torok** [OHDSI/DataQualityDashboard#322]
My visit_detail table is empty, but all potential foreign key columns are failing isForeignKey test.  Does not make sense that nothing is an invalid foreign key.

**Comment by clairblacketer** [comment]
@don-torok I have seen this before but I thought we put in a fix for it. Can you share one of the qualified SQL statements that is failing?

**Comment by don-torok** [comment]
@clairblacketer My mistake. The visit_detail was not empty, but in fact did not exist. So I am not sure what DQD will report if the table exists and is empty.  The reason for the failure was a SQL error because the table/column did not exist.  Close this issue.

**Comment by clairblacketer** [comment]
@don-torok that makes sense. Dmitry's updates for v2 will make it so that if a table is empty or does not exist, those checks will not be run
