### ISSUE TITLE
Make Notes field in DQD customizable

### ISSUE THREAD

**Issue by MelaniePhilofsky** [OHDSI/DataQualityDashboard#328]
It would be nice if the Notes field was customizable. Currently, the only option is for "Exists". If it was customizable, we would be able to add additional information inline with the failure. "known bug", "fix in progress", or any other information would be helpful for the analyst reviewing the results.

**Comment by clairblacketer** [comment]
Hi @MelaniePhilofsky the notes are customizable - the only downside is that you have to put the note into the control file in the correct cell for the table, field, and check you are writing about.

**Comment by MaximMoinat** [comment]
Linking in a draft PR #253, which The Hyve developed that might make managing the notes easier. To be refined before merging, but any input is very welcome @MelaniePhilofsky!
