### ISSUE TITLE
`tablesToExclude` disables checks on fields in non-excluded tables

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/DataQualityDashboard#342]
# Expected behaviour
When specifying `tablesToExclude`, only the checks on the specified tables are disabled.

# Observed behaviour
When specifying `tablesToExclude`, it also disables checks on fields with a foreign key relation to the excluded tables.
For example, when excluding the 'provider' table, this also disables the type and foreign checks on all `provider_id` fields in other tables. It might be debatable what is expected in this case.

However, if someone decides to add the 'concept' table to `tablesToExclude`, then the checks on ALL the `*_concept_id` fields are disabled. You could say this is a user error (as there are no checks on vocabulary tables), but there is nothing preventing a user making this simple mistake. And it leads to very confusing results where seemingly random checks are not run.

# Cause
The following code removes all checks for fields with a foreign key to any excluded tables.
https://github.com/OHDSI/DataQualityDashboard/blob/8059b9bffe4e1f424d6dd49b5293c6023acb034a/R/execution.R#L279-L283

# Suggestions
1. Discuss whether or not we want to disable checks on fields with a foreign key relation to excluded tables.
   * If we keep this, then we should document this behaviour of the `tablesToExclude` argument. 
2. Prevent users from excluding vocabulary tables, or warn if they do. e.g. check `tablesToExclude` against `tableChecks$cdmTableName`

**Comment by ablack3** [comment]
I'm not sure if this is related or not. I'm trying to run one field check on just the observation_period table and getting an NA result. 

``` r
library(Eunomia)
library(DataQualityDashboard)
library(dplyr)

checks <- DataQualityDashboard::listDqChecks() 

tablesToInclude <- "OBSERVATION_PERIOD"
tablesToExclude <- dplyr::setdiff(checks$tableChecks$cdmTableName, tablesToInclude)

result <- executeDqChecks(cd, 
                          cdmDatabaseSchema = "main",
                          resultsDatabaseSchema = "main",
                          cdmSourceName = "Eunomia",
                          checkNames = "isRequired", 
                          # cohortDefinitionId = 2,
                          tablesToExclude = tablesToExclude)

tibble(result$CheckResults) %>%
  select(CDM_FIELD_NAME, NUM_VIOLATED_ROWS)
#> # A tibble: 3 × 2
#>   CDM_FIELD_NAME              NUM_VIOLATED_ROWS
#>   <chr>                       <lgl>            
#> 1 OBSERVATION_PERIOD_ID       NA               
#> 2 OBSERVATION_PERIOD_END_DATE NA               
#> 3 PERIOD_TYPE_CONCEPT_ID      NA
```

<sup>Created on 2022-07-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by clairblacketer** [comment]
Agreed @MaximMoinat this is confusing and difficult to explain to an end user. We should remove the lines 

https://github.com/OHDSI/DataQualityDashboard/blob/8059b9bffe4e1f424d6dd49b5293c6023acb034a/R/execution.R#L281-282

this would effectively make it so that just the table itself is excluded from execution but the foreign key and other checks that relate to that excluded table are still included. 

This is also related to #139
