### ISSUE TITLE
DQD Tool Installation

### ISSUE THREAD

**Issue by ranatech08** [OHDSI/DataQualityDashboard#344]
### Discussed in https://github.com/OHDSI/DataQualityDashboard/discussions/343

<div type='discussions-op-text'>

<sup>Originally posted by **ranatech08** July 27, 2022</sup>
Hi,

I am new to R and also to your DQD tool.

Can I have the link for complete documentation of DQD setup? I don't seem to find it here in the repo. 
For instance, I see the script: codeToRun.R under extras, wherein I "think" the DB details need to be inserted. Please confirm?

If yes, then I need to change the libpath for the install_github() for me to trace that script file and make the required changes. Will be great if instruction like these be documented with the users for easier setup and utilization. 

And if not, then which file do I need to make the changes. Overall, a general documentation for DQD setup is required, which would be really great!!!

Alternatively, a YouTube video on this will be fabulous. 

Thanks,
Rana</div>

**Comment by don-torok** [comment]
The forums are a better place to ask questions. None the less, there should be an git enhancement issue to add installation instructions or a link to them in the Readme. [Installation instructions](https://ohdsi.github.io/DataQualityDashboard/articles/DataQualityDashboard.html). I suggest you google "OHDSI data quality dashboard" for additional information.

**Comment by ranatech08** [comment]
> The forums are a better place to ask questions. None the less, there should be an git enhancement issue to add installation instructions or a link to them in the Readme. [Installation instructions](https://ohdsi.github.io/DataQualityDashboard/articles/DataQualityDashboard.html). I suggest you google "OHDSI data quality dashboard" for additional information.

Thanks @don-torok, will pose my doubts and questions in the forum. Hope to get necessary assistance :)

**Comment by don-torok** [comment]
There is nothing in the readme page that refers to how to install DQD.

**Comment by ranatech08** [comment]
Thanks for keeping this thread alive till its done. Appreciate it :)
