### ISSUE TITLE
DQD tool :: viewDqDashboard command requires Internet connectivity

### ISSUE THREAD

**Issue by ranatech08** [OHDSI/DataQualityDashboard#349]
Hi, 

Please refer to the OHDSI forum [link](https://forums.ohdsi.org/t/results-tab-in-data-quality-dashboard-has-nothing-to-display/17115) for the issue in detail.

We request to have the DQD tool as **one complete repo package** which, when deployed in any environment **Not** having internet, can still function.

The below screenshot shows error in calling some of the JS files over the internet when we ran the `viewDqDashboard` command ("Results" tab not showing up due to the missing JS files). As per my company policy, the DQD tool and other tools are meant to be deployed and run in AWS WorkSpace instance....a box created without internet. Hence, if this tool comes as an independant package repo then I am sure this issue would be resolved and could be used by companies having the same approach (meaning, non internet environment).

![image](https://user-images.githubusercontent.com/34309448/185057955-ca591733-bba4-40b1-884c-4c7351421ee2.png)

Please note that in the forum [link](https://forums.ohdsi.org/t/results-tab-in-data-quality-dashboard-has-nothing-to-display/17115), I have mentioned 2 work arounds but however in the 2nd workaround when implemented, it does show the "Results" section but with some glitch coming via JS function. 

Please let me know if any additional information required from my end.

Thanks,
Rana

**Comment by clairblacketer** [comment]
Thanks for bringing this up, PR #331 was just pulled into the develop branch to address this
