### ISSUE TITLE
Add DataQualityDashboard to Hades

### ISSUE THREAD

**Issue by ablack3** [OHDSI/DataQualityDashboard#351]
This is an issue for the 2022 Hades Hack-a-thon.

Hades requirements: https://ohdsi.github.io/Hades/packageRequirements.html

<detailed tasks to be added to this issue>

**Comment by katy-sadowski** [comment]
https://docs.google.com/spreadsheets/d/1UnGJkLgpq52d6Q9LYiBAxUhCZBKkQiBiqKFisFZWi-c/edit?usp=sharing

**Comment by anthonysena** [comment]
[HADES Hack-a-thon]: Katy is going to work on this item.

**Comment by alondhe** [comment]
Most tasks are complete. Last item for the Sunday session: unit tests.

**Comment by schuemie** [comment]
Is DQD ready for review for inclusion in HADES?

**Comment by katy-sadowski** [comment]
PR #398 contains the final changes needed to meet the Hades requirements.  Once it's merged into main we should be good to go!  I can comment back here when that's the case.

**Comment by schuemie** [comment]
Just checking in if you need any help getting this over the finish line.

**Comment by katy-sadowski** [comment]
Thanks for checking in & apologies for the delay @schuemie.  Snakecase-->Camelcase change should be finalized and ready for review in the above PR this week - I'll tag you on that so you can follow along.  While that's being reviewed I'll work on the other items.

**Comment by katy-sadowski** [comment]
Hi @schuemie !  As an FYI, here is the PR with the snakecase --> camelcase conversion: https://github.com/OHDSI/DataQualityDashboard/pull/409.  The other changes in the PR are some bug fixes I'm going to include in the next release along with the Hades requirements.  I will now work on the remaining Hades reqs and put up some more PRs for those in the coming week.  Thanks for your patience 🐫

**Comment by katy-sadowski** [comment]
Hi again @schuemie 👋 I could use your advice on 2 of the R CMD Check notes.  The package is way over the max size (which I believe is 5 Mb), and some of the filenames are too long (ex. `storing paths of more than 100 bytes is not portable: ‘DataQualityDashboard/inst/shinyApps/www/vendor/googlefonts/sairaextracondensed_v11_-nFvOHYr-vcC7h8MklGBkrvmUG9rbpkisrTrU23h2wpk.ttf’`).  The main offender in both cases is the `vendor` folder for the shiny app: https://github.com/OHDSI/DataQualityDashboard/tree/main/inst/shinyApps/www/vendor

I was wondering if you have recommendations for if/how I might be able to resolve these issues?  I'm quite unfamiliar with web development so I'm not really sure where to start in terms of my options for better handling of these 3rd party files.  For the filenames, I think I see how I might be able to shorten the names and corresponding refs to them in the code, but I'm not sure if that's allowable given much of this code seems auto-generated / sourced externally.  For the size of the folder, curious if there are any best practices for sourcing this code separately vs storing in the package itself?

Thanks!

**Comment by schuemie** [comment]
Hi @katy-sadowski!

The 5mb size limit is for packages that will go to CRAN. We don't really care about size for HADES. (And I don't think DQD needs to be in CRAN right now). But still, preserving space is not a bad idea. If we did want to reduce it, then a big file is the [default JSON file](https://github.com/OHDSI/DataQualityDashboard/blob/main/inst/shinyApps/www/results_default.json), which I guess doesn't need to be that big. And then there are all the CSV files in [inst/csv](https://github.com/OHDSI/DataQualityDashboard/tree/main/inst/csv) that would be a lot smaller if they were saved as RDS (compressed R data files) instead. But if the size stays as it is that is fine by me too.

The 100 character path limit does seem to be a real thing. Apparently tar balls can't handle more, and tar balls are the way we share R packages. I'm not much of a web developer, but do these 3rd-party libraries need to be in this package? Aren't bootstrap, jquery, etc. readily available for referencing on the internet? Alternatively, perhaps we could zip the entire shiny app, and deploy it on demand. The [CohortExplorer](https://github.com/OHDSI/CohortExplorer) also deploys shiny apps on demand (although not using zip files), which actually seems to fit most user's workflow better.

**Comment by katy-sadowski** [comment]
Thanks so much for the input @schuemie !  For the package size, I think I will defer this work to a future release so it doesn't hold up the HADES submission.  I'll file an issue so we can properly scope out the work and determine the best way to slim down some of these directories.

For the filepaths, I will check with some others on the DQD team to see if they think there'd be any problem with me modifying the paths and refs to them in the code as a short term fix.  It seems the switch to include these 3rd party libraries in the package was done deliberately to enable fully offline use of the DQD app ([issue](https://github.com/OHDSI/DataQualityDashboard/issues/349) / [PR](https://github.com/OHDSI/DataQualityDashboard/pull/331)) so I think we will probably want to keep these files around - we'll just need to find a way to reduce the size eventually (I like your suggestion).

**Comment by schuemie** [comment]
Great work @katy-sadowski ! I just pushed some minor changes to the develop branch. 

Note that in the [DESCRIPTION file](https://github.com/OHDSI/DataQualityDashboard/blob/main/DESCRIPTION#L6-L14) you were listed as 'Maintainer', but you were not in the list of authors. DESCRIPTION files are weird in that the 'Maintainer' field and the 'cre' (creator) role are considered the same, and for example `pkgdown` is reading the 'cre' role, meaning you're not listed on the [website](https://ohdsi.github.io/DataQualityDashboard/index.html) at all! I removed the 'cre' role from Clair, and add you as author, with the 'cre' role.

If you could create a new release (don't forget to [update the manual and website](https://github.com/OHDSI/DataQualityDashboard/blob/main/extras/PackageMaintenance.R#L27-L75)!), we can add DQD to HADES.

**Comment by katy-sadowski** [comment]
Thank you @schuemie !  Release is all set to go; I tagged you on the PR if you'd like to give that a quick thumbs up :)

**Comment by clairblacketer** [comment]
Great job @katy-sadowski ! Thank you for pushing this forward!

**Comment by katy-sadowski** [comment]
OK woohoo, 2.1.1 is released!  Thanks so much both for your help getting this done.  @schuemie let me know if there are any next steps on the HADES side.
