### ISSUE TITLE
Fail test when threshold and results both = 0%

### ISSUE THREAD

**Issue by sarahgbmc** [OHDSI/DataQualityDashboard#366]
Several tests have a status of "Fail" despite the threshold and results % both being 0%. 

<img width="741" alt="Capture" src="https://user-images.githubusercontent.com/103575490/192271850-da2ecc40-b3ad-4968-a0c1-d4b1445c2809.PNG">

**Comment by MaximMoinat** [comment]
A few things that could be happening:

- For the visit occurrence (0.00%), there are likely just a few violating records. By looking at the check details (clicking on the +), you can see how many are violating. With the threshold being 0%, any violating record will result in the check failing.
- For revenue_code_source_value, you likely don't have this column. In older cdm versions, this column was misspelled.
- For the location and person fails, something else might be happening. Please explore the check details.

Hope this helps!

**Comment by clairblacketer** [comment]
@sarahgbmc I agree with @MaximMoinat here, there are likely a few rows failing that aren't showing up in the overview.

**Comment by sarahgbmc** [comment]
Apologies! The reply notifications for this were sent to my spam inbox!

Yes, that makes sense. I exported the counts and there are some rows failing. Thanks so much for your help!
