### ISSUE TITLE
Function to generate result json from results in database

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/DataQualityDashboard#367]
At the moment I don't think there is any easy way to generate the result json from the results saved in the database. I was in this situation with someone else having run DQD and so I can see the results in the database but could not see a way to get the json results without having to rerun the analysis. That was until @MaximMoinat shared some bespoke code that meant I could do this. It would I think be helpful to make this a function of the package if possible.

**Comment by katy-sadowski** [comment]
Hey @edward-burn - that code you mention has now been added in a vignette [here](https://ohdsi.github.io/DataQualityDashboard/articles/SqlOnly.html#optional-execute-queries) (see code starting at `# Get results`)

**Comment by jshoughtaling** [comment]
Hey @edward-burn and @katy-sadowski - I opened PR #497 yesterday that addresses this issue and adds a public function + tests in line with the vignette linked above.

**Comment by katy-sadowski** [comment]
This is added in v2.5! Thanks @jshoughtaling !
