### ISSUE TITLE
Events After Death

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/DataQualityDashboard#38]
This is more of a question than an issue, but looking at Themis Issue [42](https://github.com/OHDSI/Themis/issues/42), the proposal is to accept events within 60 days post death. Will this be incorporated into PLAUSIBLE_DURING_LIFE mentioned in [this](https://github.com/OHDSI/DataQualityDashboard/issues/6) issue for the DQDashboard? I'm happy to make a PR but wanted to see if it was by design to flag all events after death. 
By the way, the dashboard is awesome!!!

**Comment by AnthonyMolinaro** [comment]
@cukarthik  The query has been modified so that a violation (an event after death) is one that occurs at least 61 days after death.
