### ISSUE TITLE
Better error handling for bad argument of `cdmVersion`

### ISSUE THREAD

**Issue by adwasser** [OHDSI/DataQualityDashboard#399]
When passing in a bad argument for `cdmVersion` in `executeDqChecks` (for example, an overly specific "5.4.0"), we have a cryptic (to the user) error about not being able to load a file, as shown below.

```
Error in read.table(file = file, header = header, sep = sep, quote = quote,  :
  no lines available in input
In addition: Warning message:
In file(file, "rt") :
  file("") only supports open = "w+" and open = "w+b": using the former
```

It looks like this comes from something like loading the threadhold CSVs here:

https://github.com/OHDSI/DataQualityDashboard/blob/main/R/executeDqChecks.R#L164

but I'm not positive.

While the allowed values are documented in the docstring for the function, there's no error handling that could help the user figure out what to do to fix this.

**Comment by katy-sadowski** [comment]
Fix has been released. Thanks for reporting @adwasser !
