### ISSUE TITLE
Issue with running DQD on a cohort - cohort table name as a parameter

### ISSUE THREAD

**Issue by daniellenewby** [OHDSI/DataQualityDashboard#400]
Hi,

I am trying to run the DQD on a cohort however I am unable to select the cohort I want to run the DQD on because the table name for COHORT is hardcoded into the code (see below). Could there be an option to define the COHORT table name you want to run the DQD as a parameter?

Thanks
Danielle

https://github.com/OHDSI/DataQualityDashboard/blob/3425ba428ecfc0fd09f1324b11ac4cf35849524b/inst/sql/sql_server/table_condition_era_completeness.sql#L27

**Comment by don-torok** [comment]
A cohort is a list of person_ids. The COHORT table is designed to hold one or more patient cohorts, each identified by the cohort_definition_id. And DQD provides and argument for the cohortDefinitionId. What is different about your cohorts that they require a separate table?

**Comment by daniellenewby** [comment]
Hi Don, 
Thanks for the quick response. My understanding is this would be the case for cohort that have been derived using ATLAS where you are right you could identify the cohort using cohortDefinitionId but for those that are not instantiated via ATLAS this creates a different table in the results schema. So i was wondering if there could be a option to set the COHORT table name - the COHORT could still be the default but the flexibility to select a different table name would be useful.

**Comment by katy-sadowski** [comment]
Hi @daniellenewby are you referring to a cohort table instantiated by another OHDSI tool, or something custom to your institution?

Since COHORT is a CDM standard table I'm not sure we want to flex naming for that.  You do have the option to specify a `cohortDatabaseSchema`, so perhaps that could help you work around using the ATLAS cohort table?

**Comment by daniellenewby** [comment]
Hey @katy-sadowski - yes i don't want to instantiate a cohort using ATLAS we are using other packages (cohort generator) which do not instantiate to the COHORT table but to our results schema. Just having an argument with the default being COHORT but the flexibility to change where the table i want to do the DQD would be helpful. I will have a look at the cohortDatabaseSchema so thanks for flagging this :) have a good day!

**Comment by katy-sadowski** [comment]
Aha, I do see that in CohortGenerator there is the option to specify your own cohort table name.  For consistency & compatibility across OHDSI tools, now I'm thinking this might be something we'd want to support in DQD (and as you mention, we could keep `cohort` as the default value).  Let me run this by the team and get back to you.  Thanks!

**Comment by daniellenewby** [comment]
Thanks @katy-sadowski :)

**Comment by clairblacketer** [comment]
@katy-sadowski and @daniellenewby this makes a lot of sense to me, should be an easy change :)

**Comment by daniellenewby** [comment]
Hey, @katy-sadowski hope you are ok! -sorry to pester but I was wondering if there had been any progress on this enhancement for DQD. If you have any rough timelines that would be really helpful when you think it might be updated - thank you so much! :)

**Comment by katy-sadowski** [comment]
Hi @daniellenewby no worries, thanks for checking in!  I'm planning to ship v2.1 in early February and this change will be included.  I'll keep you posted if anything changes!

**Comment by katy-sadowski** [comment]
@daniellenewby thanks for your patience. some other issues arose that took precedence over this change but I've just put up a PR to add a cohort table name parameter to DQD: #421 (and @clairblacketer i tagged you to review - as you guessed, it was a simple change 😄 ).  i'll keep you posted on the release!

**Comment by daniellenewby** [comment]
Hey @katy-sadowski hope you are ok! just checking has this change been updated in the new version of DQD?

**Comment by katy-sadowski** [comment]
Thanks for checking in @daniellenewby and I apologize again for the delay!  I am waiting on approval for one last PR in the upcoming release and then this will finally be shipped.  Should be out this week or next; I will comment back here when it's released.

**Comment by daniellenewby** [comment]
No worries sorry for pestering!! Thanks for your work on this!

**Comment by katy-sadowski** [comment]
@daniellenewby at long last, the release with this update is now available!  If you update your DQD package you'll now be able to specify a `cohortTableName`. Please let us know if you experience any issues with the new feature.

**Comment by daniellenewby** [comment]
@katy-sadowski amazing! thank you so much! I am away this week but I will test it next week and will let you know if i have any troubles! Thanks again for getting this done - much appreciated!
