### ISSUE TITLE
Potential issues with DQD v2.0: cmdVersion and writeToCsv are unused arguments

### ISSUE THREAD

**Issue by krevett-iqvia** [OHDSI/DataQualityDashboard#405]
We are testing the v2.0 of the dqd pkg - and we are running into an error:

"error in DQD::executeDqChecks(...):
error output is: unused arguments (writeToCsv = TRUE,  cmdVersion  = cmdVersion )"

Has anyone else come across this response?

**Comment by katy-sadowski** [comment]
Hi there!  Could you please share the full command you ran that generated the error?  For the second arg there it looks like you have a typo - should be `cdmVersion`.  Thanks!

**Comment by katy-sadowski** [comment]
Hi @krevett-iqvia are you still experiencing any issues, or may I close this out? Thanks :)

**Comment by katy-sadowski** [comment]
@krevett-iqvia i'm going to go ahead and close this issue, but please do let me know if you are still experiencing any issue with the executeDqChecks args.
