### ISSUE TITLE
potential removal of time unit from execution duration output

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/DataQualityDashboard#407]
Currently the elapsed time is calculated and the result has the text string "secs" appended to the the execution time.  In downstream applications (DQD / ARES) the soft of this column occurs as a string sort because of the "secs" on the execution result.

Could we remove this from the output and leave only the numeric value?

https://github.com/OHDSI/DataQualityDashboard/blob/6c9c8fedb5a545dda6c34112acef40decda1fc5e/R/processCheck.R#L66

**Comment by katy-sadowski** [comment]
mm, interesting - agree that field isn't super useful as a string.  maybe we could make the `executionTime` --> `executionTimeSeconds` and store as a number.  then in the DQD UI where execution time is displayed, we could change the label to Execution Time (Seconds).
