### ISSUE TITLE
measurement/unit check wrong percentage of failed records 

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/DataQualityDashboard#415]
Denominator is calculated as number of measurements with units, while it should be calculated as number of units with value.
Missing unit is still a valid case, so it should be treated the same way as measurement with unit.

On the other hand we can consider adding check for measurements without numerical values. We already have a list of measurements that require numerical results

**Comment by katy-sadowski** [comment]
To confirm - you are talking about [this](https://github.com/OHDSI/DataQualityDashboard/blob/main/inst/sql/sql_server/concept_plausible_unit_concept_ids.sql) check? 

And do you think that the SQL is wrong given the description of the check?  Or that the check itself should be changed?

**Comment by katy-sadowski** [comment]
I think I realize what you're saying - denominator here [https://github.com/OHDSI/DataQualityDashboard/blob/162e709b4207c8ad31ca326237ae27ead9c07aa4/inst/sql/sql_server/concept_plausible_unit_concept_ids.sql#L63](url) only includes measurements with a unit source value.  However, violated rows [here](https://github.com/OHDSI/DataQualityDashboard/blob/162e709b4207c8ad31ca326237ae27ead9c07aa4/inst/sql/sql_server/concept_plausible_unit_concept_ids.sql#L42-L43) wants unit to be missing if there are no plausible unit concept IDs.

I think another issue here is that in both numerator and denominator, we require a numeric value; however, many measurements w/o units are going to be the non-numeric ones, so those aren't getting checked at all here.  Also agree with you we might want to add a check for numeric vs non-numeric measurements!
