### ISSUE TITLE
User Documentation section is pointing to a link which does not have example how to use this library

### ISSUE THREAD

**Issue by lav-patel** [OHDSI/DataQualityDashboard#419]
User Documentation section is pointing to a [link](https://ohdsi.github.io/DataQualityDashboard/index.html) which does not have example how to use this library.

Can you please example how to use this library?

**Comment by katy-sadowski** [comment]
Installation and setup instructions can be found here on the Get Started page of the linked package website: https://ohdsi.github.io/DataQualityDashboard/articles/DataQualityDashboard.html

**Comment by katy-sadowski** [comment]
@lav-patel i'm going to close this issue for now but do let me know if you require further assistance.
