### ISSUE TITLE
left menu resize issues

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/DataQualityDashboard#42]
latest change to add the data source name has introduced some resize issues with the left menu

![image](https://user-images.githubusercontent.com/6586384/64352476-1ab62980-cfca-11e9-8127-ce84e15d324c.png)

**Comment by clairblacketer** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/dcbaa397-a792-45fa-8af9-8c55a26b5724-f49472f3-e6bb-47f8-9555-447f437f5a31-v1.png?transparent=1&palette=1&width=246)

We can forget this - since the name is already under the word 'Results'

**Comment by fdefalco** [comment]
I'll fix. :)
