### ISSUE TITLE
Unit 9117 is non-standard, the unit tests with that concept need to be updated

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/DataQualityDashboard#420]
This is Juan Manuel Ramírez-Anguita from PSMAR Barcelona. We are working with the DQD v2.0.0  and I think we have detected at least two  "plausibleUnitConceptIds" tests which need to be updated:

Description: The number and percent of records for a given CONCEPT_ID 40764999 (GLOMERULAR FILTRATION RATE/1.73 SQ M.PREDICTED [VOLUME RATE/AREA] IN SERUM, PLASMA OR BLOOD BY CREATININE-BASED FORMULA (CKD-EPI)) with implausible units (i.e., UNIT_CONCEPT_ID NOT IN (9117)). (Threshold=5%).
Notes: Approved UNIT_CONCEPT_IDs for the given MEASUREMENT_CONCEPT_ID
Level: CONCEPT
Table: MEASUREMENT
Field: MEASUREMENT_CONCEPT_ID
Concept Id: 40764999

The unit_concept_id = 9117 (milliliter per minute per 1.73 square meter) is currently a non-standard concept which has recently been replaced with 720870 (milliliter per minute per 1.73 square meter). Then, the test should replace this concept as well in the next DQD release.

measurement_concept_id 46236952 [Glomerular filtration rate/1.73 sq M.predicted [Volume Rate/Area] in Serum, Plasma or Blood by Creatinine-based formula (MDRD)](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fathena.ohdsi.org%2Fsearch-terms%2Fterms%2F46236952&data=05%7C01%7Cmblacke%40its.jnj.com%7C84fd40268a904702c53308db13321b30%7C3ac94b33913548219502eafda6592a35%7C0%7C0%7C638124878146542163%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QgPI%2FjZcGV6Oyu1qvV7LuvvnbCWTWZENRhxg95mQ1zU%3D&reserved=0) is also affected.

**Comment by katy-sadowski** [comment]
@clairblacketer hah! this is very relevant to our vocab meeting last week 😉 thanks for sharing.

As we discussed at the meeting, it's probably infeasible to keep the DQD concepts fully up-to-date with the vocab version, nor would it be worth the effort of doing so given the relatively small number of concepts likely to be impacted, and the fact that our users are likely scattered over many different vocab versions themselves.

That said, I'm thinking a few actions do make sense here:

1. Update DQD code to skip checks on concepts/unit concepts that are not standard in a user's CDM.  This way users won't have check failures like the ones above if they are on a different version of the vocab than the one used in DQD's threshold file
2. At some point in the near-ish future, do a refresh of the concepts in DQD using the latest vocab version (and continue doing so every 6-12 months)
3. Add a note in DQD docs specifying which version of the vocab is used for the concept checks, for users' reference

Thoughts?

**Comment by dimshitc** [comment]
I think we need to go with 
"2. At some point in the near-ish future, do a refresh of the concepts in DQD using the latest vocab version (and continue doing so every 6-12 months)."
Units become non-standard is a rare vocabulary change, probably it will not happen anymore.
If event concepts (measurements in measurement-unit pairs checks, conditions and procedures in gender related checks) become non-standard they will not appear in a data, so the check result will be 0, or PASS, but these checks will be still relevant for users with older vocabulary versions.

**Comment by dimshitc** [comment]
The unit_concept_id = 9117 (milliliter per minute per 1.73 square meter) was replaced with 720870 (milliliter per minute per 1.73 square meter) on 28-Mar-2022. If we update the unit now, the DQD will not support the earlier vocabulary version.

**Comment by katy-sadowski** [comment]
> If event concepts (measurements in measurement-unit pairs checks, conditions and procedures in gender related checks) become non-standard they will not appear in a data

Good point :) and they will fail the standard concept check.

> If we update the unit now, the DQD will not support the earlier vocabulary version.

Also a good point. Perhaps we should actually keep both in the list of accepted concepts? And as above, if someone is using a non-standard unit, this will fail the standard concept check on unit_concept_id.

**Comment by katy-sadowski** [comment]
Closing this out as this specific issue has been fixed (thanks again @dimshitc!!)

I think I will open a GitHub Discussion to keep track of the larger thread of updating all of the plausible unit lists to be more accurate/comprehensive. We can leave notes from the THEMIS conversations there, etc.
