### ISSUE TITLE
Several errors in bigquerry due to "Function not found: charindex"

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [OHDSI/DataQualityDashboard#424]
This is an example of one of the errors. But there are more of the same type. 

```
DBMS:
bigquery

Error:
java.sql.SQLException: [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: Function not found: charindex at [23:25]

SQL:
/*********
FIELD_CDM_DATATYPE
At a minimum, for each field that is supposed to be an integer, verify it is an integer
Parameters used in this template:
cdmDatabaseSchema = atlas-development-270609.jgt_etl_cdm
cdmTableName = DRUG_ERA
cdmFieldName = PERSON_ID
**********/
select 
  num_violated_rows, 
	case 
		when denominator.num_rows = 0 then 0 
		else 1.0*num_violated_rows/denominator.num_rows 
	end as pct_violated_rows, 
	denominator.num_rows as num_denominator_rows
from
(
	select 
	  COUNT(violated_rows.violating_field) as num_violated_rows
	from
	(
		/*violatedRowsBegin*/
		select 
		  'DRUG_ERA.PERSON_ID' as violating_field, 
		  cdmtable.* 
		from atlas-development-270609.jgt_etl_cdm.drug_era cdmtable
		where 
		  CASE WHEN SAFE_CAST(cdmtable.person_id AS FLOAT64) IS NULL THEN 0 ELSE 1 END = 0 
		  or (
		    CASE WHEN SAFE_CAST(cdmtable.person_id AS FLOAT64) IS NULL THEN 0 ELSE 1 END = 1 
		    and charindex('.', cast(abs(cdmtable.person_id) as STRING)) != 0
		  )
      and cdmtable.person_id is not null
		/*violatedRowsEnd*/
	) violated_rows
) violated_row_count,
( 
	select 
	  COUNT(*) as num_rows
	from atlas-development-270609.jgt_etl_cdm.drug_era
) denominator
;


R version:
R version 4.2.2 (2022-10-31 ucrt)

Platform:
x86_64-w64-mingw32

Attached base packages:
- stats
- graphics
- grDevices
- datasets
- utils
- methods
- base

Other attached packages:
- snow (0.4-4)
```

**Comment by javier-gracia-tabuenca-tuni** [comment]
The problem is probably in SqlRender. 
There is a missing traslation for the function `charindex` for bigquerry. 

I filled this in the SqlRender Issues
 https://github.com/OHDSI/SqlRender/issues/323#issue-1615127249

**Comment by konstjar** [comment]
Could you please share JDBC driver version. I know that v1.3.x version has a lack of compatibility with DatabaseConnector. The workaround is using older 1.2.x version

**Comment by javier-gracia-tabuenca-tuni** [comment]
we are using Version 1.2.14. 
But is not driver just used to connect to database? 
I think the issue on the translation to bq, not on the sending the querry to the database. 
But im checking that now

**Comment by clairblacketer** [comment]
> we are using Version 1.2.14. But is not driver just used to connect to database? I think the issue on the translation to bq, not on the sending the querry to the database. But im checking that now, i added a traslation to SqlRender, lets see if that fix the problem

This was going to be my suggestion :) please let us know if your SqlRender fix addresses it

**Comment by javier-gracia-tabuenca-tuni** [comment]
yes, that fix in SqlRender solved the problem 
I made a pull request 
https://github.com/OHDSI/SqlRender/pull/324
It is one line fix. Probably will get merged to main  in next update.
