### ISSUE TITLE
Threshold modification not taken into account

### ISSUE THREAD

**Issue by tlecarrour-ee** [OHDSI/DataQualityDashboard#426]
Hi,

Since I updated DQD to 2.1.1, I have a strange problem with a threshold. I rpetty sure it was working before the update.

I modified several thresholds in `OMOP_CDMv5.3_Field_Level.csv ` to reflect the fact that some mappings to standard concept IDs are not finished yet. For instance, I have:

```
* Modified: CONDITION_OCCURRENCE / condition_concept_id
     - [standardConceptRecordCompletenessThreshold] '5' -> '10'
     - [standardConceptRecordCompletenessNotes] '' -> 'Ongoing Mapping.'
* Modified: DRUG_EXPOSURE / drug_concept_id
     - [standardConceptRecordCompletenessThreshold] '5' -> '10'
     - [standardConceptRecordCompletenessNotes] '' -> 'Ongoing Mapping.'
```

Those two work as expected. But, somehow, the following modification doesn't seem to:

```
* Modified: MEASUREMENT / measurement_concept_id
     - [standardConceptRecordCompletenessThreshold] '5' -> '35'
     - [standardConceptRecordCompletenessNotes] '' -> 'Ongoing Mapping.'
```

The check still shows up as failed in DQD/shiny, even though the  percentage is 33.5 and the notes ("Ongoing Mapping") appears in the detailed view.

Am I doing something so obviously wrong that I can't even see it? Any help would be welcome!

**Comment by katy-sadowski** [comment]
I'm confused as well based on what you've sent!  Could you please send a screenshot of the expanded view of that measurement check result in the DQD UI? (ie the table that appears when you click the + button, with Name, Description, Notes, Level, etc ...). Thanks!

2 ideas in the meantime could be to double check that your DQD is definitely referencing the correct location for the updated threshold files, and the correct location for the output file from the most recent run of the DQD.

**Comment by tlecarrour-ee** [comment]
> Could you please send a screenshot of the expanded view of that
> measurement check result in the DQD UI? 

Sorry I didn't attach it with the original bug report! I won't be able to access the results until Monday, but I will be sure to provide you with the file asap.


> 2 ideas in the meantime could be to double check that your DQD
> is definitely referencing the correct location for the updated threshold
> files, and the correct location for the output file from the most recent
> run of the DQD.

Isn't the fact that my *note* ("Ongoing Mapping") is displayed in the expanded view of the DQD UI enough to say that the threshold file was taken into account?
But, for sure, as the threshold itself is not mentioned (only the default threshold in the check description), I cannot be sure that I'm viewing the right DQD results, right? 🤔

**Comment by katy-sadowski** [comment]
> But, for sure, as the threshold itself is not mentioned (only the default threshold in the check description), I cannot be sure that I'm viewing the right DQD results, right? 

Your threshold should be mentioned in the Description field - that field should display the threshold used to calculate pass/fail for a given check. When you get back into the results next week I'd also check to see if your new thresholds are showing up for the other checks.
