### ISSUE TITLE
Enable unit tests on different database platforms

### ISSUE THREAD

**Issue by schuemie** [OHDSI/DataQualityDashboard#434]
There appears to be [code for running unit tests on the OHDSI testing servers](https://github.com/OHDSI/DataQualityDashboard/blob/main/tests/testthat/setup.R#L16-L57), but that is disabled. It would be good to enable this, so we can catch errors before our users do.

**Comment by katy-sadowski** [comment]
We actually do run remote DB tests - see [here](https://github.com/OHDSI/DataQualityDashboard/blob/6d025931b2f1bb3160176fc88ce0d0433f5ffb36/tests/testthat/test-execute.R#L120).  That commented out code was added during the hackathon; I think it can be removed?  Planning to do that as part of a unit test cleanup project at some point...

That said, we do have a real issue where our unit tests don't check for SQL errors - just that some results were generated by the DQD.  This I also plan to address in that unit testing project.  Pending input from the group in our next DQD meeting I think that'll be next up on the development roadmap after v2.2 release which is in the works.

**Comment by katy-sadowski** [comment]
In the latest release I've reorganized & cleaned up our tests, including removing that extraneous commented out code.  DQD is still tested against the 3 remote DBs in the same test linked above.  (And a project is still in the works to add check-specific tests for our SQL queries 😃).
