### ISSUE TITLE
Error for 2 plausible unit concept checks

### ISSUE THREAD

**Issue by katy-sadowski** [OHDSI/DataQualityDashboard#436]
```The number and percent of records for a given CONCEPT_ID 3036277 (BODY HEIGHT) with implausible units (i.e., UNIT_CONCEPT_ID NOT IN ( INF)). (Threshold=5%).```

```The number and percent of records for a given CONCEPT_ID 3023540 (BODY HEIGHT MEASURED) with implausible units (i.e., UNIT_CONCEPT_ID NOT IN ( INF)). (Threshold=5%).```

For some reason the list of unit concept IDs is not getting parsed properly for these 2 checks.

**Comment by MaximMoinat** [comment]
This could be due to `readr` v2 handling type guessing change: https://readr.tidyverse.org/articles/column-types.html#legacy-behavior 
https://readr.tidyverse.org/articles/column-types.html#legacy-behavior
