### ISSUE TITLE
Upgrade from v1.4.1 to v2.1.2 DataTables Error

### ISSUE THREAD

**Issue by SaraKimUCD** [OHDSI/DataQualityDashboard#439]
Hello @MaximMoinat,

I am working with Health Data Compass and was told by Melanie that I should reach out to you to see if you might be able to provide some insight with an issue I am having. I am trying to upgrade the DQD from version 1.4.1 to the latest 2.1.2 version and am running into the following error:
DataTables warning: table id=dt-results - Requested unknown parameter 'cdmTableName' for row 0, column 2. For more information about this error, please see http://datatables.net/tn/4

We are currently using our own modified thresholds for the CDM files so I thought it might be because the files are incompatible with the new DQD version, but even when I try running the new version using the default CDM files I get the same error. Would you be able to assist me with this error or give me some suggestions on what might be causing this error?

Thank you!
Sara Kim

**Comment by katy-sadowski** [comment]
Hi there @SaraKimUCD - I will chime in here because your issue rings a bell for me and I happen to be working on a solution right now to what I think might be the problem.  Are you by any chance trying to launch `viewDqDashboard` on a results file that was generated using the older version of DQD?  If yes, then this is likely the source of the error.
For the moment, you'll need to revert to a pre-2.1 version of DQD in order to view older files in the Shiny app.  I'm currently working on an update that will allow viewing of older results files in the next DQD version and onwards.
If this is _not_ your issue - it does seem to be some problem with the results.json file (assuming you are getting the error when trying to launch the Shiny app?)

**Comment by SaraKimUCD** [comment]
Hello @katy-sadowski,

Thank you for the fast response! I actually took over the maintenance from someone else so my logic on the details of how the DQD is setup is still a bit low, so I'm sorry for asking some questions that are probably very obvious. 

For the results file that you are mentioning is it the same results.json file that was output from the executeDqChecks where we specify the outputFolder and outputFile? I did trigger the R script for the executeDqChecks to refresh the results of the DQD using the new DQD v.2.1.2 but haven't tried manually checking the results.json file for it afterwards to see if it was actually updated, so I will try checking that to see if it has the new data. Also just to confirm, if I ran the executeDqChecks script and the results.json file has been updated, does that mean that the viewDqDashboard will use the new results.json file? 

I will also try refreshing the DQD with v.2.0 to see if it might be some other issue and update here.

Thank you!
Sara Kim

**Comment by katy-sadowski** [comment]
Hi @SaraKimUCD - FYI I just got that same datatables error when trying to run the DQD Shiny app against an older version DQD results json file, so I'm guessing this is the issue for you!  If you're able to point `viewDqDashboard` at the results file you generated with the new version of DQD the error should go away.  Please do let me know if not!

As I mentioned in my earlier message, I'm also working on a solution that'll allow viewing of older files with newer versions of the package: https://github.com/OHDSI/DataQualityDashboard/pull/440.  This'll be added in a future release :)

**Comment by SaraKimUCD** [comment]
Hello @katy-sadowski and sorry for the very late response!

As you have said, when I deleted the old result.json file that was generated and just triggered the executeDqChecks using v2.0 it picked up the new JSON and the error was not there anymore. Thank you so much for the help! I appreciate you taking the time to help out and will keep watch for the new release as well.
