### ISSUE TITLE
notification about non-preferred units

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/DataQualityDashboard#44]
KB-driven templated rules are great ! I tried to have those in Achilles and I was always referred to the perfect re-design in phase 2 of Achilles. DQD just did it. I love it.

In ThemisConcept study, we defined data driven preferred units.

 How DQD can implement this logic?

Perhaps a column that indicates a unit as non-preferred?

![image](https://user-images.githubusercontent.com/7526119/64549390-9f70b280-d2fe-11e9-99ca-c2b8159fa911.png)

**Comment by vojtechhuser** [comment]
The prefered units per lab test are here: https://github.com/vojtechhuser/ThemisConcepts/blob/master/extras/results2019/S7-preferred_units-ABC.csv

**Comment by vojtechhuser** [comment]
change to CDM convention is here (always in review status despite it is 60+ days)  (sigh....)
https://github.com/OHDSI/Themis/issues/4

**Comment by clairblacketer** [comment]
@vojtechhuser I love this idea, perhaps we can add another column in the concept level checks for this? We would of course need to add an SQL statement to evaluate it and add it to the R function.

**Comment by clairblacketer** [comment]
I am closing this as we implemented new measurement checks looking for plausible units and we removed the plausible value checks.
