### ISSUE TITLE
`measureValueCompleteness` errors for optional fields

### ISSUE THREAD

**Issue by tlecarrour-ee** [OHDSI/DataQualityDashboard#448]
I have a lot of `measureValueCompleteness` errors on fields that are supposed to be optional.

For instance, I have an error on `measurement.range_low` with the following description: "The records with a NULL value in the RANGE_LOW of the MEASUREMENT.", but the documentation [1] states "This should be set to NULL if not provided.".

[1]: https://ohdsi.github.io/CommonDataModel/cdm54.html#MEASUREMENT

For `range_low`, I can raise the threshold, but for most of them, the percentage of errors is 100.

**Comment by katy-sadowski** [comment]
Thanks for reporting this @tlecarrour-ee !  It looks like many fields have this check turned on with no threshold specified - which means the threshold is [defaulting](https://github.com/OHDSI/DataQualityDashboard/blob/1197d5d8287c35a5c3f71d010220959494a160d3/R/evaluateThresholds.R#L136) to 0%!  We'll do a review of these to make sure all non-required fields either have threshold 100 or are disabled.

**Comment by tlecarrour-ee** [comment]
Thanks! Looking forward to it. In the meantime, I'm going to squint really hard not to see them. :-)

**Comment by katy-sadowski** [comment]
Guessing this is related to #319 .  I'll fix in next release.

**Comment by katy-sadowski** [comment]
This is now fixed!

**Comment by tlecarrour-ee** [comment]
Hi @katy-sadowski,

Thanks! I'll give it a try!

Cheers
