### ISSUE TITLE
missing ER visits rule (threshold) - editing the KB

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/DataQualityDashboard#46]
For Psoriasis, we define low and high values.

How would I define low value of at least 0.001% of ER visits.

Also, the current file lists them as condition and that seems wrong

Do I just edit the row 3 in the concept level file.

Edits to Knowledge base - how a PR for those works?

The DataQuality study produced a lot of reference benchmark data and I would be super keen to implement them in DQD

![image](https://user-images.githubusercontent.com/7526119/64619368-f71b2680-d3af-11e9-96c2-35bf6be037a1.png)

**Comment by clairblacketer** [comment]
So far we have not implemented these benchmark/prevalence rules as we were unsure *which* benchmark values to use. The DataQuality study seems perfectly poised to provide those values. What we would then need are SQL scripts to validate them and they need to be added to the R function.
