### ISSUE TITLE
DataQualityDashboard::viewDqDashboard "This site can’t be reached"

### ISSUE THREAD

**Issue by joaofonseca9** [OHDSI/DataQualityDashboard#465]
After executing Dqchecks and obtaining the json file that contains the metadata of the data quality checks, when trying to run viewDqDashboard, I get a normal output:

```
Loading required package: shiny

Listening on http://127.0.0.1:3446
```

However, when I try to access http://127.0.0.1:3446, I cannot see the DataQualityDashboard

![image](https://github.com/OHDSI/DataQualityDashboard/assets/74836152/ea540b4b-3494-4e72-a8c6-295576e33a00)

**Comment by katy-sadowski** [comment]
Hi!  This seems like it's probably an issue with your local setup or networking settings.  You may have a firewall, antivirus, or restricted network that's blocking your access to the local server.   It's also possible that port may be in use by another application.  In case that's the issue, you can try passing in another port number to the `viewDqDashboard` call (add a `port` param and set it to a different port number).

**Comment by katy-sadowski** [comment]
Hello @joaofonseca9 are you still experiencing issues?

**Comment by katy-sadowski** [comment]
I'm going to close this issue for now; please feel free to comment here if you are still blocked.
