### ISSUE TITLE
Error when executing writeJsonResultsToTable

### ISSUE THREAD

**Issue by johardi** [OHDSI/DataQualityDashboard#48]
I got a connection error when trying to write the results in a JSON file.
```
> DataQualityDashboard::writeJsonResultsToTable(connectionDetails = connectionDetails, 
+                                       resultsDatabaseSchema = resultsDatabaseSchema, 
+                                       jsonFilePath = "/tmp/result.json")
Error in open.connection(con, "rb") : cannot open the connection
```

I tried to solve it by providing the file in advance but instead, I got a new error message:
```
Error in parse_con(txt, bigint_as_char) : parse error: premature EOF
                                       
                     (right here) ------^
```

**Comment by alondhe** [comment]
Hi @johardi , is this path the fully qualified path?

**Comment by johardi** [comment]
Yes, it is. Could you be able to reproduce my error?

**Comment by alondhe** [comment]
@johardi - Sorry, not able to. So you can run it fine without writing to table, you get a JSON file that is viewable when running viewDqDashboard, right?

**Comment by johardi** [comment]
Finally, here's what I did:
```
jsonFilePath <- file.path(outputFolder, cdmSourceName, paste0("results_", cdmSourceName, ".json"))
DataQualityDashboard::viewDqDashboard(jsonFilePath)
```

I used the JSON file found in the output directory instead of manually producing it from the `writeJsonResultsToTable` function

**Comment by clairblacketer** [comment]
@johardi has this been resolved? The `writeJSONResultsToTable` function is so that a table can be written back to your results schema with the results from the DQD. In the future I hope to incorporate some time-series analysis across multiple iterations of CDMs, so having a static table in the results schema would be useful.

**Comment by ParkChanghHyun** [comment]
I'm also have ISSUE when I run 「writeJsonResultsToTable 」 function.

![image](https://user-images.githubusercontent.com/45930454/66032180-e50c4e00-e53f-11e9-85f6-a4853424ef19.png)

How you could solve this problem???

**Comment by ParkChanghHyun** [comment]
I solved it! 
In my error, I misunderstand about jsonFilePath.

After  run 「executeDqChecks 」, it make output file of josn format.
you should input that's path & file name.
