### ISSUE TITLE
Add easy to copy violating records SQL

### ISSUE THREAD

**Issue by alondhe** [OHDSI/DataQualityDashboard#49]
In the dashboard, we do provide the full query the DQD executed, which includes a subquery for seeing the violating records.

However, we should make it easier to grab the violating records query.

**Comment by deebowden** [comment]
Hi,
Trio Health is currently implementing our CDM ETLs. We have Atlas and the DataQuality Dashboard live in our development environment. The Dashboard has been extremely helpful in troubleshooting our ETLs. 
We have added a simplistic drilldown capability to view patients by care site that violated a given check. We are interested in how others may have added this functionality if they have. 
Did you decide to implement this feature in your environment?

Have a great day,
Dee

**Comment by clairblacketer** [comment]
This is addressed with PR #282

**Comment by katy-sadowski** [comment]
[`violatedRows` comment wrapper added to subquery for pulling violating records in PR 282]
