### ISSUE TITLE
Finalize DQ Checks - Table Level

### ISSUE THREAD

**Issue by alondhe** [OHDSI/DataQualityDashboard#5]
In this level, we are focusing on 2 patterns:

1. Ensure that every person has at least 1 observation_period
2. Tabulating number of records per person per  month for tables we know to not change over time (IS_TEMPORALLY_CONSTANT != Yes). 
Example: for 2009-01, we see on average 10 conditions per person, then in 2009-02, we see average of 20 conditions per person. We want to highlight and understand that change: perhaps an EHR added a new practice, which is the reason for the increase.
- Visualized as histogram
- Perhaps leverage Kronos to identify temporal breaks

**Comment by pavgra** [comment]
@alondhe / @clairblacketer, could you explain the logic behind the `IS_TEMPORALLY_CONSTANT` column?

**Comment by alondhe** [comment]
Number of records per person per month for each table, using start date
