### ISSUE TITLE
Use gender specific concept set to check the correctness of gender

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/DataQualityDashboard#509]
Currently there are particular gender events checked. 
My proposal is to run this check against the ancestry.
Currently data quality question is: "How many patients with particular event (**prostate cancer**, for example) have female gender?"
I would add another question: "How many patients with **any disorder of male reproductive system** have female gender?"
The existing check doesn't answer the question if the problem is on the concept level (wrong mapping to "prostate cancer") or there was wrong gender assignment. 
The new check will explicitly indicate the problem with mapping of gender as it looks at a whole bunch of concepts

**Comment by dimshitc** [comment]
@clairblacketer @katy-sadowski should I go ahead and create the branch with the changes ?
I will add new high level concepts to the gender specific checks and usage of CONCEPT_ANCESTOR to the existing concepts as well, so, let's say, a **prostate cancer** check will look at all subtypes of prostate cancer.

**Comment by dimshitc** [comment]
Katy: it is a person level check, not a concept level.

**Comment by katy-sadowski** [comment]
Fixed in the latest release, thanks to Dima :)
