### ISSUE TITLE
Max allowed number of refills should be up to 24

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/DataQualityDashboard#511]
Some states allow number of refills up to 24, so we can allow it in CDM
https://www.ama-assn.org/practice-management/sustainability/how-does-extended-prescription-duration-help-your-patients-and#:~:text=Today%2C%20laws%20and%20regulations%20governing,prescription%20duration%20beyond%2012%20months.

**Comment by katy-sadowski** [comment]
does the value in refills always represent months?

**Comment by dimshitc** [comment]
the median value of days_supply where refills >1
in CCAE and Optum EHR is 30, 
so, yes, we can assume it's month.

**Comment by katy-sadowski** [comment]
fixed in latest release, thanks Dima
