### ISSUE TITLE
Modify the check: The number and percent of records with a value in the OBSERVATION_PERIOD_START_DATE field of the OBSERVATION_PERIOD that occurs prior to the date in the BIRTH_DATETIME field of the PERSON table.

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/DataQualityDashboard#513]
Need to modify the check. Currently if the only year of birth is given, it uses CAST(CONCAT(plausibleTable.year_of_birth,'-06-01') AS DATE. But the real date of birth can be easily in the beginning of the year, leading to observation period start at this date.

**Comment by katy-sadowski** [comment]
@MaximMoinat raised this issue as well!  Check his proposed solution here: https://github.com/OHDSI/DataQualityDashboard/issues/445#issuecomment-1529470712.  Agree this should be fixed.
