### ISSUE TITLE
Add UI to view the checks

### ISSUE THREAD

**Issue by alondhe** [OHDSI/DataQualityDashboard#52]
We currently only offer the CSVs as the source of what the checks are, before running the package. This is cumbersome for users to consume, perhaps we could add a UI that shows the check names and fully qualified check descriptions.

We could add a viewDqChecks() function that you provide all the same params as executeDqChecks, and it launches a web page with a dynamic table of checks to be run given the params. This web page should also be used as a section in the dashboard itself.

Thoughts @fdefalco and @clairblacketer ?

**Comment by clairblacketer** [comment]
@alondhe I like this idea, I think if we are concerned about the user experience then it should be a functional UI that would allow for choices to be made about which checks to run, rather than making the user go back to the csv to make any changes

**Comment by alondhe** [comment]
Yep, the number 1 piece of feedback during the DQ Tutorial a few days ago was that knowing what all the checks were was not something we could really demonstrate without opening up the CSVs and explaining away the parameters and columns. Folks in the class wanted to be able to share this information with less technical users, so perhaps a UI that is also printable could be generated based on the CSVs.

**Comment by vojtechhuser** [comment]
why not just use View() for a data.frame?  (to make it simpliest)

**Comment by alondhe** [comment]
Based on the feedback from the DQ Tutorial at the Symposium, just viewing the data frame isn't user friendly enough. Besides, viewing doesn't produce the exact checks, with params fulfilled.
