### ISSUE TITLE
DQD reports on SOURCE_TO_CONCEPT_MAP but table is deprecated

### ISSUE THREAD

**Issue by jam560** [OHDSI/DataQualityDashboard#520]
I don't see any previous issues on this topic. We just ran DQD for the first time. It still contains 24 checks on the SOURCE_TO_CONCEPT_MAP table. This page says the table is no longer part of the CDM standard: https://www.ohdsi.org/web/wiki/doku.php?id=documentation:cdm:source_to_concept_map.

**Comment by clairblacketer** [comment]
Hi @jam560 the SOURCE_TO_CONCEPT_MAP table is part of the cdm but is considered a vocabulary table. It is very much in use by many collaborators usually to house manually curated mappings. http://ohdsi.github.io/CommonDataModel/cdm54.html#Vocabulary_Tables

**Comment by jam560** [comment]
Fair enough. But if you google “omop source_to_concept_map” the first two hits tell you it is obsolete. 

![image](https://github.com/OHDSI/DataQualityDashboard/assets/18703527/2de58a78-af13-4fc4-aa56-7bb323312ef6)
