### ISSUE TITLE
Set plausibleValueLow = 1 in DRUG_EXPOSURE.days_supply

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/DataQualityDashboard#523]
in DRUG_EXPOSURE.days_supply plausibleValueLow = 1, which means 0 is allowed, while according to the CDM conventions days_supply  = 1 if drug was given one time

**Comment by MaximMoinat** [comment]
Linking in the to-be-updated days_supply convention: 
https://github.com/OHDSI/CommonDataModel/pull/593

**Comment by katy-sadowski** [comment]
fixed in latest release
