### ISSUE TITLE
measureConditionEraCompleteness is 'Not Applicable' if condition era table is empty

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/DataQualityDashboard#526]
## Expected behaviour
The check `measureConditionEraCompleteness` checks if condition era is populated and should fail if not all persons that have a condition occurrence also have a condition era.

## Actual behaviour
If Condition Era table is empty, the check status will be 'Not Applicable' (even though it correctly determines that 100% of records fail).

<img width="1124" alt="image" src="https://github.com/OHDSI/DataQualityDashboard/assets/17825660/cdc396a3-2582-4758-9eb0-b285cad8c715">

And reversely, if Condition Occurrence is empty and Condition Era populated, `measureConditionEraCompleteness` will always pass. Here it should be NA as the check has become meaningless.

## Suggested fix
The `measureConditionEraCompleteness` check status should be NA if the condition_occurrence is empty. To do this, I see two options: 1) make a separate variable against which table/field should be checked for emptyness or 2) make an exception for this check.

**Comment by katy-sadowski** [comment]
@MaximMoinat  as part of this fix, would you mind creating a check documentation page for measureConditionEraCompleteness?  😄 thanks
