### ISSUE TITLE
Error: (nrow(checks) > 0) { : argument is of length zero

### ISSUE THREAD

**Issue by don-torok** [OHDSI/DataQualityDashboard#53]
Error occurred when checkLevels <- c("TABLES")

**Comment by don-torok** [comment]
Error in if (nrow(checks) > 0) { : argument is of length zero when checkLevels <- c("TABLES")

**Comment by alondhe** [comment]
can you try checkLevels <- c("TABLE") instead?

**Comment by don-torok** [comment]
My mistake "TABLE" worked.  Thanks
