### ISSUE TITLE
Released version currently failing unit tests

### ISSUE THREAD

**Issue by schuemie** [OHDSI/DataQualityDashboard#540]
This seems to be a bit silly, but I think the issue is that, with R 4.4.0, [this line](https://github.com/OHDSI/DataQualityDashboard/blob/6ef7ee2dd1116741e3fe9907ef4d9cc98eccb96c/R/view.R#L49) needs quotes around the 0, so:
```r
is_installed <- function(pkg, version = "0") {
```

(There is also a note about a mismatch in documentation in the R Check results you may want to fix)

**Comment by katy-sadowski** [comment]
Thanks for figuring that out!  I was pretty confused why this randomly started showing up.  The docs note too must be a new thing in R Check.  One of the params in the header isn't capitalized the right way.  I'll fix both of these in the next release :)

**Comment by katy-sadowski** [comment]
Fixed in v2.6.1.
