### ISSUE TITLE
multiple values for conceptChecks$conceptId failing

### ISSUE THREAD

**Issue by chrisroederucdenver** [OHDSI/DataQualityDashboard#545]
I'm running DQD with sqlOnly and getting an error when it gets down to plausibleGenderUseDescendants.
It's working line 335 in inst/csv/OMOP_CDMv5.3_Concept_Level.csv:
`CONDITION_OCCURRENCE,CONDITION_CONCEPT_ID,"4090861, 4025213","Male genitalia finding, Male reproductive finding",,,,,,,,,,Male,,2,,,,,,,,,,,,,`
The two concepts in the third column cause it to build  this string:
	conceptChecks$plausibleGenderUseDescendantsThreshold[conceptChecks$cdmTableName == "CONDITION_OCCURRENCE" & conceptChecks$cdmFieldName == "CONDITION_CONCEPT_ID" & conceptChecks$conceptId == 4090861, 4025213]
I think that last "==" is failing, and wold work if it were an in-list:
	conceptChecks$plausibleGenderUseDescendantsThreshold[conceptChecks$cdmTableName == "CONDITION_OCCURRENCE" & conceptChecks$cdmFieldName == "CONDITION_CONCEPT_ID" & conceptChecks$conceptId in  (4090861, 4025213)]

getThreshold() in sql/sqlOnly.R would have to look for commas and spaces in the unitConceptId and format as an in-list instead.

Where else might such errors occur? evaluateThresholds.R has similar code.

**Comment by chrisroederucdenver** [comment]
It stitches together this string:
`	conceptChecks$plausibleGenderUseDescendantsThreshold[conceptChecks$cdmTableName == "CONDITION_OCCURRENCE" & conceptChecks$cdmFieldName == "CONDITION_CONCEPT_ID" & conceptChecks$conceptId == 4090861, 4025213]`
I think  that last "==" is not happy, and wold work if it were an in-list:
`	conceptChecks$plausibleGenderUseDescendantsThreshold[conceptChecks$cdmTableName == "CONDITION_OCCURRENCE" & conceptChecks$cdmFieldName == "CONDITION_CONCEPT_ID" & conceptChecks$conceptId in  (4090861, 4025213)]`

getThreshold() in sql/sqlOnly.R would have to look for commas and spaces in the unitConceptId and format as an in-list instead.

**Comment by katy-sadowski** [comment]
Thanks for reporting this @chrisroederucdenver !  This is a new check and I'm guessing we didn't make the necessary update to sqlOnly functionality when adding it in.  I'll get this fixed in the next release.

**Comment by chrisroederucdenver** [comment]
Thanks Katy. I also wondered if sqlOnly provided an avenue for CI/CD tests with and without a database.

I wish I had time to work on it this summer. I'm both envious of and thankful for your work!

**Comment by katy-sadowski** [comment]
> I also wondered if sqlOnly provided an avenue for CI/CD tests with and without a database.

Do you mean CI/CD for your ETL?  If yes - I believe there are folks doing this - taking the SQL and then incorporating it into their pipeline.

**Comment by chrisroederucdenver** [comment]
No, I mean DQD could have a build run with each commit via a github action.  Acknowledging that there are a bunch of things you couldn't test this way, there are a few that you could. The issue here is one where at least you can check the file parses.

**Comment by katy-sadowski** [comment]
Ahh, yes, we actually do have [tests](https://github.com/OHDSI/DataQualityDashboard/blob/6ef7ee2dd1116741e3fe9907ef4d9cc98eccb96c/tests/testthat/test-executeDqChecks.R#L208-L330) for SqlOnly mode ... but they only test the run of a single check (and not the one causing an issue here).  Our tests leave a lot to be desired.  For SqlOnly mode, we could probably just be doing a full run of DQD since I doubt runtime will be a concern there.  I'll look into it :)

**Comment by katy-sadowski** [comment]
This has been fixed in the v2.6.1 release.
