### ISSUE TITLE
Overview and Checkresults counts are not matching when missing specific checkNames

### ISSUE THREAD

**Issue by Bharathi1991** [OHDSI/DataQualityDashboard#565]
I am using R 4.3.1 and DQD 2.6.1. I am noticing a difference between checkResults and Overview object in the results produced by `executeDQChecks` method in DQD Dashboard when certain checkNames are omitted from the list. These checkNames are defined [here in calculateNotApplicableStatus.R](https://github.com/OHDSI/DataQualityDashboard/blob/main/R/calculateNotApplicableStatus.R#L33). In the absence of any one of these 3 checkNames, the code does not update the default value for passed column which is zero (initialized [here](https://github.com/OHDSI/DataQualityDashboard/blob/main/R/evaluateThresholds.R#L31) and updated within [calculateNotApplicableStatus.R here](https://github.com/OHDSI/DataQualityDashboard/blob/main/R/calculateNotApplicableStatus.R#L190). So, if we miss to add those 3 checkNames, this results in this mismatch. Screenshots showing this behavior can be seen below,

## resultsViewer
Showing 0 for passed column
![image (1)](https://github.com/user-attachments/assets/d5fd78cf-9255-4d89-aeed-7fba1ba3ed55)

## Overview
`results$overview` object showing a non-zero `countPassed` value
![image3](https://github.com/user-attachments/assets/c13474c4-f7ce-40da-8565-b333c83cf2b2)

## DQD Dashboard 
Results from inaccurate checkResults object
![image (2)](https://github.com/user-attachments/assets/2962163f-897b-4083-9123-faf92ee87c93)
Relevant OHDSI Forum post - https://forums.ohdsi.org/t/dqd-results-mismatch-between-overview-and-checkresults-when-missing-specific-checknames/22337

Can anyone help me understand why we require these 3 speciifc checks to update the column. Just curious to know if these 3 checks are of some significance among the rest. If not, can we please update the code so that the overview and checkResults objects are always in alignment with each other.

**Comment by katy-sadowski** [comment]
Thanks @Bharathi1991 for moving your report over here!  One thing to confirm - when you do include those 3 checks, you do _not_ experience this issue with the pass/fail counts in the summary table?  Also, are you seeing any issue with check statuses in the full list of check results, or does this just impact the summary table?

**Comment by Bharathi1991** [comment]
Hi @katy-sadowski , Can you please clarify if you referring to the table that gets created in results schema dqdashboard_results by summary table?

The `checkResults` object and the table that gets created (`dqdashboard_results`) are in alignment with each other. So they are both equally impacted. 

And when we include all these 3 checks in `checkNames`, then the `isPassed` column in `checkResults` is accurate and it matches with the counts in `results$Overview` object. When missing any one of those 3 checks, the checkResults and dqdashboard_results have inaccurate check status values. 

Hope I understood your question correctly. Can you please let me know if my answer is unclear.

**Comment by katy-sadowski** [comment]
Sorry I wasn't clear and thanks for the additional info!  In my comment I was referring to the Shiny app UI, and "summary table" = the last screenshot in your post, and "full list of check results" = this:

<img width="1132" alt="Screenshot 2024-09-12 at 7 39 58 PM" src="https://github.com/user-attachments/assets/f83adddb-c632-486c-b36c-edca81055749">

So you did answer my first question.  In my second question, I'd like to know if all checks are listed correctly with the correct statuses in the list of checks in the Shiny App.

**Comment by katy-sadowski** [comment]
@Bharathi1991 any update here?

**Comment by katy-sadowski** [comment]
closing for now - @Bharathi1991 please re-open if you're still experiencing issues.
