### ISSUE TITLE
Check plausibleTemporalAfter date format problem

### ISSUE THREAD

**Issue by dassagichnicht** [OHDSI/DataQualityDashboard#566]
In the check "plausibleTemporalAfter" the year of birth is cast to a date by concatenating it with "-06-01". The date format which is used is however "YYYYMMDD". This leads to the error `java.sql.SQLDataException: ORA-01843: not a valid month`.

This is an example:
`CAST(plausibleTable.BIRTH_DATETIME AS DATE),
				TO_DATE(CONCAT(plausibleTable.year_of_birth,'-06-01'), 'YYYYMMDD')`

An easy fix would be to just remove the "-" in the string. 

Unfortunately, I wasn't able to find the file in which the check is defined to make sure the problem is not already solved, and I'm just using an old version.

**Comment by katy-sadowski** [comment]
Same comment as for the other issue. Please confirm that you are using the latest version of the package.
The source SQL is here and does not contain dashes: https://github.com/OHDSI/DataQualityDashboard/blob/main/inst/sql/sql_server/field_plausible_temporal_after.sql

If you are on the latest DQD version, this may be an issue with SqlRender.

**Comment by katy-sadowski** [comment]
@dassagichnicht I am going to close this issue for now but please let me know if you continue to have problems after updating the package.
