### ISSUE TITLE
Error When Trying to Install Package

### ISSUE THREAD

**Issue by anonymous34** [OHDSI/DataQualityDashboard#57]
```
> devtools::install_github("OHDSI/DataQualityDashboard")
Error: Failed to install 'unknown package' from GitHub:
  schannel: SNI or certificate check failed: SEC_E_WRONG_PRINCIPAL (0x80090322) - The target principal name is incorrect.

```
Any ideas?  Thank you

**Comment by alondhe** [comment]
Can you check to see you're on the latest version of devtools?

**Comment by anonymous34** [comment]
I do.  I have version 2.2.1

**Comment by anonymous34** [comment]
So is anything from OHDSI compatible with the latest version of R because everything with OHDSI is getting this error.  R version is 3.6.1

**Comment by alondhe** [comment]
I don't think that's a problem, I'm using that version as well. It seems like some certificate error between your client and GitHub. Have you tried installing on a different machine?

**Comment by anonymous34** [comment]
It was a proxy configuration issue.  This is re
