### ISSUE TITLE
Remove 'meas value' domain restriction

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/DataQualityDashboard#580]
For measurement.value_as_concept_id we require that the domain is 'meas value'. However, there are some 'Maps to Value' relationships that do not map to 'meas value' concepts. We should remove this restriction given that it is not reflected in the vocabulary. 

for reference: https://github.com/OHDSI/CommonDataModel/issues/598

**Comment by katy-sadowski** [comment]
This was fixed in release 2.6.2 :)
