### ISSUE TITLE
Allow specification of OMOP tables to either exclude or include in the test harness

### ISSUE THREAD

**Issue by WJMetcalfUNRMed** [OHDSI/DataQualityDashboard#582]
I am standing up the Data Quality Dashboard for the first time. Many of the errors I'm seeing involve tables that our OMOP project is not generating such as DOSE_ERA, DRUG_ERA, FACT_RELATIONSHIP, NOTE_NLP, EPISODE and COST. Being able to filter out one or all of those tables would reduce many harness errors given that they are not present in our OMOP payload.  If this is already existing functionality I apologize as I have not been able to find this in the doc.

**Comment by clairblacketer** [comment]
Hi @WJMetcalfUNRMed , in the [executeDqChecks](https://ohdsi.github.io/DataQualityDashboard/reference/executeDqChecks.html) function there is a parameter called `tablesToExclude` where you can pass a vector of tables names that you do not want DQD to evaluate.
