### ISSUE TITLE
Move Heel rules fully to DQD

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/DataQualityDashboard#60]
readme may try to explain the relationship

Also, is the plan to move some or all the rules from Heel to DQD?

**Comment by vojtechhuser** [comment]
with end of Heel, this issue can be used to port all Heel rules to DQD. Rules are:

Is this rule in DQD ?

31 | ratio of providers to total patients

**Comment by AnthonyMolinaro** [comment]
As HEEL has been removed from Achilles, here are the HEEL sql checks from an branch in Nov' 21:  [HEEL QUERIES](https://github.com/OHDSI/Achilles/tree/e21c7e16cb4cbd653e3e572db86b536cdda86aca/inst/sql/sql_server/heels/serial)

**Comment by clairblacketer** [comment]
Heel rules: https://github.com/OHDSI/Achilles/blob/e21c7e16cb4cbd653e3e572db86b536cdda86aca/inst/csv/heel/heel_rules_all.csv
