### ISSUE TITLE
Data Quality Dashboard Only Displaying Some Sections

### ISSUE THREAD

**Issue by anonymous34** [OHDSI/DataQualityDashboard#61]
So I got the shiny app to launch.  The overview section is showing up.  However, the sections for metadata and results are blank.  The blank sections have the title, but no data.  So it looks like this:

METADATA

RESULTS

Am I missing something or is this a bug?

**Comment by alondhe** [comment]
Most likely it is not seeing the results JSON file correctly. When you launched the app, did you use this:

`DataQualityDashboard::viewDqDashboard(jsonPath = "/the/full/path/to/jsonfile.json")`

**Comment by anonymous34** [comment]
This is my code.  I copied and pasted the the ip address below to google chrome because it was it was really warped in its display on IE.  My company uses an old version so I was not surprised.

```
> 
> DataQualityDashboard::viewDqDashboard(jsonPath = "C:/DataQualityDashboard/CDMV5.3.1/results_CDMV5.3.1.json")
Loading required package: shiny

Listening on http://127.0.0.1:7553
```

**Comment by alondhe** [comment]
Yeah, IE warps pretty much most OHDSI web apps. Chrome is highly recommended here.

In Chrome, can you hit Ctrl-Shift-I to open the web developer console, then click on the Console tab to see if there are any errors being thrown?

**Comment by mgurley** [comment]
We are getting the same problem.  Here is the error from the console.

TypeError: this.results.Metadata[0] is undefined

Our metadata table is empty.  I am assuming this is causing the problem.  The METADATA documentation does not completely make it clear what should go in this table:

https://github.com/OHDSI/CommonDataModel/wiki/METADATA

I am assuming at the least we need one entry to describe the CDM version.  So maybe the following but I have some missing values that I would appreciate some help on:

field| value|concept_name
--|--|--
metadata_concept_id|1147638|OMOP CDM Version 5.3.1
metadata_type_concept_id|?|?
name|?|?
value_as_string|?|?
value_as_concept_id|?|?
metadata date|?|?
metadata_datetime|?|?

**Comment by alondhe** [comment]
We use the CDM_SOURCE table to populate the Metadata section in the app, not the metadata table (which is not used at all here). 

@mgurley is that table populated in your CDM?

**Comment by mgurley** [comment]
@alondhe No the CDM_SOURCE table is not populated.  I will populate CDM_SOURCE to see if it fixed the problem.

**Comment by anonymous34** [comment]
Does this fix the results not showing up either?

**Comment by mgurley** [comment]
Populating CDM_SOURCE solved the problem for us.

**Comment by clairblacketer** [comment]
It is not very well specified that the CDM_SOURCE table needs to be populated for all results to display. I will make a note to put this in the upcoming vignette.

**Comment by anonymous34** [comment]
Okay is there supposed to be one record in this table?

**Comment by clairblacketer** [comment]
yes that is correct, you only need one record

**Comment by vojtechhuser** [comment]
well. there was a big discussion if one row and one row only is expected ! I am not sure the specs say one record.

**Comment by ParkChanghHyun** [comment]
When I test "Data Quality Dashboard" with [CMS SynPUF 5% Sample] data , It occurred error like bellow.
![image](https://user-images.githubusercontent.com/45930454/70298331-a2fbd300-1834-11ea-9f9e-021b9f81808e.png)


"Data Quality Dashboard" well working in 'checkLevels is ("Table") or ("Field")', 
But when I run the "Data Quality Dashboard ::executeDqChecks" function  this error occurred in checkLevels <- c("CONCEPT").


Before I filled "CDM_SOURCE" TABLE it is well working. 
But After I filled "CDM_SOURCE" TABLE [Data Quality Dashboard ::executeDqChecks] is occurred error in concept checkLevel.

can I have some advice?

**Comment by katy-sadowski** [comment]
Docs now specify that CDM_SOURCE table must be populated: https://ohdsi.github.io/DataQualityDashboard/#data-requirements; https://ohdsi.github.io/DataQualityDashboard/articles/DataQualityDashboard.html#note

`executeDqChecks` also stops running & notifies user if cdm_source table is empty: https://github.com/OHDSI/DataQualityDashboard/blob/3425ba428ecfc0fd09f1324b11ac4cf35849524b/R/executeDqChecks.R#L121
