### ISSUE TITLE
“DataQualityDashboard” OUTPUT can’t understand

### ISSUE THREAD

**Issue by ParkChanghHyun** [OHDSI/DataQualityDashboard#62]
> Hi! I’m park in Korea.
> 
> our environment is “ORACLE”
> 
> Now a days, I check our 「CDM DB 」 to “DataQualityDashboard”.
> 
> I have 2 Question output in “log_DqDashboard_@OUR_cdmSourceName.txt”,
> 
>
> 
>

**### First SqlRender occurred warning.**

###########################################################################

imageimage.png1181x842 16.1 KB
![image](https://user-images.githubusercontent.com/45930454/66905870-9b445d00-f041-11e9-868c-9296dada17a6.png)

###########################################################################

> -too many warning about SqlRender.
> I already set some UTF setting in r studio. So how can I solve this warning.
> 
>
> 
>
**### Second DataQualityDashboard Error.**

**「 This is error message」**
###########################################################################

imageimage.png1666x26 3.48 KB
![image](https://user-images.githubusercontent.com/45930454/66905825-8bc51400-f041-11e9-856e-182d75f72baa.png)

###########################################################################

> But When I run the DQ query in manually, It hasn’t error like bellow image.

imageimage.png1040x738 36.4 KB .
![image](https://user-images.githubusercontent.com/45930454/66905889-a5fef200-f041-11e9-9f80-19373c1d1bf6.png)

> In this case, how can I solve this error.
> I can’t catch the “invalid multibyte string” meaning.

**Comment by clairblacketer** [comment]
Hi @ParkChanghHyun I haven't seen this error before though it's interesting that the SQL prior to rendering works fine while after rendering it doesn't. Here's what I would do to error check further:

Run the `executeDqChecks` function with `sqlOnly` set to TRUE. With this turned on it will create sql files in your `outputFolder` AFTER being run through sqlRender. I would take one of these files and run it in your environment to see if you get a more descriptive error message.

@fdefalco any idea what might be happening here?

**Comment by alondhe** [comment]
@ParkChanghHyun it seems like a DatabaseConnector issue possibly. You ran it manually in a SQL editor, can you instead run it using DatabaseConnector::querySql to verify?

**Comment by ParkChanghHyun** [comment]
Thanks all I got a SOLUTION !!!
In this case, It need to 

add  code  
> Sys.setlocale('LC_ALL',locale="us").

After then run a code

![image](https://user-images.githubusercontent.com/45930454/66985799-85de3a00-f0f8-11e9-8cba-47dec7199f4e.png)
