### ISSUE TITLE
Remove payer_plan_period.payer_plan_period_id foreign key check

### ISSUE THREAD

**Issue by don-torok** [OHDSI/DataQualityDashboard#63]
In field level check, payer plan period id is defined as a foreign key into person table

**Comment by clairblacketer** [comment]
Thanks for catching that!

**Comment by ericaVoss** [comment]
Agree with Don 

![bitmoji](https://sdk.bitmoji.com/render/panel/4f211e34-f0a8-4ad4-b294-4aadf9aa76b7-57e33e42-97a5-4431-9f6b-41da527dbc87-v1.png?transparent=1&palette=1&width=246)

**Comment by nbpshc** [comment]
@clairblacketer  
You can assign this to me. 
I am working on some payer_plan_period initiatives and I can help resolve.
I may need to connect with you separately before I start working on this.
