### ISSUE TITLE
Some measurement plausibility checks have incorrect range

### ISSUE THREAD

**Issue by don-torok** [OHDSI/DataQualityDashboard#66]

**Comment by don-torok** [comment]
Can you review the plausible range for these test/unit pairs.  They do not seem to agree with what I see on the WWW.


cdmTableName | cdmFieldName | conceptId | conceptName | unitConceptId | unitConceptName | plausibleValueLow | plausibleValueLowThreshold | plausibleValueHigh |   | Note
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
MEASUREMENT | MEASUREMENT_CONCEPT_ID | 3019800 | Troponin T.cardiac [Mass/volume] in Serum or Plasma | 8842 | nanogram per milliliter | 1 | 5 | 40 | 5 | Normal range: below 0.04   ng/ml
MEASUREMENT | MEASUREMENT_CONCEPT_ID | 3027597 | Bilirubin.direct [Mass/volume] in Serum or Plasma | 8840 | milligram per deciliter | 1 | 5 | 398 | 5 | Range mg/dL:[0.1,0.3];
MEASUREMENT | MEASUREMENT_CONCEPT_ID | 3007359 | Bilirubin.indirect [Mass/volume] in Serum or Plasma | 8840 | milligram per deciliter | 1 | 5 | 100 | 5 | Range mg/dL:[0.2,0.7];
MEASUREMENT | MEASUREMENT_CONCEPT_ID | 3024128 | Bilirubin.total [Mass/volume] in Serum or Plasma | 8840 | milligram per deciliter | 1 | 5 | 100 | 5 | Range mg/dL:[0.3,1.0];
MEASUREMENT | MEASUREMENT_CONCEPT_ID | 3026925 | Triiodothyronine (T3) Free [Mass/volume] in Serum or Plasma | 8820 | picogram per deciliter | 600 | 5 | 10000 | 5 | The reference range of   free triiodothyronine (FT3) in adults is 260-480 pg/dL

**Comment by clairblacketer** [comment]
@don-torok these values are looking at biological plausibility rather than normal ranges. Does that help answer the question or would they still be off based on that criteria?

**Comment by don-torok** [comment]
I assume to be 'not plausible' the means the value as number is so far above or below the normal range that it is unlikely to be in your data.  But look a specific example 1st row, Troponin T.cardiac the generated query flags any Measurement record where the measurment concept id = 3019800 AND unit_concept_id = 8842 and value_as_number < 1.  But if a normal reading is 0.4, then every 'normal' row is going to be flagged as invalid.  That cannot be correct.

**Comment by clairblacketer** [comment]
@don-torok that is very fair, I agree we need to revisit these combinations and the chosen plausible values.

**Comment by deebowden** [comment]
Another example :
(LOINC: 1968-7) Bilirubin.direct [Mass/volume] in Serum or Plasma,  has a rough reference range of  0.1 - 0.3 when provided in mg/dL
The PlausibleLowValue for this test/unit combination in OMOP_CDMv5.3.1_Concept_Level.csv is **1.0**

For now we are updating odd ranges like this locally. Is there a group working on these?
I can propose some updated PlausibilityLowValues via a PR if that is appropriate.


from OMOP_CDMv5.3.1_Concept_Level.csv:
MEASUREMENT	MEASUREMENT_CONCEPT_ID	3027597	Bilirubin.direct [Mass/volume] in Serum or Plasma	8840	milligram per deciliter	1	5	398	5

**Comment by Andreyyiv** [comment]
@clairblacketer Another example is `For the combination of CONCEPT_ID  3025315 (Body weight) and UNIT_CONCEPT_ID 9373 (ounce (avoirdupois)), the number and percent of records that have a value higher than    1000.0.` The value [seems to be the same](https://github.com/OHDSI/DataQualityDashboard/blob/master/inst/csv/OMOP_CDMv5.3.1_Concept_Level.csv) in pounds, ounces, and mg. It should be 16000 oz and 500000000 mg.

**Comment by clairblacketer** [comment]
I am closing this as we implemented new measurement checks looking for plausible units and we removed the plausible value checks.
