### ISSUE TITLE
Make csv files parameters in runDataQualityDashboard function

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/DataQualityDashboard#67]
It is conceivable that a site can have multiple csv files for different CDM instances. We should build in a way to reference them individually without having to rename and move them all each time you want to run for a different db.

**Comment by dmitryilyn** [comment]
Hi @clairblacketer !
Recently I was faced with having to run DQD checks on a 5.2.2 dataset. I added separate CSVs for v5.2.2 and also added the cdmVersion parameter to the execution.R file:
https://github.com/dmitryilyn/DataQualityDashboard/commit/d23ebbe610b3d70dae55d6118e863165bd462db2
These changes helped us to increase the percentage of passed checks.
I can create a pull request from this fork, or create a separate branch with new changes (if you invite me as collaborator).
Thank you!

**Comment by dmitryilyn** [comment]
Hi @clairblacketer ,
Recently I was faced with having to run DQD checks on a 5.2.2 dataset. 
I added separate CSVs for v5.2.2 and also added the cdmVersion parameter to the execution.R file:
https://github.com/dmitryilyn/DataQualityDashboard/commit/d23ebbe610b3d70dae55d6118e863165bd462db2
(it helped us to increase the number of passed checks)
If you find these changes helpful, then I will create a pull request from my fork.

**Comment by dmitryilyn** [comment]
Hi @clairblacketer ,
Recently I was faced with having to run DQD checks on a 5.2.2 dataset.
I added separate CSVs for v5.2.2 and also added the cdmVersion parameter to the execution.R file:
https://github.com/dmitryilyn/DataQualityDashboard/commit/1f3396140e1b66b019f81cb8a168aa09e3120aef
(it helped us to increase the number of passed checks)
If you find these changes helpful, then I will create a pull request.

**Comment by clairblacketer** [comment]
Thanks @dmitryilyn, this sounds very useful! Please submit a pull request so we can review.

**Comment by dmitryilyn** [comment]
@clairblacketer Done:
https://github.com/OHDSI/DataQualityDashboard/pull/71
