### ISSUE TITLE
Add exclusion option for checkNames

### ISSUE THREAD

**Issue by bronshvayg** [OHDSI/DataQualityDashboard#68]
Currently there is ability to limit the number of names to check by defining list of names into checkNames object. It would be nice to have an option to specify list of the Names to exclude from the run, i.e. run all checks, except specified names.

**Comment by vojtechhuser** [comment]
you can get all of them and do a minus set operation.
see 
http://rpubs.com/vojtech_huser/book701   chapter DQD

```
checkNames=c('plausibleValueLow')

#all checks are here
dashChecks<-read.csv(system.file("csv","OMOP_CDMv5.3.1_Check_Descriptions.csv",package="DataQualityDashboard"),as.is=T)
dashChecks$checkName
```

**Comment by katy-sadowski** [comment]
docs are being updated in #443

**Comment by katy-sadowski** [comment]
Docs (code to run) updated in v2.3.0 release.

**Comment by katy-sadowski** [comment]
I realized I got confused, in 2.3.0 docs were updated to demonstrate `tablesToExclude`, not how to exclude checks. Will add this in a future release.

**Comment by katy-sadowski** [comment]
Docs have been updated with suggestion for how to exclude checks in v2.4.1
