### ISSUE TITLE
Create numbers for the checks

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/DataQualityDashboard#70]
Create a way to permanently number the data quality checks so they can be referred to by external sources

**Comment by alondhe** [comment]
Seems like there's 2 options:

### **1. Use descriptive Ids**

**Pros:**
- Easy to interpret
- No need to create a new numbering system

**Cons:**
- Unwieldy names as we don't have concept ids for CDM table names or CDM field names
- When CDM specs change, we will have checks that do the same thing, but have different names
  - e.g. for Death checks in V5.3.1, these will use "Death" in the check name, but in V6, they will need to use something else ("Person" or "Condition_Occurrence")

### **2. Use integer ids**

**Pros:**
- We can assign a permanent id to every check, and this id can persist even across CDM versions. 
  - So for the death example above, a check on death events can have the same id between V5.3.1 and V6.

**Cons:**
- Not easy to interpret, a lookup would be needed

I think the ability to maintain the check meaning across CDM versions is huge, so leaning towards integer ids.
