### ISSUE TITLE
 After I filled "CDM_SOURCE" TABLE, Data Quality Dashboard occurred error

### ISSUE THREAD

**Issue by ParkChanghHyun** [OHDSI/DataQualityDashboard#74]
When I test “Data Quality Dashboard” with [CMS SynPUF 5% Sample] data , It occurred error like bellow.
image
![image](https://user-images.githubusercontent.com/45930454/70872212-c28bbc00-1fe9-11ea-9c1b-def0bd0cef26.png)

“Data Quality Dashboard” well working in ‘checkLevels is (“Table”) or (“Field”)’,
But when I run the “Data Quality Dashboard ::executeDqChecks” function this error occurred in checkLevels <- c(“CONCEPT”).

Before I filled “CDM_SOURCE” TABLE it is well working.
But After I filled “CDM_SOURCE” TABLE [Data Quality Dashboard ::executeDqChecks] is occurred error in concept checkLevel.

can I have some advice?

it is full log.

image
![image](https://user-images.githubusercontent.com/45930454/70872214-c6b7d980-1fe9-11ea-9f5e-b78750e5d824.png)

**Comment by alondhe** [comment]
What happens when you run the full package (meaning, don't pass in anything to checkLevels)?

**Comment by clairblacketer** [comment]
@ParkChanghHyun is this still an issue for you?
