### ISSUE TITLE
Add denominator to JSON

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/DataQualityDashboard#77]
Add the denominator of each check to the JSON

**Comment by alondhe** [comment]
For each check template, add the denominator.num_rows to the select statement. Also, add this as a field to the JSON creation.

**Comment by alondhe** [comment]
Fixed in latest commit

**Comment by jimfrankfort** [comment]
> Add the denominator of each check to the JSON

thanks for updating the DQD!  We ran this and see the version listed as DQD 1.0.0.  This is nice but not sufficient to address our use case.  We have 3 data partners and we want to all run the exact same DQD.  I don't think 1.0.0 does it.  the prior release had some bugs fixed (e.g. case statement in field names)....what would that version be?  Although we can sync our DQDs by loading a specific  commitID ID, it would be nice to be able to tell from the meta data.  Apologies in advance if I am mistaken.  thx

**Comment by alondhe** [comment]
Hmm. I think the best option will be to include the commit version as well. I'll open a new issue.
