### ISSUE TITLE
Add FIELD name to the UI

### ISSUE THREAD

**Issue by alondhe** [OHDSI/DataQualityDashboard#80]
In the current table UI, we don't have the field name available except for in the description. It would be easier to read if we include it.

![image](https://user-images.githubusercontent.com/8037742/72644588-39d4a880-3926-11ea-8bab-bf925f47e78d.png)

**Comment by jimfrankfort** [comment]
Until a persistent unique identifier is created for data quality checks, I needed to create one to combine DQD results from multiple CDM instances.  It would be great if you would include conceptID, unitConceptID, and quality check denominator count in addition to CDM_Field_Name in the JSON output.  I need the denominator to combine results at the DQ check level (sum of numerators, sum of denominators, recalc %).
  Fields needed to uniquely ID a DQ check are:
Check_Level, Check_Name, CDM_Table_Name, CDM_Field_Name, conceptID, and unitConceptID, 
We are string processing the query text to get these field values.....but it would be nice if it were part of the JSON output.  Also, we are estimating the denominator using numerator and % violated....but that doesn't work when there are 0 failures :-).....need that output too.

thanks for considering this!.....jimf

**Comment by alondhe** [comment]
@jimfrankfort added the denominator for now in my fork. I'll look into adding the other fields you mentioned.
