### ISSUE TITLE
Data Quality Metric Proposal - Visit Date Discrepancies

### ISSUE THREAD

**Issue by noahgengel** [OHDSI/DataQualityDashboard#82]
It would be helpful if the DQD had the following metric:

Measured the 'date' agreement between a particular domain (e.g. observation) and the 'date' for any linked IDs (e.g. a visit_occurrence_id). 

The following would be an instance of a 'date' disagreement:
- an observation_id that has an observation_date of February 6th, 2020 and a linked visit_occurrence_id of 12345
- visit_occurrence_id 12345 has a visit_start_date of December 13th, 2019 and a visit_end_date of December 13th, 2019

The following 'issues' would be of use to document:
- the number of discrepant records
- the average distance between the two records

For example of how these metrics were calculated and applied to the AoU dataset, please see [this notebook from the AoU Curation GitHub.](https://github.com/all-of-us/curation/blob/develop/data_steward/analytics/cdr_ops/foreign_key_gaps.py)

Please feel free to contact me if you have any other questions or would like to see the output of this code with respect to the AoU dataset.

**Comment by RogerJCarlson** [comment]
We have several examples of measures that fail this metric, but are valid.  Particularly in the ambulatory setting.

- Person has an office visit, but does not get the drug until the next day.

- Hospital/ER visit spans midnight, so the first blood pressure is taken before midnight, but the admission is after midnight

- Another involves a death, but organs are harvested after discharge.

There is a more detailed discussion here: [https://forums.ohdsi.org/t/visit-date-disparity-in-ambulatory-setting/12190/2](https://forums.ohdsi.org/t/visit-date-disparity-in-ambulatory-setting/12190/2)

I would suggest a date range of at least one day on either side of the visit date.  Better would be a week on either side.

**Comment by clairblacketer** [comment]
Closed - we added the withinVisitDates check and padded the visits dates by a week on either side based on Roger's suggestion.
