### ISSUE TITLE
Errors when run the checking job

### ISSUE THREAD

**Issue by zrwu** [OHDSI/DataQualityDashboard#83]
returns error: "java.lang.RuntimeException: Don't know how to translate from sql server to allofus. Valid target dialects are sql server" when using argument(s): list(checkLevel = "FIELD", checkName = "cdmField", checkDescription = "A yes or no value indicating if all fields are present in the @cdmTableName table as expected based on the specification. ", kahnContext = "Verification", kahnCategory = "Conformance", kahnSubcategory = "Relational", sqlFile = "field_cdm_field.sql", evaluationFilter = "cdmFieldName!=''"),list(cdmTableName = c("PERSON", "OBSERVATION_PERIOD", "VISIT_OCCURRENCE", "CONDITION_OCCURRENCE", "DRUG_EXPOSURE", "PROCEDURE_OCCURRENCE", "DEVICE_EXPOSURE", "MEASUREMENT", "VISIT_DETAIL", "NOTE", "NOTE_NLP", "OBSERVATION", "SPECIMEN", "FACT_RELATIONSHIP", "LOCATION", "CARE_SITE", "PROVIDER", "PAYER_PLAN_PERIOD", "COST", "DRUG_ERA", "DOSE_ERA", "CONDITION_ERA"), schema = c("CDM", "CDM", "CDM", "CDM", "CDM", "CDM", "CDM", "CDM", "CDM", "CDM", "CDM", "CDM", "CDM", "CDM", "CDM", "CDM", "CDM", "CDM", n"CDM", "CDM", "CDM", "CDM"), isRequired = c("Yes", "Yes", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No"), conceptPrefix = c("", "", "VISIT_", "CONDITION_", "DRUG_", "PROCEDURE_", "DEVICE_", "MEASUREMENT_", "VISIT_DETAIL_", "", "", "OBSERVATION_", "SPECIMEN_", "", "", "", "", "", "", "", "", ""), measurePersonCompleteness = c("No", "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", "No", "Yes", "Yes", "No", "No", n"No", "No", "Yes", "No", "Yes", "Yes", "Yes"), measurePersonCompletenessThreshold = c(NA, 0, 95, 95, 95, 95, 100, 95, 100, 100, NA, 95, 100, NA, NA, NA, NA, 100, NA, 95, 100, 95)),list(cdmTableName = c("PERSON", "PERSON", "PERSON", "PERSON", "PERSON", "PERSON", "PERSON", "PERSON", "PERSON", "PERSON", "PERSON", "PERSON", "PERSON", "PERSON", "PERSON", "PERSON", "PERSON", "PERSON", "OBSERVATION_PERIOD", "OBSERVATION_PERIOD", "OBSERVATION_PERIOD", "OBSERVATION_PERIOD", "OBSERVATION_PERIOD", "VISIT_OCCURRENCE", "VISIT_OCCURRENCE", "VISIT_OCCURRENCE", "VISIT_OCCURRENCE", "VISIT_OCCURRENCE", "VISIT_OCCURRENCE", "VISIT_OCCURRENCE", "VISIT_OCCURRENCE", "VISIT_OCCURRENCE", "VISIT_OCCURRENCE", n"VISIT_OCCURRENCE", "VISIT_OCCURRENCE", "VISIT_OCCURRENCE", "VISIT_OCCURRENCE", "VISIT_OCCURRENCE", "VISIT_OCCURRENCE", "VISIT_OCCURRENCE", "CONDITION_OCCURRENCE", "CONDITION_OCCURRENCE", "CONDITION_OCCURRENCE", "CONDITION_OCCURRENCE", "CONDITION_OCCURRENCE", "CONDITION_OCCURRENCE", "CONDITION_OCCURRENCE", "CONDITION_OCCURRENCE", "CONDITION_OCCURRENCE", "CONDITION_OCCURRENCE", "CONDITION_OCCURRENCE", "CONDITION_OCCURRENCE", "CONDITION_OCCURRENCE", "CONDITION_OCCURRENCE", "CONDITION_OCCURRENCE", "CONDITION_OCCURRENCE", n"DRUG_EXPOSURE", "DRUG_EXPOSURE", "DRUG_EXPOSURE", "DRUG_EXPOSURE", "DRUG_EXPOSURE", "DRUG_EXPOSURE", "DRUG_EXPOSURE", "DRUG_EXPOSURE", "DRUG_EXPOSURE", "DRUG_EXPOSURE", "DRUG_EXPOSURE", "DRUG_EXPOSURE", "DRUG_EXPOSURE", "DRUG_EXPOSURE", "DRUG_EXPOSURE", "DRUG_EXPOSURE", "DRUG_EXPOSURE", "DRUG_EXPOSURE", "DRUG_EXPOSURE", "DRUG_EXPOSURE", "DRUG_EXPOSURE", "DRUG_EXPOSURE", "DRUG_EXPOSURE", "PROCEDURE_OCCURRENCE", "PROCEDURE_OCCURRENCE", "PROCEDURE_OCCURRENCE", "PROCEDURE_OCCURRENCE", "PROCEDURE_OCCURRENCE", n"PROCEDURE_OCCURRENCE", "PROCEDURE_OCCURRENCE", "PROCEDURE_OCCURRENCE", "PROCEDURE_OCCURRENCE", "PROCEDURE_OCCURRENCE", "PROCEDURE_OCCURRENCE", "PROCEDURE_OCCURRENCE", "PROCEDURE_OCCURRENCE", "PROCEDURE_OCCURRENCE", "DEVICE_EXPOSURE", "DEVICE_EXPOSURE", "DEVICE_EXPOSURE", "DEVICE_EXPOSURE", "DEVICE_EXPOSURE", "DEVICE_EXPOSURE", "DEVICE_EXPOSURE", "DEVICE_EXPOSURE", "DEVICE_EXPOSURE", "DEVICE_EXPOSURE", "DEVICE_EXPOSURE", "DEVICE_EXPOSURE", "DEVICE_EXPOSURE", "DEVICE_EXPOSURE", "DEVICE_EXPOSURE", n"MEASUREMENT", "MEASUREMENT", "MEASUREMENT", "MEASUREMENT", "MEASUREMENT", "MEASUREMENT", "MEASUREMENT", "MEASUREMENT", "MEASUREMENT", "MEASUREMENT", "MEASUREMENT", "MEASUREMENT", "MEASUREMENT", "MEASUREMENT", "MEASUREMENT", "MEASUREMENT", "MEASUREMENT", "MEASUREMENT", "MEASUREMENT", "MEASUREMENT", "VISIT_DETAIL", "VISIT_DETAIL", "VISIT_DETAIL", "VISIT_DETAIL", "VISIT_DETAIL", "VISIT_DETAIL", "VISIT_DETAIL", "VISIT_DETAIL", "VISIT_DETAIL", "VISIT_DETAIL", "VISIT_DETAIL", "VISIT_DETAIL", "VISIT_DETAIL", n"VISIT_DETAIL", "VISIT_DETAIL", "VISIT_DETAIL", "VISIT_DETAIL", "VISIT_DETAIL", "VISIT_DETAIL", "NOTE", "NOTE", "NOTE", "NOTE", "NOTE", "NOTE", "NOTE", "NOTE", "NOTE", "NOTE", "NOTE", "NOTE", "NOTE", "NOTE", "NOTE_NLP", "NOTE_NLP", "NOTE_NLP", "NOTE_NLP", "NOTE_NLP", "NOTE_NLP", "NOTE_NLP", "NOTE_NLP", "NOTE_NLP", "NOTE_NLP", "NOTE_NLP", "NOTE_NLP", "NOTE_NLP", "NOTE_NLP", "OBSERVATION", "OBSERVATION", "OBSERVATION", "OBSERVATION", "OBSERVATION", "OBSERVATION", "OBSERVATION", "OBSERVATION", "OBSERVATION", n"OBSERVATION", "OBSERVATION", "OBSERVATION", "OBSERVATION", "OBSERVATION", "OBSERVATION", "OBSERVATION", "OBSERVATION", "OBSERVATION", "SPECIMEN", "SPECIMEN", "SPECIMEN", "SPECIMEN", "SPECIMEN", "SPECIMEN", "SPECIMEN", "SPECIMEN", "SPECIMEN", "SPECIMEN", "SPECIMEN", "SPECIMEN", "SPECIMEN", "SPECIMEN", "SPECIMEN", "FACT_RELATIONSHIP", "FACT_RELATIONSHIP", "FACT_RELATIONSHIP", "FACT_RELATIONSHIP", "FACT_RELATIONSHIP", "LOCATION", "LOCATION", "LOCATION", "LOCATION", "LOCATION", "LOCATION", "LOCATION", n"LOCATION", "CARE_SITE", "CARE_SITE", "CARE_SITE", "CARE_SITE", "CARE_SITE", "CARE_SITE", "PROVIDER", "PROVIDER", "PROVIDER", "PROVIDER", "PROVIDER", "PROVIDER", "PROVIDER", "PROVIDER", "PROVIDER", "PROVIDER", "PROVIDER", "PROVIDER", "PROVIDER", "PAYER_PLAN_PERIOD", "PAYER_PLAN_PERIOD", "PAYER_PLAN_PERIOD", "PAYER_PLAN_PERIOD", "PAYER_PLAN_PERIOD", "PAYER_PLAN_PERIOD", "PAYER_PLAN_PERIOD", "PAYER_PLAN_PERIOD", "PAYER_PLAN_PERIOD", "PAYER_PLAN_PERIOD", "PAYER_PLAN_PERIOD", "PAYER_PLAN_PERIOD", "PAYER_PLAN_PERIOD", n"PAYER_PLAN_PERIOD", "PAYER_PLAN_PERIOD", "PAYER_PLAN_PERIOD", "PAYER_PLAN_PERIOD", "COST", "COST", "COST", "COST", "COST", "COST", "COST", "COST", "COST", "COST", "COST", "COST", "COST", "COST", "COST", "COST", "COST", "COST", "COST", "COST", "COST", "COST", "DRUG_ERA", "DRUG_ERA", "DRUG_ERA", "DRUG_ERA", "DRUG_ERA", "DRUG_ERA", "DRUG_ERA", "DOSE_ERA", "DOSE_ERA", "DOSE_ERA", "DOSE_ERA", "DOSE_ERA", "DOSE_ERA", "DOSE_ERA", "CONDITION_ERA", "CONDITION_ERA", "CONDITION_ERA", "CONDITION_ERA", "CONDITION_ERA", n"CONDITION_ERA"), cdmFieldName = c("person_id", "gender_concept_id", "year_of_birth", "month_of_birth", "day_of_birth", "CAST(birth_datetime AS DATE)", "race_concept_id", "ethnicity_concept_id", "location_id", "provider_id", "care_site_id", "person_source_value", "gender_source_value", "gender_source_concept_id", "race_source_value", "race_source_concept_id", "ethnicity_source_value", "ethnicity_source_concept_id", "observation_period_id", "person_id", "observation_period_start_date", "observation_period_end_date", n"period_type_concept_id", "visit_occurrence_id", "person_id", "visit_concept_id", "visit_start_date", "CAST(visit_start_datetime AS DATE)", "visit_end_date", "CAST(visit_end_datetime AS DATE)", "visit_type_concept_id", "provider_id", "care_site_id", "visit_source_value", "visit_source_concept_id", "admitting_source_concept_id", "admitting_source_value", "discharge_to_concept_id", "discharge_to_source_value", "preceding_visit_occurrence_id", "condition_occurrence_id", "person_id", "condition_concept_id", n"condition_start_date", "CAST(condition_start_datetime AS DATE)", "condition_end_date", "CAST(condition_end_datetime AS DATE)", "condition_type_concept_id", "condition_status_concept_id", "stop_reason", "provider_id", "visit_occurrence_id", "visit_detail_id", "condition_source_value", "condition_source_concept_id", "condition_status_source_value", "drug_exposure_id", "person_id", "drug_concept_id", "drug_exposure_start_date", "CAST(drug_exposure_start_datetime AS DATE)", "drug_exposure_end_date", n"CAST(drug_exposure_end_datetime AS DATE)", "verbatim_end_date", "drug_type_concept_id", "stop_reason", "refills", "quantity", "days_supply", "sig", "route_concept_id", "lot_number", "provider_id", "visit_occurrence_id", "visit_detail_id", "drug_source_value", "drug_source_concept_id", "route_source_value", "dose_unit_source_v
Error in ParallelLogger::clusterApply(cluster = cluster, x = checkDescriptions,  : 
  Error(s) when calling function 'fun', see earlier messages for details
> 
>

**Comment by zrwu** [comment]
> connectionDetails <- DatabaseConnector::createConnectionDetails(dbms = "allofus", user = "", password = "", server = "TestOMOPSQL01", port = "", extraSettings = "")
> cdmDatabaseSchema <- "dbo" 
> resultsDatabaseSchema <- "dqd"
> cdmSourceName <- "OMOP5"
> numThreads <- 3
> sqlOnly <- FALSE
> outputFolder <- "output"
> verboseMode <- TRUE 
> checkLevels <- c("TABLE", "FIELD", "CONCEPT")
> checkNames <- c("cdmField")
> DataQualityDashboard::executeDqChecks(connectionDetails = connectionDetails, cdmDatabaseSchema = cdmDatabaseSchema, resultsDatabaseSchema = resultsDatabaseSchema,cdmSourceName = cdmSourceName,numThreads = numThreads,sqlOnly = sqlOnly, outputFolder = outputFolder, verboseMode = verboseMode,writeToTable = writeToTable,checkLevels = checkLevels,checkNames = checkNames)

**Comment by alondhe** [comment]
Your dbms should be the type of database, not the name of the database. 

So, dbms should be:

"oracle" for Oracle
"postgresql" for PostgreSQL
"redshift" for Amazon Redshift
"sql server" for Microsoft SQL Server
"pdw" for Microsoft Parallel Data Warehouse (PDW)
"netezza" for IBM Netezza
"bigquery" for Google BigQuery
"sqlite" for SQLite

**Comment by alondhe** [comment]
To clarify, I think you would need to use this:

```
connectionDetails <- DatabaseConnector::createConnectionDetails(dbms = "sql server", user = "", password = "", server = "TestOMOPSQL01", port = "", extraSettings = "")
cdmDatabaseSchema <- "allofus.dbo"
resultsDatabaseSchema <- "allofus.dqd"
cdmSourceName <- "OMOP5"
```

**Comment by zrwu** [comment]
How do I use Windows Authentication if my user name is hs\zwu?

**Comment by zrwu** [comment]
1 returns error: "com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'zwu'

**Comment by alondhe** [comment]
From a Windows machine:

> To be able to use Windows authentication for SQL Server (and PDW), you have to install the JDBC driver. Download the .exe from [Microsoft ](https://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=11774) and run it, thereby extracting its contents to a folder. In the extracted folder you will find the file sqljdbc_4.0/enu/auth/x64/sqljdbc_auth.dll (64-bits) or sqljdbc_4.0/enu/auth/x86/sqljdbc_auth.dll (32-bits), which needs to be moved to location on the system path, for example to c:/windows/system32. If you not have write access to any folder in the system path, you can also specify the path to the folder containing the dll by setting the environmental variable PATH_TO_AUTH_DLL, so for example Sys.setenv("PATH_TO_AUTH_DLL" = "c:/temp") Note that the environmental variable needs to be set before calling connect for the first time.

Then, don't put anything for user or password.

**Comment by zrwu** [comment]
1 returns error: "com.microsoft.sqlserver.jdbc.SQLServerException: This driver is not configured for integrated authentication.


Zhen Wu
Data System Analyst , IT Research
University of California Davis Health
Office: (916) 731-1307
Confidentiality Notice:

This e-mail and any attachments thereto, is intended only for use by the addressee (s) named herein and may contain privileged and/or confidential information.  If you are not the intended recipient of this e-mail, any dissemination, distribution or copying of this e-mail in error, please notify the sender by e-mail or telephone and permanently delete all copies of this e-mail and any attachments.

**Comment by alondhe** [comment]
Looks like the DLL is not being found then. After you add it to your system path, I would recommend restarting your machine. Verify it's in the path by running echo %PATH% to ensure the folder that is hosting the DLL is in there.

**Comment by zrwu** [comment]
Hi Ajit,

I got same error after reboot my machine.

Path=C:\Windows\SysWOW64;
PATH_TO_AUTH_DLL=c:\temp
[cid:image002.png@01D5E017.0195C5C0]

d 1 returns error: "com.microsoft.sqlserver.jdbc.SQLServerException: This driver is not configured for integrated authentication. ClientConnectionId:a9e113c0-7fd1-4619-857d-f4d56791472c" when using argument(s): list(checkLevel = "FIELD", checkName =


Thank you for your help!
Zhen Wu
Data System Analyst , IT Research
University of California Davis Health
Office: (916) 731-1307
Confidentiality Notice:

This e-mail and any attachments thereto, is intended only for use by the addressee (s) named herein and may contain privileged and/or confidential information.  If you are not the intended recipient of this e-mail, any dissemination, distribution or copying of this e-mail in error, please notify the sender by e-mail or telephone and permanently delete all copies of this e-mail and any attachments.

**Comment by alondhe** [comment]
So the sqljdbc_auth.dll file is located in the path C:\Windows\SysWOW64, right?

**Comment by zrwu** [comment]
Correct.


Zhen Wu
Data System Analyst , IT Research
University of California Davis Health
Office: (916) 731-1307
Confidentiality Notice:

This e-mail and any attachments thereto, is intended only for use by the addressee (s) named herein and may contain privileged and/or confidential information.  If you are not the intended recipient of this e-mail, any dissemination, distribution or copying of this e-mail in error, please notify the sender by e-mail or telephone and permanently delete all copies of this e-mail and any attachments.

**Comment by zrwu** [comment]
Hi Aijt,

I changed my setup to a different machine and added sqljdbc_auth.dll file to both Java’s bin and lib folders in Java home because I cannot add it to the system folder (no permission). The connection seems worked now but there is a new error in an error report file, I am not sure why there is a string ‘cdm_source' added to the query:
DBMS:
sql server

Error:
com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'allofus.dbo.cdm_source'.

SQL:
select * from allofus.dbo.cdm_source;

R version:
R version 3.5.3 (2019-03-11)

Platform:
x86_64-w64-mingw32

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base
Other attached packages:
- magrittr (1.5)

connectionDetails <- DatabaseConnector::createConnectionDetails(dbms = "sql server",server = "TestOMOPSQL01", port = "1433", extraSettings = “trusted_conection=true”)
cdmDatabaseSchema <- "allofus.dbo"
resultsDatabaseSchema <- "allofus.dqd"
cdmSourceName <- "OMOP5"
numThreads <- 3
sqlOnly <- FALSE
outputFolder <- "output"
verboseMode <- TRUE
checkLevels <- c("TABLE", "FIELD", "CONCEPT")
checkNames <- c()


What are common values that I should set to checkNames?

Thanks you for your help!

Zhen Wu
Data System Analyst , IT Research
University of California Davis Health
Office: (916) 731-1307
Confidentiality Notice:

This e-mail and any attachments thereto, is intended only for use by the addressee (s) named herein and may contain privileged and/or confidential information.  If you are not the intended recipient of this e-mail, any dissemination, distribution or copying of this e-mail in error, please notify the sender by e-mail or telephone and permanently delete all copies of this e-mail and any attachments.

**Comment by alondhe** [comment]
Ah good that the initial issue is resolved. As for this one -- there is a table named cdm_source in the CDM, you'll need to have it in your database. The DDL for SQL Server is:

CREATE TABLE cdm_source
(
  cdm_source_name					VARCHAR(255)	NOT NULL ,
  cdm_source_abbreviation			VARCHAR(25)		NULL ,
  cdm_holder						VARCHAR(255)	NULL ,
  source_description				VARCHAR(MAX)	NULL ,
  source_documentation_reference	VARCHAR(255)	NULL ,
  cdm_etl_reference					VARCHAR(255)	NULL ,
  source_release_date				DATE			NULL ,
  cdm_release_date					DATE			NULL ,
  cdm_version						VARCHAR(10)		NULL ,
  vocabulary_version				VARCHAR(20)		NULL
)
;

**Comment by zrwu** [comment]
It worked!

What are common values that I should set to the variable checkNames?

Zhen Wu
Data System Analyst , IT Research
University of California Davis Health
Office: (916) 731-1307
Confidentiality Notice:

This e-mail and any attachments thereto, is intended only for use by the addressee (s) named herein and may contain privileged and/or confidential information.  If you are not the intended recipient of this e-mail, any dissemination, distribution or copying of this e-mail in error, please notify the sender by e-mail or telephone and permanently delete all copies of this e-mail and any attachments.

**Comment by zrwu** [comment]
got a new error:

Error in ParallelLogger::clusterApply(cluster = cluster, x = checkDescriptions,  : 
Error(s) when calling function 'fun', see earlier messages for details

**Comment by alondhe** [comment]
What do the logs say?

**Comment by zrwu** [comment]
Hi Author,

I am testing the data quality dashboard tool now and would like to add more custom data validation rules to this tool within our database.

If I save all the validation result data or validation query results to a database table which has  the same structure as you defined (it is used for importing result to a database table in R), how could I export the result data to a json file in a right format and merger the it with metadata in cdm_source and summery data as well to show the data in the dashboard?  Do you have the code to do so? If you have, it would be a big help!

I have manually export the result data in table (created by the tool in R) to a json file, it dose not work, please see attachment and advise me on how to reversed the data in a table to json file in a compatible format.

Thanks,
Zhen




Data System Analyst , IT Health Informatics
University of California Davis Health
1651 Alhambra Blvd
Sacramento, CA 95816
Office:   916.731.1307

zrwu@ucdavis.edu<mailto:zrwu@ucdavis.edu>
[A picture containing knife  Description automatically generated]
Enabling a Learning Health System
health.ucdavis.edu/data<http://www.health.ucdavis.edu/data>

**Comment by don-torok** [comment]
Zhen, if your goal is to "add more custom data validation rules to this tool", then you should learn how the rules are defined in the CSV workbooks (see inst/csv).  Once you figure out the relationship between Check Descriptions and the column headings in Concept Level csv file and how arguments are passed to the SQL scripts in inst/sql you will be able to add custom rules in the same manner that DQ developers do.

**Comment by clairblacketer** [comment]
I would also recommend looking at this article for how to change the thresholds: https://ohdsi.github.io/DataQualityDashboard/articles/Thresholds.html

**Comment by zrwu** [comment]
Hi Don and author,

Could you please tell where the complete source code can be download if it is an open source project?
My goals are to run validation query in SQL server without involving R code to speedup process, add custom rules to the tool set and reuse dashboard interface (presentation layer) without using BI such as BO or Tableau) if possible.

My first question is how to export validation result data in a database table result, metadata in a table cdm_source and summery data into a single data file in json format to display it in the DQD dashboard.
In json file

  1.  Data in execution log table (startTimestamp date, endTimestamp date, executionTime char(20))
{"startTimestamp":["2020-03-16 20:46:53"],"endTimestamp":["2020-03-16 20:54:34"],"executionTime":["8 mins"],

  1.  metadata in table cdm_source
  2.  validation result data in table CheckResults
My second quarrion is where the overall (summery) data stored.

[cid:image002.jpg@01D637F7.5AF12050]

Thank you for your help!
Zhen

Data System Analyst , IT Health Informatics
University of California Davis Health
1651 Alhambra Blvd
Sacramento, CA 95816
Office:   916.731.1307

zrwu@ucdavis.edu<mailto:zrwu@ucdavis.edu>
[A picture containing knife  Description automatically generated]
Enabling a Learning Health System
health.ucdavis.edu/data<http://www.health.ucdavis.edu/data>

**Comment by don-torok** [comment]
https://github.com/OHDSI/DataQualityDashboard
