### ISSUE TITLE
Vocab data quality checks

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/DataQualityDashboard#85]
Add data quality checks to assess the integrity of the vocabulary tables included content and NULL values.

**Comment by alondhe** [comment]
Would these checks be just within the vocab tables, or would they also do something with the CDM tables as well?

**Comment by fdefalco** [comment]
These would be just for the Vocab tables.  We're finding instances where things like an empty string existing instead of a null value can break certain checks.

**Comment by clairblacketer** [comment]
This is a duplicate, closing. Vocab checks were added with support of CDMv5.4
