### ISSUE TITLE
add dqd version to metadata

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/DataQualityDashboard#86]
Allow metadata to include the current version of this package used to generate the output.

**Comment by alondhe** [comment]
In the develop branch of my fork, I've added this to the metadata section

**Comment by alondhe** [comment]
Fixed in latest commit

**Comment by jimfrankfort** [comment]
thanks for updating the DQD! We ran this and see the version listed as DQD 1.0.0. This is nice but not sufficient to address our use case. We have 3 data partners and we want to all run the exact same DQD. I don't think 1.0.0 does it. the prior release had some bugs fixed (e.g. case statement in field names)....what would that version be? Although we can sync our DQDs by loading a specific commitID ID, it would be nice to be able to tell from the meta data. Apologies in advance if I am mistaken. thx
