### ISSUE TITLE
Logviewer vs Dashboard - Without cdm_source

### ISSUE THREAD

**Issue by SSMK-wq** [OHDSI/DataQualityDashboard#89]
Hi,

I was following the tutorial to run DQD at our end and must say that the dashboard looks great and it is very useful. Thanks for your efforts.

Before I explain the issue, I would like to let you know that both cdm_source and metadata tables are empty at our site (no default values as well). I understand we need to have one record in cdm_source for generating DQD successfully. But now the issue is

1) When I just gave my Data source name (that we see in Atlas "Data sources tab"), the code after execution generated some logs (which seems to contain valid messages). 

But is it even possible? 

Because my cdm_source table is empty.  I verified it in the db. I use postgresql (pgadmin) to write queries

As expected DQD is just launched but doesn't display anything whereas I do see logs alone? The below code helped generate logs 

`ParallelLogger::launchLogViewer(logFileName = file.path(outputFolder, cdmSourceName, 
                                                        sprintf("log_DqDashboard_%s.txt", cdmSourceName)))`

Most of these logs are about date fields for which we have another issue (double quotes generated in template) open. 

I was expecting the logs to not generate as well because cdm_source is empty.  Is our Atlas Data source and CDM_source related anyway? if yes, then DQD should also be generated. If not, then I shouldn't have seen the logs. trying to understand the link here. Is it something related to webAPI thing which I don't have much knowledge to talk about?

But when I insert a record into "cdm_source" table, I still see that DQD is empty. Not sure why

Kindly request you to help me with this. 

Thanks for your help and efforts in creating this dashboard.

**Comment by clairblacketer** [comment]
Hi, so the code will run if you don’t have a CDM_SOURCE table but it will not generate the JSON correctly. This is intentional so that if you share the JSON to be viewed there is some information about the database it was run on.

**Comment by SSMK-wq** [comment]
Hi @clairblacketer - Thanks for your response. 

1) So the logs files generated are based on the database connection info and not based on cdm_source field. Am I right to understand this?

2) But even when I insert a record into cdm_source, I see that DQD is still empty. Is there any other item that I should be looking at?

**Comment by alondhe** [comment]
Hi @SSMK-wq,

I'd like to take several steps back here. DQD does not tie into Atlas in any way at this time, it is a separate tool. So let's just focus on your DQD issue.

If you have a record in CDM_SOURCE, the JSON file should generate. Can you confirm this happened?

If it did and you are not seeing results when launching the viewDqDashboard function, most likely it's an issue with the file path you're providing the function. It has to be full path to the file, so for example, "C:\git\DQD\results.json" rather than "results.json". Can you confirm that you are using the full path?

**Comment by SSMK-wq** [comment]
Yes, as you said,It was a path Issue. This issue can be closed

**Comment by Ak784** [comment]
Sorry to revive this old post. I have multiple questions on this area.

q1) May I check in which step do we generate the json file? When I run DataQualityDashboard::executeDqChecks(), the output in display on screen. But the same output (displayed on screen) is also stored as a json file in output folder? Am I right to understand this?

q2)  Even though I give the full file path as shown below for parallellogger, I get an error message that `cannot open the connection`

```
ParallelLogger::launchLogViewer(logFileName = file.path(outputFolder, cdmSourceName, 
                                                        sprintf("C:\\Users\\test\\output\\hospital\\log_DqDashboard_My CDM source.txt", cdmSourceName)))
```

q3)  Even though I give the full file path as shown below for `viewDqDashboard function` , I see an empty DQD. Where is the json file here for `viewDQDashboard` function to look for? Will `viewDQDashboard` look for json file (if created) from the `executeDqChecks()` function?

q4) Could there by any other reason as to why my DQD is empty even after pointing to the full path of json file. 

q5) If all my checks fail, can it still launch DQD with some info (and not be empty)?
