### ISSUE TITLE
Get finalized v5.3.1 Excel file

### ISSUE THREAD

**Issue by alondhe** [OHDSI/DataQualityDashboard#9]
@clairblacketer -- can we finalize the v5.3.1 Excel workbook that will be used as the input? Currently we're operating off of the v6 version, and I believe some changes have been made this week.

**Comment by clairblacketer** [comment]
Yes will clean it up today and send it over. The structure hasn't changed much so we should still be able to start writing the SQL code.

**Comment by clairblacketer** [comment]
Closed with [commit](https://github.com/OHDSI/DataQualityDashboard/commit/49db66d4b623050f07a338f81d84f04957f7febb)
