### ISSUE TITLE
Unable to view dashboard but able to see results in R

### ISSUE THREAD

**Issue by Ak784** [OHDSI/DataQualityDashboard#90]
Hi folks,

I ran DQD R code given below

`DataQualityDashboard::executeDqChecks(connectionDetails = connectionDetails, 
                                      cdmDatabaseSchema = cdmDatabaseSchema, 
                                      resultsDatabaseSchema = resultsDatabaseSchema,
                                      cdmSourceName = cdmSourceName, 
                                      numThreads = numThreads,
                                      sqlOnly = sqlOnly, 
                                      outputFolder = outputFolder, 
                                      verboseMode = verboseMode,
                                      writeToTable = writeToTable,
                                      checkLevels = checkLevels,
                                      checkNames = checkNames)`

Though this produced some output like below in R studio console, 

```
`$Overview$percentFailed
[1] 3

$Overview$countTotalPlausibility
[1] 2126

$Overview$countTotalConformance
[1] 785

$Overview$countTotalCompleteness
[1] 401

$Overview$countFailedPlausibility
[1] 43

$Overview$countFailedConformance
[1] 49

$Overview$countFailedCompleteness
[1] 11

$Overview$countPassedPlausibility
[1] 2083`

```
But   **I don't see anything in the browser. It is empty. Moreover my cdm_source table has a record in my db**  (I did see the old issue on this). I reopened my browser/ cleared the cache etc. but in vain

Can anyone let me know what would be the cause of browser not just displaying anything but blank?

**Comment by alondhe** [comment]
When you open the browser (Chrome), can you right mouse click and then hit Inspect, then click on Console, and then reply back if there's any errors listed?

**Comment by alondhe** [comment]
@Ak784 -- Also, are you using the full path to the JSON when calling the viewDqDashboard() function?

**Comment by Ak784** [comment]
Hi,

Earlier, I had a code like this which didn't fetch the file

DataQualityDashboard::viewDqDashboard(jsonPath = file.path(getwd(), outputFolder, cdmSourceName, sprintf("results_%s.json", cdmSourceName)))

Later I modified it to below (remoed getwd())

DataQualityDashboard::viewDqDashboard(jsonPath = file.path(outputFolder, cdmSourceName, sprintf("results_%s.json", cdmSourceName)))

My output folder path that I set earlier was - "C:/Users/testuser/Desktop/DQD/output"

getwd() results in - "C:/Users/testuser/Desktop/DQD"

It's a path issue as you suggested. 

Thanks for your time.

**Comment by alondhe** [comment]
Great! Yeah, the path parameter can be a bit tricky. Something for us to consider improving...
