### ISSUE TITLE
Remove CAST(...datetime as DATE) 

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/DataQualityDashboard#92]
As part of PR #76 all the datetime fields were cast to dates. The cast should not be done in the csv in the field name but it could moved to a different spot.

**Comment by alondhe** [comment]
Fixed in latest commit

**Comment by alondhe** [comment]
Looks like we're playing whack-a-mole with this issue. I think we'll need the script to have conditional logic for the cdmFieldName and plausibleValueHigh comparison. But we can't do this in the CSV as we did previously.

**Comment by alondhe** [comment]
We'll handle this in #98
