### ISSUE TITLE
Datatables Warning

### ISSUE THREAD

**Issue by CartWill** [OHDSI/DataQualityDashboard#97]
When I try to load the Shiny app, I get a warning popup in the browser

> DataTables warning: table id=dt-results - Cannot reinitialise DataTable.  For more information about this error, please see http://datatables.net/tn/3

The top counts load but it looks like it's stuck with some test data in the detailed results.  It looks like shiny app is loading a test results.json from the ../Library/DataQualityDashboard/shiny/Apps/www  R package folder and then tries to re-initialize that results table with the the actual JSON file with the real results.  The only way to can make the warning go away and get the Shiny app to load the real results is to delete the results.json from the R package.

**Comment by alondhe** [comment]
Hi @CartWill -- did you just update your installation of DQD (like in the last few hours)?

**Comment by CartWill** [comment]
Yes but I was getting that problem in older versions too.

**Comment by alisonpark** [comment]
Hi @CartWill. Did you find a solution to this issue?  I'm getting this exact same error in v.2.5.0 and v.2.6.0.  Thanks

**Comment by CartWill** [comment]
@alisonpark  Not that I can remember besides what I said originally to delete json file in the actual installed library folder.

**Comment by alisonpark** [comment]
Thank you @CartWill. That wasn't working initially but it is now!
